# Generated by Django 5.2.17 on 2026-09-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0002_goodsreceipt_goodsreceiptline"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={
                "ordering": ["-bill_date", "-id"],
                "permissions": [("post_bill", "Can post bills and issue debit notes")],
            },
        ),
        migrations.AlterModelOptions(
            name="goodsreceipt",
            options={
                "ordering": ["-receipt_date", "-id"],
                "permissions": [
                    ("post_goodsreceipt", "Can post goods receipts and returns")
                ],
            },
        ),
    ]
