# Generated by Django 5.2.17 on 2026-09-19 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("core", "0008_company_tax_rounding"),
        ("purchasing", "0003_alter_bill_options_alter_goodsreceipt_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.currency",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="due_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                editable=False,
                help_text="Rate to the base currency captured at posting time.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="number",
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name="bill",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.paymentterms",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="number",
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="number",
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name="bill",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="The vendor's own invoice number — what they will quote when chasing payment.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="The vendor's own quote or reference, if any.",
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="unique_bill_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsreceipt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="unique_goods_receipt_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="unique_purchase_order_number",
            ),
        ),
    ]
