# Generated by Django 5.2.17 on 2026-09-19 19:40

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("purchasing", "0004_bill_currency_bill_due_date_bill_exchange_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billline",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Line discount, e.g. 10.00 for 10% off.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="taxes",
            field=models.ManyToManyField(
                blank=True, related_name="bill_lines", to="accounting.tax"
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Line discount, e.g. 10.00 for 10% off.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Where a non-stocked line lands when this order is billed.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="taxes",
            field=models.ManyToManyField(
                blank=True, related_name="purchase_order_lines", to="accounting.tax"
            ),
        ),
        migrations.AlterField(
            model_name="billline",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="On a sales document, left blank it resolves from the price list or the item's list price.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="On a sales document, left blank it resolves from the price list or the item's list price.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
