# Generated by Django 5.2.17 on 2026-09-19 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0005_billline_discount_percent_billline_taxes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billline",
            name="order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this line bills a purchase order line, so the order cannot be billed twice for the same goods.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bill_lines",
                to="purchasing.purchaseorderline",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="bill_policy",
            field=models.CharField(
                choices=[
                    ("received", "Bill what has been received"),
                    ("ordered", "Bill the whole order"),
                ],
                default="received",
                help_text="Accept a bill for the whole order, or only for what has actually arrived.",
                max_length=16,
            ),
        ),
    ]
