# Generated by Django 5.2.17 on 2026-09-20 01:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("core", "0009_company_default_purchase_expense_account_and_more"),
        ("purchasing", "0007_billpayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("debits__isnull", True), models.Q(("reference", ""), _negated=True)
                ),
                fields=("vendor", "reference"),
                name="one_bill_per_vendor_reference",
            ),
        ),
    ]
