# Generated by Django 5.2.17 on 2026-09-20 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("purchasing", "0008_bill_one_bill_per_vendor_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="billline",
            name="debits_line",
            field=models.ForeignKey(
                blank=True,
                help_text="On a debit note line, the bill line being given back.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="debit_lines",
                to="purchasing.billline",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="posted_account",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Where this line actually landed when the bill posted, frozen so a debit note gives it back to the same place.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
