# Generated by Django 5.2.17 on 2026-09-20 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("purchasing", "0009_billline_debits_line_billline_posted_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="settlement_discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Early-settlement discount taken against this bill.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="settlement_discount_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
    ]
