# Generated by Django 5.2.17 on 2026-09-20 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_chargetype"),
        ("core", "0012_company_vendor_prepayment_account"),
        ("inventory", "0005_item_sale_price"),
        ("purchasing", "0011_bill_is_prepayment_prepaymentapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billline",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                help_text="Set instead of an item when this line is freight, handling or similar.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="accounting.chargetype",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                help_text="Set instead of an item when this line is freight, handling or similar.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="accounting.chargetype",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_order_lines",
                to="inventory.item",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderline",
            name="uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.unitofmeasure",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("charge__isnull", True), ("item__isnull", False)),
                    models.Q(("charge__isnull", False), ("item__isnull", True)),
                    _connector="OR",
                ),
                name="po_line_is_item_or_charge",
            ),
        ),
    ]
