# Generated by Django 5.2.17 on 2026-09-20 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_payment_voided_entry"),
        ("purchasing", "0012_billline_charge_purchaseorderline_charge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billpayment",
            name="fx_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Realised exchange difference posted when this allocation was made.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
    ]
