# Generated by Django 5.2.17 on 2026-09-20 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0013_billpayment_fx_entry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "ordering": ["-order_date", "-id"],
                "permissions": [
                    (
                        "approve_purchaseorder",
                        "Can approve orders that breach the spend policy",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="approval_note",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="approved_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseApprovalPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "max_order_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Orders above this total need approval.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "max_line_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Catches one very large line inside an otherwise ordinary order.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "require_approval_without_vendor_price",
                    models.BooleanField(
                        default=False,
                        help_text="Need approval when a line's price was typed in rather than taken from an agreed vendor price.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "purchase approval policies",
                "ordering": ["code"],
            },
        ),
    ]
