# Generated by Django 5.2.17 on 2026-09-20 02:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_paymenttermsline"),
        ("inventory", "0006_stockmovement_value_adjustment"),
        ("purchasing", "0014_alter_purchaseorder_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VendorPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="Smallest order this price applies to — the quantity break.",
                        max_digits=18,
                    ),
                ),
                (
                    "vendor_item_code",
                    models.CharField(
                        blank=True,
                        help_text="The vendor's own part number, which is what their invoice will quote.",
                        max_length=64,
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Days from order to delivery, as agreed.",
                        null=True,
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                (
                    "is_preferred",
                    models.BooleanField(
                        default=False,
                        help_text="Buy this item from this vendor by default.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_prices",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_prices",
                        to="core.party",
                    ),
                ),
            ],
            options={
                "ordering": ["item", "vendor", "-min_quantity"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("unit_price__gte", 0)),
                        name="vendor_price_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("min_quantity__gte", 0)),
                        name="vendor_price_min_quantity_not_negative",
                    ),
                ],
            },
        ),
    ]
