# Generated by Django 5.2.17 on 2026-09-20 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_paymenttermsline"),
        ("inventory", "0006_stockmovement_value_adjustment"),
        ("purchasing", "0016_purchaseorderline_expected_date_blanketorder_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRequisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, editable=False, max_length=32)),
                ("request_date", models.DateField()),
                ("needed_by", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("ordered", "Ordered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("justification", models.TextField(blank=True)),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "decision_note",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        help_text="The employee asking.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisitions",
                        to="core.party",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-request_date", "-id"],
                "permissions": [
                    ("decide_purchaserequisition", "Can approve or reject requisitions")
                ],
            },
        ),
        migrations.CreateModel(
            name="PurchaseRequisitionLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="What the requester thinks it costs — an estimate, not an agreed price.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requisition_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="purchasing.purchaserequisition",
                    ),
                ),
                (
                    "suggested_vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who the requester had in mind, if anyone. Not binding.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.party",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="requisition_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this line fulfils a requisition, so the request can be traced from ask to receipt.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_lines",
                to="purchasing.purchaserequisitionline",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequisition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="unique_requisition_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaserequisitionline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="requisition_line_quantity_positive",
            ),
        ),
    ]
