# Generated by Django 5.2.17 on 2026-09-20 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_stockmovement_value_adjustment"),
        (
            "purchasing",
            "0018_requestforquotation_rfqinvitation_rfqline_rfqquote_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="subcontract_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Where components sit while the subcontractor holds them. Still the company's stock — it has only moved, not been sold.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.warehouse",
            ),
        ),
        migrations.CreateModel(
            name="SubcontractComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_per",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="How many of this component go into one of the finished item.",
                        max_digits=18,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplied_to",
                        to="inventory.item",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="purchasing.purchaseorderline",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_per__gt", 0)),
                        name="component_quantity_positive",
                    ),
                    models.UniqueConstraint(
                        fields=("order_line", "item"), name="one_component_row_per_item"
                    ),
                ],
            },
        ),
    ]
