# Generated by Django 5.2.17 on 2026-09-20 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0019_purchaseorder_subcontract_warehouse_and_more"),
        ("sales", "0023_delivery_is_drop_ship"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="drop_ship_for",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this order exists only to ship a sales order direct from the vendor.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drop_ship_orders",
                to="sales.salesorder",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="shipping_note",
            field=models.CharField(
                blank=True,
                help_text="Where the vendor should deliver, when it is not to the company.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="sales_order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer line this drop-ship fulfils.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="drop_ship_lines",
                to="sales.salesorderline",
            ),
        ),
    ]
