# Generated by Django 5.2.17 on 2026-09-20 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_bankstatement_bankstatementline"),
        ("core", "0014_paymenttermsline"),
        ("inventory", "0006_stockmovement_value_adjustment"),
        ("purchasing", "0020_purchaseorder_drop_ship_for_and_more"),
        ("sales", "0023_delivery_is_drop_ship"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="billline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="bill_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="blanketorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="blanket_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="goodsreceiptline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_received__gt", 0)),
                name="received_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="purchaseorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="po_line_quantity_positive",
            ),
        ),
    ]
