# Generated by Django 5.2.17 on 2026-09-20 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0021_billline_bill_line_quantity_positive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptline",
            name="reverses_line",
            field=models.ForeignKey(
                blank=True,
                help_text="On a return line, the receipt line being sent back.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_lines",
                to="purchasing.goodsreceiptline",
            ),
        ),
    ]
