# Generated by Django 5.2.17 on 2026-09-20 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("purchasing", "0023_landedcostapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "up_to_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty for no ceiling — the final tier.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Members of this group may approve up to the limit.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="auth.group",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="purchasing.purchaseapprovalpolicy",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["up_to_amount", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("up_to_amount__isnull", True),
                            ("up_to_amount__gt", 0),
                            _connector="OR",
                        ),
                        name="approval_tier_limit_positive",
                    ),
                    models.UniqueConstraint(
                        fields=("policy", "group"), name="one_tier_per_group_and_policy"
                    ),
                ],
            },
        ),
    ]
