# Generated by Django 5.2.17 on 2026-09-20 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_paymenttermsline"),
        ("inventory", "0007_warehouse_is_quarantine"),
        ("purchasing", "0025_purchaseorderline_inspect_on_receipt_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReorderRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "minimum",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Order when projected stock falls to or below this.",
                        max_digits=18,
                    ),
                ),
                (
                    "target",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Order enough to bring projected stock back up to this.",
                        max_digits=18,
                    ),
                ),
                (
                    "multiple_of",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Round the order up to a whole case, pallet or minimum order quantity.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reorder_rules",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Buy from this vendor. Left empty, the preferred or cheapest agreed price decides.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reorder_rules",
                        to="core.party",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reorder_rules",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["item", "warehouse"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("minimum__gte", 0)),
                        name="reorder_minimum_not_negative",
                    ),
                    models.UniqueConstraint(
                        fields=("item", "warehouse"),
                        name="one_reorder_rule_per_item_and_warehouse",
                    ),
                ],
            },
        ),
    ]
