# Generated by Django 5.2.17 on 2026-09-20 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_bankstatement_bankstatementline"),
        ("purchasing", "0027_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequisitionline",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Which budget this is asking to spend. Carried to the order line.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
