# Generated by Django 5.2.17 on 2026-09-20 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accountingperiod"),
        ("purchasing", "0028_purchaserequisitionline_expense_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billline",
            name="expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Where a line lands when it expenses. A stocked line that a receipt accrued for clears GRNI instead and needs none.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
