# Generated by Django 5.2.17 on 2026-09-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_remove_stockcountline_one_count_line_per_item_and_more"),
        ("purchasing", "0029_alter_billline_expense_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptline",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Which batch arrived. Required when the item is tracked: the receipt is where a batch enters the company, and if it is not recorded here there is nothing to trace it from.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.lot",
            ),
        ),
    ]
