# Generated by Django 5.2.17 on 2026-09-20 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0018_remove_stockcountline_one_count_line_per_untracked_item_and_more",
        ),
        ("purchasing", "0030_goodsreceiptline_lot"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptline",
            name="bin",
            field=models.ForeignKey(
                blank=True,
                help_text="Which shelf the goods were put on. Required when the warehouse is binned.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.storagebin",
            ),
        ),
    ]
