# Generated by Django 5.2.17 on 2026-09-20 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0020_remove_stockadjustmentline_adjustment_line_quantity_not_zero_and_more",
        ),
        ("purchasing", "0031_goodsreceiptline_bin"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptline",
            name="stock_movement",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="What this line wrote into the stock ledger. Kept because under FIFO a landed cost has to raise the layer these goods created, not an average of every layer on the shelf.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.stockmovement",
            ),
        ),
    ]
