# Generated by Django 5.2.17 on 2026-09-21 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0021_stockadjustment_from_standard_change"),
        ("purchasing", "0032_goodsreceiptline_stock_movement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goodsreceiptline",
            name="bin",
            field=models.ForeignKey(
                blank=True,
                help_text="Which shelf to put the goods on. Left blank in a binned warehouse, the receipt puts them next to the same item and records where.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.storagebin",
            ),
        ),
    ]
