# Generated by Django 5.2.17 on 2026-09-22 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0009_workorder_time_allowance_percent"),
        ("purchasing", "0034_goodsreceiptline_landed_warehouse_receiptroutemove"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="bom",
            field=models.ForeignKey(
                blank=True,
                help_text="What goes into the item, when this line is job work. The components are computed from it rather than typed, so a specification that moves does not leave a stale copy of itself on an open order. Rebuilt only while the order is a draft: the job worker was sent what the order said at the time.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subcontract_lines",
                to="manufacturing.billofmaterials",
            ),
        ),
        migrations.AddField(
            model_name="subcontractcomponent",
            name="is_computed",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Set when a bill of materials works this row out. Such a row refuses to be edited by hand: the edit would survive until the next rebuild and no longer.",
            ),
        ),
        migrations.AlterField(
            model_name="subcontractcomponent",
            name="quantity_per",
            field=models.DecimalField(
                decimal_places=6,
                help_text="How many of this component go into one of the finished item, in the component's own stocking unit. Six places, not four: a sack's sewing thread is about 0.0012 kg a bag, and four places lose a fortieth of it on every sack.",
                max_digits=18,
            ),
        ),
    ]
