# Generated by Django 5.2.17 on 2026-09-22 21:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("inventory", "0026_stockvaluationsnapshot"),
        ("purchasing", "0035_purchaseorderline_bom_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="reorderrule",
            name="maximum_order_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="The most that goes into one order — a silo, a mixer or a lorry. A requirement larger than this is split into several orders for the same date rather than one nobody can take.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reorderrule",
            name="minimum_order_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="The least anybody will sell, or the least worth making. Read by the plan: a vendor with a one-tonne minimum does not deliver two hundred kilos because that is what the arithmetic asked for.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="reorderrule",
            name="order_period_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order once for this many days of demand instead of once per shortage. Nought is lot for lot, which is exact and raises twelve orders for twelve daily call-offs; a week turns those into two and carries a little stock for the privilege.",
            ),
        ),
        migrations.AlterField(
            model_name="reorderrule",
            name="multiple_of",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Round the order up to a whole case, pallet or bag size.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="reorderrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimum_order_quantity__isnull", True),
                    ("minimum_order_quantity__gt", 0),
                    _connector="OR",
                ),
                name="reorder_minimum_order_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="reorderrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maximum_order_quantity__isnull", True),
                    ("maximum_order_quantity__gt", 0),
                    _connector="OR",
                ),
                name="reorder_maximum_order_quantity_positive",
            ),
        ),
    ]
