# Generated by Django 5.2.17 on 2026-09-26 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0023_outsidemovement_routingoperation_is_outside_and_more"),
        ("purchasing", "0036_reorderrule_maximum_order_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptline",
            name="outside_movement",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Where this line put a vendor's work into a run, when it pays for an outside step.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipt_lines",
                to="manufacturing.outsidemovement",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="work_order_operation",
            field=models.ForeignKey(
                blank=True,
                help_text="The outside step of a run this line pays a vendor for — lamination sent out mid-routing, say. Its receipt puts the vendor's charge into the run's work in progress through the goods-received accrual, rather than posting nothing and expensing the bill as an ordinary service would.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_lines",
                to="manufacturing.workorderoperation",
            ),
        ),
    ]
