# Generated by Django 5.2.17 on 2026-09-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0037_goodsreceiptline_outside_movement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billline",
            name="accrued_base",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                editable=False,
                help_text="The same in base currency, at the receipts' own rates — exactly what this line took out of goods received not invoiced. A debit note puts back the same, and the gap between this and the bill's own rate is an exchange difference.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="accrued_doc",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                editable=False,
                help_text="What the receipts this line clears accrued, in the bill's currency, frozen when it posted.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                editable=False,
                help_text="What one unit of the order's currency was worth in base currency when this receipt posted, frozen. The stock and the accrual are booked at it, and the bill clears the accrual at exactly what this booked — any movement in the rate before the bill is an exchange difference, not a change in what the goods cost. Blank on receipts posted before this was recorded, which booked the order's figures as base currency: read as one, because that is what they did.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="accrued_unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                editable=False,
                help_text="The same in base currency, at the receipt's rate — what went into goods received not invoiced per unit.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceiptline",
            name="accrued_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                editable=False,
                help_text="The agreed price this receipt accrued at, in the order's currency, frozen. The order's price can still be revised before a bill arrives; what this receipt booked cannot.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
