# Generated by Django 5.2.17 on 2026-09-27 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0012_chargetype_hsn_code_tax_gst_head"),
        ("purchasing", "0038_billline_accrued_base_billline_accrued_doc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="party_gstin",
            field=models.CharField(blank=True, editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name="bill",
            name="party_registration",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Regular, SEZ, overseas… as it stood: which table of a return the document is filed in.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="place_of_supply",
            field=models.CharField(blank=True, editable=False, max_length=2),
        ),
        migrations.AddField(
            model_name="bill",
            name="taxes_recorded",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Set when posting wrote down what each line bore. A document posted before that existed computes, as it always did.",
            ),
        ),
        migrations.AddField(
            model_name="billline",
            name="hsn_code",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="HSN or SAC as it stood when the line posted — the code its return reports, whatever the item says later.",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="BillLineTax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=9)),
                ("gst_head", models.CharField(blank=True, max_length=8)),
                (
                    "taxable",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The line's net amount the tax was charged on, in the document's currency.",
                        max_digits=18,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorded_taxes",
                        to="purchasing.billline",
                    ),
                ),
                (
                    "tax",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.tax",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0), ("taxable__gte", 0)),
                        name="purchasing_billlinetax_not_negative",
                    )
                ],
            },
        ),
    ]
