# Generated by Django 5.2.17 on 2026-09-28 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_refold_company_wide_valuation"),
        ("purchasing", "0039_recorded_taxes"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Where it is to be received. Planning counts it as coming there; blank, it is counted as coming to whichever warehouse is planned, which is right only on one site. A receipt line that names no warehouse takes this one.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="purchaserequisitionline",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Where it is wanted. Carried to the order line, and what planning counts it as coming to.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.warehouse",
            ),
        ),
    ]
