# Generated by Django 5.2.17 on 2026-10-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0041_drawdown_fx_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="posted_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="The total when it posted, in its own currency. A fact of the posting, which cannot change; reports use it to pass over what is already settled without working every total out again.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
