# Generated by Django 5.2.17 on 2026-10-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0042_posted_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="billline",
            name="posted_net",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="The line's amount before tax when it posted. With the taxes it recorded, what reports sum instead of working every line out again.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
