# Generated by Django 5.2.17 on 2026-10-04 18:59

from django.conf import settings
from django.db import migrations, models

from apps.core.trigram import trigram_indexes


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0016_list_indexes"),
        ("core", "0018_login_failures"),
        ("inventory", "0033_list_indexes"),
        ("purchasing", "0043_posted_net"),
        ("sales", "0042_posted_net"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bill",
            index=models.Index(fields=["bill_date", "id"], name="bill_by_date"),
        ),
        migrations.AddIndex(
            model_name="goodsreceipt",
            index=models.Index(fields=["receipt_date", "id"], name="receipt_by_date"),
        ),
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["order_date", "id"], name="purchase_order_by_date"
            ),
        ),
        # ?search= on the lists (apps/core/trigram.py).
        trigram_indexes(
            ("purchasing_purchaseorder", "number"),
            ("purchasing_purchaseorder", "reference"),
            ("purchasing_bill", "number"),
            ("purchasing_bill", "reference"),
            ("purchasing_goodsreceipt", "number"),
            ("purchasing_goodsreceipt", "reference"),
        ),
    ]
