# Generated by Django 5.2.17 on 2026-10-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0044_list_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderline",
            name="closed_short_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorderline",
            name="closed_short_reason",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
