# Generated by Django 5.2.17 on 2026-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0045_purchase_line_close_short"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="is_opening_balance",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Brought in at go-live (import_csv open_bills): what the old system's bill still had owing. Its credit was claimed there; no return here counts it.",
            ),
        ),
    ]
