# Generated by Django 5.2.17 on 2026-10-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0046_opening_balance_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="corrects_old_supply",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="A debit note with its own GST on a bill the old system booked: it takes back input tax this month.",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="old_bill_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="On such a note, what the old bill was for in all: no more is debited against it.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
