# Generated by Django 5.2.17 on 2026-10-06 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0017_tds_sections"),
        ("purchasing", "0047_old_supply_notes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TdsChallan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "month",
                    models.DateField(
                        help_text="The month the deductions were made in (its first day)."
                    ),
                ),
                ("date", models.DateField(help_text="The day it was paid.")),
                (
                    "challan_number",
                    models.CharField(
                        help_text="The challan serial number.", max_length=16
                    ),
                ),
                (
                    "bsr_code",
                    models.CharField(
                        help_text="The bank branch's BSR code.", max_length=7
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=18
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.tdssection",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TdsDeduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base", models.DecimalField(decimal_places=2, max_digits=18)),
                ("rate_percent", models.DecimalField(decimal_places=4, max_digits=7)),
                ("pan", models.CharField(blank=True, max_length=10)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("date", models.DateField()),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tds_deductions",
                        to="purchasing.bill",
                    ),
                ),
                (
                    "challan",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deductions",
                        to="purchasing.tdschallan",
                    ),
                ),
                (
                    "covered_bills",
                    models.ManyToManyField(
                        help_text="The bills its base is made of: this one, and under 194C the year's earlier ones untaxed until the threshold was passed.",
                        related_name="+",
                        to="purchasing.bill",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "reversed_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.tdssection",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="tdschallan",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="tds_challan_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="tdsdeduction",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="tds_deduction_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="tdsdeduction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reversed_entry__isnull", True)),
                fields=("bill", "section"),
                name="one_standing_tds_per_bill_and_section",
            ),
        ),
    ]
