# Generated by Django 5.2.17 on 2026-10-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0048_tds"),
    ]

    operations = [
        migrations.AddField(
            model_name="billlinetax",
            name="reverse_charge",
            field=models.BooleanField(
                default=False,
                help_text="Paid by the company, not charged by the vendor, as the tax stood.",
            ),
        ),
    ]
