# Generated by Django 5.2.17 on 2026-10-07 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0020_cost_centres"),
        ("purchasing", "0050_freight_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="billline",
            name="cost_centre",
            field=models.ForeignKey(
                blank=True,
                help_text="The centre this expense is for; carried onto the ledger line when the bill posts.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.costcentre",
            ),
        ),
    ]
