# Generated by Django 5.2.17 on 2026-10-07 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_saved_filters"),
        ("purchasing", "0052_custom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="freight_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ex_works", "Ex works: the buyer collects"),
                    (
                        "for_destination",
                        "FOR destination: the seller delivers, freight paid",
                    ),
                    (
                        "to_pay",
                        "To pay: the seller sends, the buyer pays the transporter",
                    ),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="incoterm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXW", "EXW: ex works"),
                    ("FCA", "FCA: free carrier"),
                    ("FOB", "FOB: free on board"),
                    ("CFR", "CFR: cost and freight"),
                    ("CIF", "CIF: cost, insurance and freight"),
                    ("DAP", "DAP: delivered at place"),
                    ("DDP", "DDP: delivered duty paid"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.paymentterms",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="port_of_loading",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="VendorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "standing",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("trial", "On trial: an order to them is approved first"),
                            ("blocked", "Blocked: no new order"),
                        ],
                        default="approved",
                        max_length=16,
                    ),
                ),
                (
                    "standing_reason",
                    models.CharField(
                        blank=True,
                        help_text="Why they are on trial or blocked; whoever meets it is told.",
                        max_length=255,
                    ),
                ),
                (
                    "payment_hold",
                    models.BooleanField(
                        default=False,
                        help_text="Nothing is paid to them until it is lifted: a dispute, a quality claim.",
                    ),
                ),
                ("payment_hold_reason", models.CharField(blank=True, max_length=255)),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How long they usually take, where no agreed price for the item says: planning reads it.",
                        null=True,
                    ),
                ),
                (
                    "freight_terms",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ex_works", "Ex works: the buyer collects"),
                            (
                                "for_destination",
                                "FOR destination: the seller delivers, freight paid",
                            ),
                            (
                                "to_pay",
                                "To pay: the seller sends, the buyer pays the transporter",
                            ),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "incoterm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXW", "EXW: ex works"),
                            ("FCA", "FCA: free carrier"),
                            ("FOB", "FOB: free on board"),
                            ("CFR", "CFR: cost and freight"),
                            ("CIF", "CIF: cost, insurance and freight"),
                            ("DAP", "DAP: delivered at place"),
                            ("DDP", "DDP: delivered duty paid"),
                        ],
                        help_text="For an import.",
                        max_length=3,
                    ),
                ),
                (
                    "port_of_loading",
                    models.CharField(
                        blank=True, help_text="For an import: Shanghai.", max_length=64
                    ),
                ),
                (
                    "our_account_number",
                    models.CharField(
                        blank=True,
                        help_text="What they call us: printed on our orders to them.",
                        max_length=64,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor_profile",
                        to="core.party",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [
                    (
                        "set_vendor_standing",
                        "Can approve, put on trial or block a vendor",
                    ),
                    ("hold_vendor_payments", "Can hold or release a vendor's payments"),
                ],
            },
        ),
    ]
