# Generated by Django 5.2.17 on 2026-10-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0022_statement_line_returns_a_payment"),
        ("purchasing", "0054_debit_note_undoes_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceipt",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="What receiving it posted: stock in, or out on a return; cost of sales on a drop-ship.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="price_difference_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="On a return at a price other than the shelf's: the difference, to price variance.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
    ]
