# Generated by Django 5.2.17 on 2026-10-07 21:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0022_statement_line_returns_a_payment"),
        ("purchasing", "0055_receipt_keeps_its_entries"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="settlement_discount_withdrawal_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="settlement_discount_withdrawn",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                editable=False,
                help_text="Of the discount for paying early, what was taken back when the payment that earned it was returned.",
                max_digits=18,
            ),
        ),
    ]
