# Generated by Django 5.2.17 on 2026-10-08 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0037_refold_below_zero_fifo_and_specific"),
        ("purchasing", "0058_challans_paid_from_hold_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="landedcostapplication",
            name="movements",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                help_text="What each shelf took: one value-only movement per shelf the goods were on. What the shelves did not take went to cost of sales.",
                related_name="+",
                to="inventory.stockmovement",
            ),
        ),
        migrations.AddField(
            model_name="receiptinspection",
            name="movement",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The movement that put accepted goods on that shelf: under FIFO their layer, which a cost landed on them later raises. Blank on clearances made before it was kept.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.stockmovement",
            ),
        ),
        migrations.AlterField(
            model_name="landedcostapplication",
            name="stock_movement",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The one shelf an allocation made before `movements` were kept landed on.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.stockmovement",
            ),
        ),
    ]
