# Generated by Django 5.2.17 on 2026-10-10 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0023_account_holds_money"),
        ("core", "0030_saved_filters"),
        ("purchasing", "0061_bill_keeps_its_msme_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="supplier_note_date",
            field=models.DateField(
                blank=True,
                help_text="On a debit note: the date of the supplier's credit note.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bill",
            name="supplier_note_number",
            field=models.CharField(
                blank=True,
                help_text="On a debit note: the number of the credit note the supplier issued for it, which its GSTR-1 and so the company's GSTR-2B carry. Given when the note is made, or while it is a draft.",
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("debits__isnull", False),
                    models.Q(("supplier_note_number", ""), _negated=True),
                ),
                fields=("vendor", "supplier_note_number"),
                name="one_debit_note_per_supplier_credit_note",
            ),
        ),
    ]
