# Generated by Django 5.2.17 on 2026-10-10 20:03

from django.conf import settings
from django.db import migrations, models


def key_the_notes_recorded(apps, schema_editor):
    """Each debit note's supplier credit note, keyed as GSTR-2B pairs it within its year (O159)."""
    from apps.purchasing.models import supplier_note_key

    Bill = apps.get_model("purchasing", "Bill")
    for bill in Bill.objects.exclude(supplier_note_number="").only("supplier_note_number", "supplier_note_date",
                                                                   "bill_date"):
        Bill.objects.filter(pk=bill.pk).update(supplier_note_key=supplier_note_key(
            bill.supplier_note_number, bill.supplier_note_date or bill.bill_date))


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0024_statement_line_matches_a_booked_entry"),
        ("core", "0030_saved_filters"),
        ("purchasing", "0062_debit_note_keeps_the_suppliers_credit_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bill",
            name="one_debit_note_per_supplier_credit_note",
        ),
        migrations.AddField(
            model_name="bill",
            name="supplier_note_key",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The supplier's credit-note number as GSTR-2B pairs it, within the supplier's financial year: what makes it one note.",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="bill",
            name="supplier_note_number",
            field=models.CharField(
                blank=True,
                help_text="On a debit note: the number of the credit note the supplier issued for it, which its GSTR-1 and so the company's GSTR-2B carry. Given when the note is made, or recorded on it when it arrives (record_supplier_note).",
                max_length=64,
            ),
        ),
        migrations.RunPython(key_the_notes_recorded, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="bill",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("debits__isnull", False),
                    models.Q(("supplier_note_key", ""), _negated=True),
                ),
                fields=("vendor", "supplier_note_key"),
                name="one_debit_note_per_supplier_credit_note",
            ),
        ),
    ]
