# Generated by Django 5.2.17 on 2026-10-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0063_a_supplier_credit_note_is_one_in_its_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceipt",
            name="objected_on",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="The day the company objected to these goods in writing (MSMED Act s.2(b)).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="objection",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="What the written objection said, or its reference.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="objection_removed_on",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="The day the supplier removed the objection.",
                null=True,
            ),
        ),
    ]
