# Generated by Django 5.2.17 on 2026-10-10 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0064_an_objection_in_writing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goodsreceipt",
            options={
                "ordering": ["-receipt_date", "-id"],
                "permissions": [
                    ("post_goodsreceipt", "Can post goods receipts and returns"),
                    (
                        "object_goodsreceipt",
                        "Can record an objection to goods received and its removal",
                    ),
                ],
            },
        ),
    ]
