# Generated by Django 5.2.17 on 2026-09-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-invoice_date", "-id"],
                "permissions": [
                    ("post_invoice", "Can post invoices and issue credit notes")
                ],
            },
        ),
    ]
