# Generated by Django 5.2.17 on 2026-09-19 15:15

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_fiscalposition_partytaxprofile_taxgroup_tax_and_more"),
        ("core", "0003_country_partytag_address_company_documentsequence_and_more"),
        ("sales", "0002_alter_invoice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.address",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.currency",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                editable=False,
                help_text="Rate to the base currency captured at posting time.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="number",
            field=models.CharField(
                blank=True, editable=False, max_length=32, unique=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.paymentterms",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.address",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Line discount, e.g. 10.00 for 10% off.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="taxes",
            field=models.ManyToManyField(
                blank=True, related_name="invoice_lines", to="accounting.tax"
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.address",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="number",
            field=models.CharField(
                blank=True, editable=False, max_length=32, unique=True
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="payment_terms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.paymentterms",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.address",
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="discount_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Line discount, e.g. 10.00 for 10% off.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="revenue_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="taxes",
            field=models.ManyToManyField(
                blank=True, related_name="sales_order_lines", to="accounting.tax"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="reference",
            field=models.CharField(
                blank=True,
                help_text="The customer's own PO number, if any.",
                max_length=64,
            ),
        ),
    ]
