# Generated by Django 5.2.17 on 2026-09-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_alter_delivery_number_alter_invoice_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this line bills a sales order line, so the order can't be billed twice.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_lines",
                to="sales.salesorderline",
            ),
        ),
    ]
