# Generated by Django 5.2.17 on 2026-09-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_invoiceline_order_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryline",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                editable=False,
                help_text="Weighted average cost at the moment of shipping, frozen so a return reverses exactly.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
