# Generated by Django 5.2.17 on 2026-09-19 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_deliveryline_unit_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="credits_line",
            field=models.ForeignKey(
                blank=True,
                help_text="On a credit note line, the invoice line being credited.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="credit_lines",
                to="sales.invoiceline",
            ),
        ),
    ]
