# Generated by Django 5.2.17 on 2026-09-19 15:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("core", "0004_company_default_cogs_account_and_more"),
        ("inventory", "0005_item_sale_price"),
        ("sales", "0009_invoiceline_credits_line"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum this customer may owe. Blank means no limit.",
                        max_digits=18,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Used for any customer without a list of their own.",
                    ),
                ),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PriceListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "min_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1"),
                        help_text="Volume break: this price applies from this quantity upwards.",
                        max_digits=18,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=18)),
            ],
            options={
                "ordering": ["price_list", "item", "-min_quantity"],
            },
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Left blank, it is resolved from the price list or the item's list price.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Left blank, it is resolved from the price list or the item's list price.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="order_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="order_line_price_not_negative",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="party",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_profile",
                to="core.party",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="price_lists",
                to="core.currency",
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="price_list",
            field=models.ForeignKey(
                blank=True,
                help_text="Overrides the default price list for this customer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customers",
                to="sales.pricelist",
            ),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_entries",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="price_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="sales.pricelist",
            ),
        ),
        migrations.AddField(
            model_name="pricelistitem",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.UniqueConstraint(
                fields=("price_list", "item", "min_quantity"), name="unique_price_break"
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_quantity__gt", 0)),
                name="price_break_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelistitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)), name="price_not_negative"
            ),
        ),
    ]
