# Generated by Django 5.2.17 on 2026-09-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_customerprofile_pricelist_pricelistitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="sent_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When this was last emailed to the customer.",
                null=True,
            ),
        ),
    ]
