# Generated by Django 5.2.17 on 2026-09-19 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_invoice_sent_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DunningLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=64, unique=True)),
                (
                    "days_overdue",
                    models.PositiveIntegerField(
                        help_text="Send once the invoice is at least this many days past due."
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        default="Reminder: invoice {number} is overdue",
                        help_text="Supports {number}, {customer}, {days}, {amount}.",
                        max_length=200,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        default="Dear {customer},\n\nInvoice {number} for {amount} was due on {due_date} and is now {days} days overdue.\n\nPlease arrange payment.\n",
                        help_text="Supports {number}, {customer}, {days}, {amount}, {due_date}.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["days_overdue"],
            },
        ),
        migrations.CreateModel(
            name="DunningNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("days_overdue", models.PositiveIntegerField()),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=18)),
                ("sent_to", models.EmailField(blank=True, max_length=254)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dunning_notices",
                        to="sales.invoice",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notices",
                        to="sales.dunninglevel",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="dunninglevel",
            constraint=models.UniqueConstraint(
                fields=("days_overdue",), name="unique_dunning_threshold"
            ),
        ),
        migrations.AddConstraint(
            model_name="dunningnotice",
            constraint=models.UniqueConstraint(
                fields=("invoice", "level"), name="one_notice_per_invoice_and_level"
            ),
        ),
    ]
