# Generated by Django 5.2.17 on 2026-09-19 18:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("core", "0004_company_default_cogs_account_and_more"),
        ("inventory", "0005_item_sale_price"),
        ("sales", "0013_quotation_quotationline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="backorder_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this delivery carries what an earlier shipment left behind.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="backorders",
                to="sales.delivery",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="sales_rep",
            field=models.ForeignKey(
                blank=True,
                help_text="The employee credited with this sale.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_sales",
                to="core.party",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="revision",
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="quotation",
            name="revision_of",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The quotation this one revises.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revisions",
                to="sales.quotation",
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="sales_rep",
            field=models.ForeignKey(
                blank=True,
                help_text="The employee credited with this sale.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_sales",
                to="core.party",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="sales_rep",
            field=models.ForeignKey(
                blank=True,
                help_text="The employee credited with this sale.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_sales",
                to="core.party",
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("expired", "Expired"),
                    ("superseded", "Superseded by a revision"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="CommissionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission rate, e.g. 2.50 for 2.5%.",
                        max_digits=5,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("invoiced", "What was invoiced"),
                            ("paid", "What was collected"),
                        ],
                        default="invoiced",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RecurringInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=16,
                    ),
                ),
                (
                    "interval_count",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Every N intervals, e.g. 2 monthly = every other month.",
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Blank runs indefinitely.", null=True
                    ),
                ),
                ("next_run_date", models.DateField(blank=True, null=True)),
                (
                    "auto_post",
                    models.BooleanField(
                        default=False,
                        help_text="Post generated invoices immediately instead of leaving drafts.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.currency",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_invoices",
                        to="core.party",
                    ),
                ),
                (
                    "payment_terms",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.paymentterms",
                    ),
                ),
                (
                    "receivable_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "sales_rep",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_sales",
                        to="core.party",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RecurringInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Left blank, it is resolved from the price list or the item's list price.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Line discount, e.g. 10.00 for 10% off.",
                        max_digits=5,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.recurringinvoice",
                    ),
                ),
                (
                    "taxes",
                    models.ManyToManyField(
                        blank=True, related_name="recurring_lines", to="accounting.tax"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesRep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_rep_profile",
                        to="core.party",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reps",
                        to="sales.commissionplan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="commissionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("percent__gte", 0)),
                name="commission_percent_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval_count__gt", 0)),
                name="interval_count_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="recurringinvoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="recurring_quantity_positive",
            ),
        ),
    ]
