# Generated by Django 5.2.17 on 2026-09-19 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("sales", "0014_delivery_backorder_of_invoice_sales_rep_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="settlement_discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Early-settlement discount written off against this invoice.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="settlement_discount_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="invoice_policy",
            field=models.CharField(
                choices=[
                    ("ordered", "Bill what was ordered"),
                    ("delivered", "Bill what was delivered"),
                ],
                default="ordered",
                help_text="Bill the whole order up front, or only what has shipped.",
                max_length=16,
            ),
        ),
    ]
