# Generated by Django 5.2.17 on 2026-09-19 19:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("sales", "0015_invoice_settlement_discount_amount_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="written_off_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                editable=False,
                help_text="Receivable judged uncollectable and charged to bad debt.",
                max_digits=18,
            ),
        ),
        migrations.CreateModel(
            name="InvoiceWriteOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="write_offs",
                        to="sales.invoice",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "recovered_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Set when the debt was recovered and this write-off reversed.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="write_off_amount_positive",
                    )
                ],
            },
        ),
    ]
