# Generated by Django 5.2.17 on 2026-09-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0016_invoice_written_off_amount_invoicewriteoff"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-invoice_date", "-id"],
                "permissions": [
                    ("post_invoice", "Can post invoices and issue credit notes"),
                    ("write_off_invoice", "Can write a receivable off to bad debt"),
                ],
            },
        ),
    ]
