# Generated by Django 5.2.17 on 2026-09-19 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("core", "0007_company_customer_deposit_account"),
        ("inventory", "0005_item_sale_price"),
        ("sales", "0018_invoice_is_down_payment_depositapplication"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quotationline",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="quotationline",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotation_lines",
                to="inventory.item",
            ),
        ),
        migrations.AlterField(
            model_name="quotationline",
            name="uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.unitofmeasure",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_order_lines",
                to="inventory.item",
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="uom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.unitofmeasure",
            ),
        ),
        migrations.CreateModel(
            name="ChargeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revenue_account",
                    models.ForeignKey(
                        help_text="Keep this separate from product revenue: recharged freight with no cost behind it otherwise flatters gross margin.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "taxes",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Applied by default when this charge is added to a document.",
                        related_name="charge_types",
                        to="accounting.tax",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                help_text="Set instead of an item when this line bills freight, handling or similar.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="sales.chargetype",
            ),
        ),
        migrations.AddField(
            model_name="quotationline",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                help_text="Set instead of an item when this line bills freight, handling or similar.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="sales.chargetype",
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                help_text="Set instead of an item when this line bills freight, handling or similar.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="sales.chargetype",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("charge__isnull", True), ("item__isnull", False)),
                    models.Q(("charge__isnull", False), ("item__isnull", True)),
                    _connector="OR",
                ),
                name="quote_line_is_item_or_charge",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("charge__isnull", True), ("item__isnull", False)),
                    models.Q(("charge__isnull", False), ("item__isnull", True)),
                    _connector="OR",
                ),
                name="order_line_is_item_or_charge",
            ),
        ),
    ]
