# Generated by Django 5.2.17 on 2026-09-19 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0019_quotationline_description_salesorderline_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salesorder",
            options={
                "ordering": ["-order_date", "-id"],
                "permissions": [
                    (
                        "approve_order",
                        "Can approve orders that breach the discount policy",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="salesorder",
            name="approval_note",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="approved_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "max_discount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Any line discounted above this needs approval.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "min_margin_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Gross margin over the order, against weighted average cost. Catches the discount that a percentage limit misses: a cheap item sold at a small discount can still be sold at a loss.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "max_order_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Orders above this value need approval regardless of margin.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "approval policies",
                "ordering": ["code"],
            },
        ),
    ]
