# Generated by Django 5.2.17 on 2026-09-20 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_chargetype"),
        ("sales", "0020_alter_salesorder_options_salesorder_approval_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesorderline",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                help_text="Set instead of an item when this line bills freight, handling or similar.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="accounting.chargetype",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                help_text="Set instead of an item when this line bills freight, handling or similar.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="accounting.chargetype",
            ),
        ),
        migrations.AlterField(
            model_name="quotationline",
            name="charge",
            field=models.ForeignKey(
                blank=True,
                help_text="Set instead of an item when this line bills freight, handling or similar.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)ss",
                to="accounting.chargetype",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceline",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="On a sales document, left blank it resolves from the price list or the item's list price.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quotationline",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="On a sales document, left blank it resolves from the price list or the item's list price.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="recurringinvoiceline",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="On a sales document, left blank it resolves from the price list or the item's list price.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="salesorderline",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="On a sales document, left blank it resolves from the price list or the item's list price.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="ChargeType",
        ),
    ]
