# Generated by Django 5.2.17 on 2026-09-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0022_invoicepayment_fx_entry"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="is_drop_ship",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Shipped by the vendor straight to the customer. Records what the customer received without moving stock the company never held.",
            ),
        ),
    ]
