# Generated by Django 5.2.17 on 2026-09-20 04:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0009_bankstatement_bankstatementline"),
        ("inventory", "0006_stockmovement_value_adjustment"),
        ("sales", "0023_delivery_is_drop_ship"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="invoice_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoiceline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="invoice_line_price_not_negative",
            ),
        ),
    ]
