# Generated by Django 5.2.17 on 2026-09-20 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_stockreservation"),
        ("sales", "0024_invoiceline_invoice_line_quantity_positive_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderline",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Where this line is expected to ship from. Naming it lets confirming the order hold the stock; without it the order is a promise against no particular shelf.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.warehouse",
            ),
        ),
    ]
