# Generated by Django 5.2.17 on 2026-09-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_remove_stockcountline_one_count_line_per_item_and_more"),
        ("sales", "0025_salesorderline_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryline",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Which batch is being shipped. Required when the item is tracked: a recall that cannot say which customer got which batch is not a recall.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.lot",
            ),
        ),
    ]
