# Generated by Django 5.2.17 on 2026-09-21 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0028_alter_deliveryline_lot_deliveryallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryline",
            name="reverses_line",
            field=models.ForeignKey(
                blank=True,
                help_text="On a return line, the delivery line being sent back. The goods go home to the batches and shelves they left from, which only that line knows.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="return_lines",
                to="sales.deliveryline",
            ),
        ),
    ]
