# Generated by Django 5.2.17 on 2026-09-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0029_deliveryline_reverses_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderline",
            name="delivery_date",
            field=models.DateField(
                blank=True,
                help_text="When this line was promised. Left empty it falls back to the order date, which reads as 'wanted now'.",
                null=True,
            ),
        ),
    ]
