# Generated by Django 5.2.17 on 2026-09-28 03:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("sales", "0032_return_allocations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="max_filler_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The most filler (calcium carbonate) the tape may carry.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="min_uv_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The least UV stabiliser the tape must carry.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="virgin_only",
            field=models.BooleanField(
                default=False,
                help_text="Nothing recovered from waste — regrind of any kind — anywhere in what they are sold, checked on the recipe and on the lots shipped.",
            ),
        ),
        migrations.AddConstraint(
            model_name="customerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("max_filler_percent__isnull", True),
                        models.Q(
                            ("max_filler_percent__gte", 0),
                            ("max_filler_percent__lte", 100),
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        ("min_uv_percent__isnull", True),
                        models.Q(
                            ("min_uv_percent__gte", 0), ("min_uv_percent__lte", 100)
                        ),
                        _connector="OR",
                    ),
                ),
                name="customer_material_rules_are_percentages",
            ),
        ),
    ]
