# Generated by Django 5.2.17 on 2026-09-28 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("inventory", "0030_refold_company_wide_valuation"),
        ("sales", "0034_salesorder_is_job_work_supplieditem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="release_covers_returns",
            field=models.BooleanField(
                default=False,
                help_text="Goods they send back go back under their inspector's release. Off, returned sacks must be inspected again before they go out again.",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="third_party_inspection",
            field=models.BooleanField(
                default=False,
                help_text="Their own inspector passes each batch before it may be loaded. What a new order takes; an order may say otherwise.",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="returned_under_release",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="On a customer return: whether the goods came back under the customer's inspector's release, as their profile said when it was posted. Recorded, so changing the profile later does not rewrite it.",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="third_party_inspection",
            field=models.BooleanField(
                blank=True,
                help_text="Whether the customer's inspector must release the goods first. Blank takes the customer's setting when the order is written; fixed once anything has shipped on it.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ThirdPartyRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, editable=False, max_length=32)),
                ("inspector", models.CharField(blank=True, max_length=128)),
                (
                    "their_reference",
                    models.CharField(
                        help_text="The agency's inspection certificate number.",
                        max_length=64,
                    ),
                ),
                ("inspected_on", models.DateField()),
                ("posted", models.BooleanField(default=False, editable=False)),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "agency",
                    models.ForeignKey(
                        help_text="Who inspected.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.party",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.party",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="The order the agency signed against, when it did. Left blank, the release serves any of the customer's inspected orders.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="third_party_releases",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-inspected_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ThirdPartyReleaseLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_offered",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="What was put before the inspector, in the item's stocking unit.",
                        max_digits=18,
                    ),
                ),
                (
                    "quantity_released",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="What they passed. Nothing passed is a rejection, and is recorded as one rather than left out.",
                        max_digits=18,
                    ),
                ),
                ("remarks", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.lot",
                    ),
                ),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.thirdpartyrelease",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="thirdpartyrelease",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="third_party_release_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="thirdpartyrelease",
            constraint=models.UniqueConstraint(
                condition=models.Q(("posted", True), ("voided_at__isnull", True)),
                fields=("agency", "their_reference"),
                name="one_release_per_agency_certificate",
            ),
        ),
        migrations.AddConstraint(
            model_name="thirdpartyreleaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_offered__gt", 0),
                    ("quantity_released__gte", 0),
                    ("quantity_released__lte", models.F("quantity_offered")),
                ),
                name="third_party_release_quantities_in_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="thirdpartyreleaseline",
            constraint=models.UniqueConstraint(
                fields=("release", "lot"), name="one_line_per_batch_per_release"
            ),
        ),
    ]
