# Generated by Django 5.2.17 on 2026-09-29 03:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0035_customerprofile_release_covers_returns_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="PriceVariationBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, editable=False, max_length=32)),
                ("start", models.DateField()),
                ("end", models.DateField()),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "credit_note",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sales.invoice",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sales.invoice",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_variation_bills",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-end", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PriceVariationClause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "base_value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="The index value the order's price stood on.",
                        max_digits=12,
                    ),
                ),
                (
                    "polymer_kg_per_unit",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Polymer in one unit of the line — kilogrammes a sack.",
                        max_digits=12,
                    ),
                ),
                (
                    "pass_through_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100"), max_digits=6
                    ),
                ),
                (
                    "threshold_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="A move of the index within this share of the base changes nothing.",
                        max_digits=6,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clauses",
                        to="sales.priceindex",
                    ),
                ),
                (
                    "order_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="price_clause",
                        to="sales.salesorderline",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceVariationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Negative for a return.",
                        max_digits=18,
                    ),
                ),
                ("index_value", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "variation_per_unit",
                    models.DecimalField(decimal_places=6, max_digits=14),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.pricevariationbill",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sales.delivery",
                    ),
                ),
                (
                    "delivery_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sales.deliveryline",
                    ),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sales.priceindex",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="sales.salesorderline",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["bill", "id"],
            },
        ),
        migrations.CreateModel(
            name="PriceIndexValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateField()),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Per kilogramme of polymer.",
                        max_digits=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "index",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="sales.priceindex",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["index", "-valid_from"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("index", "valid_from"), name="one_index_value_a_day"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("value__gt", 0)),
                        name="index_value_positive",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pricevariationbill",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="price_variation_bill_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricevariationclause",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("base_value__gt", 0),
                    ("polymer_kg_per_unit__gt", 0),
                    ("pass_through_percent__gt", 0),
                    ("pass_through_percent__lte", 100),
                    ("threshold_percent__gte", 0),
                ),
                name="price_clause_figures_sensible",
            ),
        ),
        migrations.AddConstraint(
            model_name="pricevariationline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("quantity", 0), _negated=True),
                    models.Q(
                        ("amount", 0),
                        models.Q(
                            ("quantity__gt", 0),
                            ("variation_per_unit__gt", 0),
                            ("amount__gt", 0),
                        ),
                        models.Q(
                            ("quantity__gt", 0),
                            ("variation_per_unit__lt", 0),
                            ("amount__lt", 0),
                        ),
                        models.Q(
                            ("quantity__lt", 0),
                            ("variation_per_unit__gt", 0),
                            ("amount__lt", 0),
                        ),
                        models.Q(
                            ("quantity__lt", 0),
                            ("variation_per_unit__lt", 0),
                            ("amount__gt", 0),
                        ),
                        _connector="OR",
                    ),
                ),
                name="price_variation_amount_signed_as_quantity_times_rate",
            ),
        ),
    ]
