# Generated by Django 5.2.17 on 2026-09-29 05:59

from decimal import Decimal
from django.conf import settings
from decimal import Decimal

from django.db import migrations, models


def exact_for_lines_already_taken(apps, schema_editor):
    """Lines taken before tolerances existed were taken exact."""
    Line = apps.get_model("sales", "SalesOrderLine")
    Line.objects.filter(item__isnull=False, over_delivery_percent__isnull=True).update(
        over_delivery_percent=Decimal("0"))
    Line.objects.filter(item__isnull=False, under_delivery_percent__isnull=True).update(
        under_delivery_percent=Decimal("0"))


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_gstsettings_job_work_sac"),
        ("core", "0016_company_net_pay_account"),
        ("inventory", "0031_adjustment_raised_by"),
        ("sales", "0036_price_variation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="over_delivery_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="How far over the ordered quantity they accept, and are billed for. What a new order line takes; the line may say otherwise.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="under_delivery_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="How far short of the ordered quantity still counts as the order met: nothing more is planned or promised against it.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="closed_short_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="closed_short_reason",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="over_delivery_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="How far over the quantity may ship and be billed. Blank takes the customer's, and is written down then: a term of this order.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="under_delivery_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="How far short the line still counts as met. Blank takes the customer's, written down then.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorderline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("over_delivery_percent__isnull", True),
                        models.Q(
                            ("over_delivery_percent__gte", 0),
                            ("over_delivery_percent__lte", 100),
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        ("under_delivery_percent__isnull", True),
                        models.Q(
                            ("under_delivery_percent__gte", 0),
                            ("under_delivery_percent__lt", 100),
                        ),
                        _connector="OR",
                    ),
                ),
                name="order_line_tolerances_sensible",
            ),
        ),
        migrations.RunPython(exact_for_lines_already_taken, migrations.RunPython.noop),
    ]
