# Generated by Django 5.2.17 on 2026-10-03 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0038_call_offs"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorderline",
            name="quotation_line",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The quotation line this was accepted from: where its quoted cost is.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_lines",
                to="sales.quotationline",
            ),
        ),
    ]
