# Generated by Django 5.2.17 on 2026-10-04 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_gstsettings_job_work_sac"),
        ("sales", "0039_salesorderline_quotation_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="depositapplication",
            name="fx_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Realised exchange difference posted when the deposit, taken at one rate, was drawn down against an invoice billed at another.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
    ]
