# Generated by Django 5.2.17 on 2026-10-04 18:59

from django.conf import settings
from django.db import migrations, models

from apps.core.trigram import trigram_indexes


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0016_list_indexes"),
        ("core", "0018_login_failures"),
        ("sales", "0042_posted_net"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["delivery_date", "id"], name="delivery_by_date"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["invoice_date", "id"], name="invoice_by_date"),
        ),
        migrations.AddIndex(
            model_name="quotation",
            index=models.Index(
                fields=["quotation_date", "id"], name="quotation_by_date"
            ),
        ),
        migrations.AddIndex(
            model_name="salesorder",
            index=models.Index(fields=["order_date", "id"], name="sales_order_by_date"),
        ),
        # ?search= on the lists (apps/core/trigram.py).
        trigram_indexes(
            ("sales_invoice", "number"),
            ("sales_invoice", "reference"),
            ("sales_salesorder", "number"),
            ("sales_salesorder", "reference"),
            ("sales_delivery", "number"),
            ("sales_delivery", "reference"),
            ("sales_quotation", "number"),
            ("sales_quotation", "reference"),
        ),
    ]
