# Generated by Django 5.2.17 on 2026-10-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0044_deposit_tax_reversal"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="is_opening_balance",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Brought in at go-live (import_csv open_invoices): what the old system's invoice still had owing. A supply that system already reported, so no GST return or e-invoice here counts it.",
            ),
        ),
    ]
