# Generated by Django 5.2.17 on 2026-10-05 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def keep_everyone_seeing_every_customer(apps, schema_editor):
    """
    Nobody was limited before this: everyone who could read parties saw
    every customer. Given only by setup_roles, the permission would leave
    an installation upgraded without running it limited to nobody's
    customers. So every group and person that reads parties gets it now,
    but a Sales Rep group, which is what the limit is for.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")
    User = apps.get_model(settings.AUTH_USER_MODEL)
    profile_type, _ = ContentType.objects.get_or_create(app_label="sales", model="customerprofile")
    party_type, _ = ContentType.objects.get_or_create(app_label="core", model="party")
    every, _ = Permission.objects.get_or_create(
        content_type=profile_type, codename="view_every_customer",
        defaults={"name": "Can see every customer, not only one's own as a rep"})
    reads = Permission.objects.filter(content_type=party_type, codename="view_party").first()
    if reads is None:
        return
    for group in Group.objects.filter(permissions=reads).exclude(name="Sales Rep"):
        group.permissions.add(every)
    for user in User.objects.filter(user_permissions=reads):
        user.user_permissions.add(every)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0020_login_failure_address"),
        ("sales", "0045_opening_balance_flag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customerprofile",
            options={
                "permissions": [
                    (
                        "view_every_customer",
                        "Can see every customer, not only one's own as a rep",
                    )
                ]
            },
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="sales_rep",
            field=models.ForeignKey(
                blank=True,
                help_text="The rep whose customer this is. A rep sees their own customers and nobody else's; a new order takes them as its rep.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customers_carried",
                to="core.party",
            ),
        ),
        migrations.RunPython(keep_everyone_seeing_every_customer, migrations.RunPython.noop),
    ]
