# Generated by Django 5.2.17 on 2026-10-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0046_customer_sales_rep"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="corrects_old_supply",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="A credit note with its own GST on an invoice the old system issued: reported in this system's returns against the old number.",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="old_invoice_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="On such a note, what the old invoice was for in all: no more is credited against it, and for an unregistered buyer it decides whether the note is reported as a large one (CDNUR).",
                max_digits=18,
                null=True,
            ),
        ),
    ]
