# Generated by Django 5.2.17 on 2026-10-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0049_invoicelinetax_reverse_charge"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="claim_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("torn", "Torn or damaged bags"),
                    ("short_weight", "Short weight or count"),
                    ("rate", "Rate disputed"),
                    ("quality", "Quality below specification"),
                    ("other", "Other"),
                ],
                editable=False,
                help_text="On a credit note given for a customer's claim: what the money was given back for.",
                max_length=16,
            ),
        ),
    ]
