# Generated by Django 5.2.17 on 2026-10-06 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_login_failure_address"),
        ("sales", "0050_invoice_claim_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="lr_date",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="delivery",
            name="lr_number",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The transporter's lorry receipt.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="transporter",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="carried_deliveries",
                to="core.party",
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="vehicle_number",
            field=models.CharField(blank=True, editable=False, max_length=15),
        ),
    ]
