# Generated by Django 5.2.17 on 2026-10-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0051_delivery_transport"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="receipt_reference",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The customer's goods-received note or the signed copy's number.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="delivery",
            name="received_by",
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name="delivery",
            name="received_on",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
