# Generated by Django 5.2.17 on 2026-10-06 22:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_licences"),
        ("sales", "0052_delivery_receipt"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("exhibition", "Exhibition"),
                            ("print", "Print"),
                            ("digital", "Digital"),
                            ("field", "Field visits"),
                            ("referral", "Referral drive"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField(blank=True, null=True)),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="What it was allowed to cost.",
                        max_digits=18,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-starts_on", "code"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, editable=False, max_length=32)),
                ("company_name", models.CharField(max_length=255)),
                ("contact_name", models.CharField(blank=True, max_length=128)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.CharField(blank=True, max_length=254)),
                ("city", models.CharField(blank=True, max_length=64)),
                ("state", models.CharField(blank=True, max_length=64)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("referral", "Referral"),
                            ("walk_in", "Walked in"),
                            ("phone", "Phone or WhatsApp"),
                            ("web", "Website"),
                            ("exhibition", "Exhibition"),
                            ("campaign", "Campaign"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "interest",
                    models.CharField(
                        blank=True,
                        help_text="What they asked for: 50 kg cement sacks, twenty thousand a month.",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("working", "Being worked"),
                            ("converted", "Converted"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "converted_on",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "lost_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads",
                        to="sales.campaign",
                    ),
                ),
                (
                    "converted_party",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.party",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The rep who carries it. Empty, any rep may take it.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leads_owned",
                        to="core.party",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, editable=False, max_length=32)),
                (
                    "title",
                    models.CharField(
                        help_text="The business, in a line: 20,000 cement sacks a month.",
                        max_length=128,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("qualified", "Qualified"),
                            ("quoted", "Quoted"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="What the order would be worth, before tax.",
                        max_digits=18,
                    ),
                ),
                (
                    "expected_on",
                    models.DateField(
                        blank=True, help_text="When the order is expected.", null=True
                    ),
                ),
                (
                    "probability",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Chance in percent; empty takes the stage's own.",
                        null=True,
                    ),
                ),
                (
                    "lost_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                ("closed_on", models.DateField(blank=True, editable=False, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="sales.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="core.party",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="sales.lead",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The rep who carries it.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities_owned",
                        to="core.party",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="sales.quotation",
                    ),
                ),
                (
                    "sales_order",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opportunities",
                        to="sales.salesorder",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "opportunities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("call", "Call"),
                            ("visit", "Visit"),
                            ("email", "Email or message"),
                            ("note", "Note"),
                            ("follow_up", "Follow-up"),
                        ],
                        default="call",
                        max_length=16,
                    ),
                ),
                ("summary", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "due_on",
                    models.DateField(
                        blank=True,
                        help_text="For a follow-up: the day it is due; the morning checks watch it.",
                        null=True,
                    ),
                ),
                ("done_on", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="The rep who did it, or will.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="activities_owned",
                        to="core.party",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        blank=True,
                        help_text="A customer, where it is about neither a lead nor an opportunity.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.party",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="sales.lead",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="sales.opportunity",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(("budget__gte", 0)),
                name="campaign_budget_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaign",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ends_on__isnull", True),
                    ("ends_on__gte", models.F("starts_on")),
                    _connector="OR",
                ),
                name="campaign_ends_after_it_starts",
            ),
        ),
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="unique_lead_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="unique_opportunity_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0)),
                name="opportunity_value_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="opportunity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("probability__isnull", True),
                    ("probability__lte", 100),
                    _connector="OR",
                ),
                name="opportunity_chance_is_a_percent",
            ),
        ),
        migrations.AddConstraint(
            model_name="activity",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("lead__isnull", False),
                        ("opportunity__isnull", True),
                        ("party__isnull", True),
                    ),
                    models.Q(
                        ("lead__isnull", True),
                        ("opportunity__isnull", False),
                        ("party__isnull", True),
                    ),
                    models.Q(
                        ("lead__isnull", True),
                        ("opportunity__isnull", True),
                        ("party__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="activity_about_one_thing",
            ),
        ),
    ]
