# Generated by Django 5.2.17 on 2026-10-07 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_party_identity"),
        ("sales", "0055_teams_and_targets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="credit_hold",
            field=models.BooleanField(
                default=False,
                help_text="No order is confirmed and nothing is dispatched to them until it is lifted.",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="credit_hold_reason",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="freight_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ex_works", "Ex works: they collect"),
                    (
                        "for_destination",
                        "FOR destination: we deliver, the freight is ours",
                    ),
                    ("to_pay", "To pay: we send, they pay the transporter"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="incoterm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXW", "EXW: ex works"),
                    ("FCA", "FCA: free carrier"),
                    ("FOB", "FOB: free on board"),
                    ("CFR", "CFR: cost and freight"),
                    ("CIF", "CIF: cost, insurance and freight"),
                    ("DAP", "DAP: delivered at place"),
                    ("DDP", "DDP: delivered duty paid"),
                ],
                help_text="For an export customer.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cement", "Cement"),
                    ("fertiliser", "Fertiliser"),
                    ("food_grain", "Food grain and pulses"),
                    ("sugar", "Sugar"),
                    ("salt", "Salt"),
                    ("feed", "Animal feed"),
                    ("chemicals", "Chemicals and polymers"),
                    ("other", "Other"),
                ],
                help_text="What they fill the sacks with; the sales report groups by it.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="marking",
            field=models.TextField(
                blank=True,
                help_text="Marking and printing instructions: batch, date, brand.",
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="port_of_discharge",
            field=models.CharField(
                blank=True,
                help_text="For an export customer: Jebel Ali.",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="sacks_per_bale",
            field=models.PositiveIntegerField(
                blank=True, help_text="Bales of 500, say.", null=True
            ),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="transporter",
            field=models.ForeignKey(
                blank=True,
                help_text="Who usually carries their goods; a new delivery takes them.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.party",
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="freight_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ex_works", "Ex works: they collect"),
                    (
                        "for_destination",
                        "FOR destination: we deliver, the freight is ours",
                    ),
                    ("to_pay", "To pay: we send, they pay the transporter"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="incoterm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXW", "EXW: ex works"),
                    ("FCA", "FCA: free carrier"),
                    ("FOB", "FOB: free on board"),
                    ("CFR", "CFR: cost and freight"),
                    ("CIF", "CIF: cost, insurance and freight"),
                    ("DAP", "DAP: delivered at place"),
                    ("DDP", "DDP: delivered duty paid"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="marking",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="port_of_discharge",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="sacks_per_bale",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="customerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sacks_per_bale__isnull", True),
                    ("sacks_per_bale__gt", 0),
                    _connector="OR",
                ),
                name="customer_bales_hold_some_sacks",
            ),
        ),
        migrations.AddConstraint(
            model_name="salesorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sacks_per_bale__isnull", True),
                    ("sacks_per_bale__gt", 0),
                    _connector="OR",
                ),
                name="sales_order_bales_hold_some_sacks",
            ),
        ),
    ]
