# Generated by Django 5.2.17 on 2026-10-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0056_customer_trade_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="freight_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ex_works", "Ex works: the buyer collects"),
                    (
                        "for_destination",
                        "FOR destination: the seller delivers, freight paid",
                    ),
                    (
                        "to_pay",
                        "To pay: the seller sends, the buyer pays the transporter",
                    ),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="freight_terms",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ex_works", "Ex works: the buyer collects"),
                    (
                        "for_destination",
                        "FOR destination: the seller delivers, freight paid",
                    ),
                    (
                        "to_pay",
                        "To pay: the seller sends, the buyer pays the transporter",
                    ),
                ],
                max_length=16,
            ),
        ),
    ]
