# Generated by Django 5.2.17 on 2026-10-07 19:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0021_budgets_recurring_periods"),
        ("sales", "0057_freight_terms_either_side"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="reversed_discount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), editable=False, max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="reversed_write_off",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), editable=False, max_digits=18
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="settlement_reversal_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
    ]
