# Generated by Django 5.2.17 on 2026-10-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0022_statement_line_returns_a_payment"),
        ("sales", "0058_credit_note_undoes_settlements"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="What shipping it posted: cost of sales out of stock, or back in on a return.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
    ]
