# Generated by Django 5.2.17 on 2026-10-07 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0022_statement_line_returns_a_payment"),
        ("sales", "0060_discount_withdrawn_with_its_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoicepayment",
            name="fx_released_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Its payment returned: the exchange difference it realised, reversed on that day.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
    ]
