# Generated by Django 5.2.17 on 2026-10-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0061_returned_payment_releases_fx"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryallocation",
            name="cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                editable=False,
                help_text="What its movement took off the shelf, or put back on a return: the total, frozen. A return puts back its share of this rather than a rate times a quantity. Blank on allocations made before it was kept, which read their movement's own rate.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryline",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                editable=False,
                help_text="What a unit cost on average across the batches it came off, frozen. A return puts back what each batch took (its allocations), not this rate.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
