# Generated by Django 5.2.17 on 2026-10-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0062_allocation_keeps_its_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="approved_figures",
            field=models.JSONField(
                blank=True,
                editable=False,
                help_text="What the approval covered, as the order stood when it was given: each line's discount, the total and the margin. A confirmed order changes within it; past it, it is refused (SalesOrder.refuse_going_past_the_policy).",
                null=True,
            ),
        ),
    ]
