# Generated by Django 5.2.17 on 2026-09-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("core", "0003_country_partytag_address_company_documentsequence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="default_cogs_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Cost of goods sold account when an item doesn't name its own.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="default_inventory_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset account for stock value when an item doesn't name its own.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="grni_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Goods received not invoiced: the accrual between receiving stock and being billed for it.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
