# Generated by Django 5.2.17 on 2026-09-19 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("core", "0004_company_default_cogs_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="settlement_discount_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Where early-settlement discounts are written off (an expense).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
