# Generated by Django 5.2.17 on 2026-09-19 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("core", "0005_company_settlement_discount_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="bad_debt_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account for receivables judged uncollectable.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
