# Generated by Django 5.2.17 on 2026-09-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_company_customer_deposit_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="tax_rounding",
            field=models.CharField(
                choices=[
                    ("line", "Round tax per line"),
                    ("document", "Round tax per document"),
                ],
                default="line",
                help_text="Some jurisdictions require tax computed on the document total per rate rather than line by line. The two differ by pennies, which is enough to fail a tax return's reconciliation.",
                max_length=16,
            ),
        ),
    ]
