# Generated by Django 5.2.17 on 2026-09-19 19:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("core", "0008_company_tax_rounding"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="default_purchase_expense_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Where a non-stocked purchase lands when its line names no account.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="purchase_price_tolerance_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="How far above the agreed purchase price a bill may go before it is refused. Zero means the vendor's price must match the order exactly.",
                max_digits=5,
            ),
        ),
    ]
