# Generated by Django 5.2.17 on 2026-09-20 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("core", "0009_company_default_purchase_expense_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="purchase_price_variance_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Where the difference lands when a vendor bills a different price than was agreed on the order (an expense; a credit means they billed less).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
