# Generated by Django 5.2.17 on 2026-09-20 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("core", "0010_company_purchase_price_variance_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="settlement_discount_received_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Where early-settlement discounts taken from vendors are booked (income, or a contra-expense).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
