# Generated by Django 5.2.17 on 2026-09-20 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("core", "0011_company_settlement_discount_received_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="vendor_prepayment_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset account holding money paid to a vendor before the goods arrive.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
