# Generated by Django 5.2.17 on 2026-09-20 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_payment_voided_entry"),
        ("core", "0012_company_vendor_prepayment_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="fx_gain_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Realised exchange gains — when a foreign balance settles for more base currency than it was booked at.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="fx_loss_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Realised exchange losses — when it settles for less.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
