# Generated by Django 5.2.17 on 2026-09-20 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_company_fx_gain_account_company_fx_loss_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTermsLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveSmallIntegerField(default=10)),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Share of the document falling due here. All lines must total 100.",
                        max_digits=6,
                    ),
                ),
                (
                    "days",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Days from the document date until this installment is due.",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Snap to this day of the resulting month — 31 means end of month, which is how 'net 30 EOM' is actually written.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "terms",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.paymentterms",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("percent__gt", 0)),
                        name="installment_percent_positive",
                    )
                ],
            },
        ),
    ]
