# Generated by Django 5.2.17 on 2026-09-20 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_paymenttermsline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="unitofmeasure",
            constraint=models.CheckConstraint(
                condition=models.Q(("conversion_factor__gt", 0)),
                name="uom_conversion_factor_positive",
            ),
        ),
    ]
