# Generated by Django 5.2.17 on 2026-09-21 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accountingperiod"),
        ("core", "0015_unitofmeasure_uom_conversion_factor_positive"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="net_pay_account",
            field=models.ForeignKey(
                blank=True,
                help_text="What payroll owes its staff between posting a pay run and paying it. A control account: it is emptied by paying people, and a balance that never clears is wages nobody has chased.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
