# Generated by Django 5.2.17 on 2026-10-04 15:32

import django.db.models.deletion
from django.db import migrations, models


def carry_counters_across(apps, schema_editor):
    """
    The one counter a sequence kept was for its current year: it becomes
    that year's. Before the RemoveField, which the autodetector put first.
    """
    Sequence = apps.get_model("core", "DocumentSequence")
    Year = apps.get_model("core", "DocumentSequenceYear")
    for sequence in Sequence.objects.filter(reset_yearly=True, current_year__isnull=False):
        Year.objects.create(sequence=sequence, year=sequence.current_year,
                            next_number=sequence.next_number)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSequenceYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("next_number", models.PositiveIntegerField(default=1)),
                (
                    "sequence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="years",
                        to="core.documentsequence",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "year"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sequence", "year"), name="one_counter_per_year"
                    )
                ],
            },
        ),
        migrations.RunPython(carry_counters_across, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="documentsequence",
            name="current_year",
        ),
    ]
