# Generated by Django 5.2.17 on 2026-10-05 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0016_list_indexes"),
        ("core", "0018_login_failures"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="default_bank_account",
            field=models.ForeignKey(
                blank=True,
                help_text="The bank a payment goes through when it names none.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="default_payable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="What is owed to vendors is booked to this, when a bill or a payment out names no account of its own.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="default_receivable_account",
            field=models.ForeignKey(
                blank=True,
                help_text="What customers owe is booked to this, when an invoice or a receipt names no account of its own.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="default_revenue_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Where a sale is credited when its line names no revenue account.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
