# Generated by Django 5.2.17 on 2026-10-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_default_accounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginfailure",
            name="address",
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True),
        ),
    ]
