# Generated by Django 5.2.17 on 2026-10-06 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_login_failure_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("factory", "Factory licence"),
                            ("consent", "Consent to operate (pollution board)"),
                            ("fire", "Fire NOC"),
                            ("metrology", "Weights and measures stamping"),
                            ("boiler", "Boiler certificate"),
                            ("trade", "Trade licence"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "licence_number",
                    models.CharField(
                        help_text="The authority's number, not one of ours.",
                        max_length=64,
                    ),
                ),
                (
                    "issued_by",
                    models.CharField(
                        blank=True,
                        help_text="The office that issues and renews it.",
                        max_length=128,
                    ),
                ),
                (
                    "covers",
                    models.CharField(
                        blank=True,
                        help_text='What it is for, where the plant holds several: "Weighbridge WB-1".',
                        max_length=128,
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField()),
                (
                    "remind_days",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="How long before it lapses to start renewing: the board's own processing time and some.",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "renewed_by",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renews",
                        to="core.licence",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["valid_to", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("valid_to__gte", models.F("valid_from"))),
                        name="licence_ends_after_it_starts",
                    ),
                    models.UniqueConstraint(
                        fields=("kind", "licence_number", "valid_from"),
                        name="licence_issued_once",
                    ),
                ],
            },
        ),
    ]
