# Generated by Django 5.2.17 on 2026-10-07 04:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0021_licences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveBigIntegerField()),
                (
                    "at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Made"),
                            ("updated", "Changed"),
                            ("action", "Done"),
                            ("mail", "Sent"),
                            ("deleted", "Deleted"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        help_text="The action's name: post, void, approve, send.",
                        max_length=64,
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="The fields a change touched, or who a mail went to.",
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "who",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id", "-at"],
                        name="record_event_by_record",
                    )
                ],
            },
        ),
    ]
