# Generated by Django 5.2.17 on 2026-10-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_attachments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "permissions": [
                    ("import_records", "Can bring the old system's records in")
                ],
                "verbose_name_plural": "company",
            },
        ),
    ]
