# Generated by Django 5.2.17 on 2026-10-07 07:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_import_records_and_depreciated_before"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "permissions": [
                    ("import_records", "Can bring the old system's records in"),
                    (
                        "check_health",
                        "Can read whether the books agree and the server is well",
                    ),
                ],
                "verbose_name_plural": "company",
            },
        ),
        migrations.CreateModel(
            name="ServerError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.CharField(editable=False, max_length=12, unique=True)),
                (
                    "happened_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("path", models.CharField(blank=True, editable=False, max_length=255)),
                ("method", models.CharField(blank=True, editable=False, max_length=8)),
                (
                    "kind",
                    models.CharField(
                        editable=False,
                        help_text="The exception's class.",
                        max_length=128,
                    ),
                ),
                ("message", models.TextField(blank=True, editable=False)),
                ("traceback", models.TextField(blank=True, editable=False)),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, help_text="What was done about it.", max_length=255
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "server error",
                "ordering": ["-happened_at", "-id"],
            },
        ),
    ]
