# Generated by Django 5.2.17 on 2026-10-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_servererror_check_health"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="company",
            name="bank_ifsc",
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name="company",
            name="bank_name",
            field=models.CharField(
                blank=True,
                help_text="The bank and branch customers pay into.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="partybankaccount",
            name="ifsc",
            field=models.CharField(
                blank=True,
                help_text="The branch's IFSC, for NEFT and RTGS: HDFC0001234.",
                max_length=11,
            ),
        ),
    ]
