# Generated by Django 5.2.17 on 2026-10-07 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_bank_particulars"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="extra",
            field=models.JSONField(
                blank=True, db_default={}, default=dict, help_text="The custom fields' values, by key."
            ),
        ),
        migrations.CreateModel(
            name="CustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("assets.fixedasset", "Fixed assets"),
                            ("core.party", "Customers and vendors"),
                            ("hr.employee", "Employees"),
                            ("inventory.item", "Items"),
                            ("manufacturing.machine", "Machines"),
                            ("purchasing.bill", "Bills and debit notes"),
                            ("purchasing.purchaseorder", "Purchase orders"),
                            ("sales.invoice", "Invoices and credit notes"),
                            ("sales.salesorder", "Sales orders"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="How the value is stored and sent: letters, digits and _ ; never changes.",
                        max_length=32,
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("yes_no", "Yes or no"),
                            ("choice", "One of a list"),
                        ],
                        default="text",
                        max_length=8,
                    ),
                ),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="One choice a line, for a field that is one of a list.",
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=False,
                        help_text="Must be filled when the record is saved from the office.",
                    ),
                ),
                ("hint", models.CharField(blank=True, max_length=255)),
                ("position", models.PositiveSmallIntegerField(default=10)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Off, the field is hidden and its values kept.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "position", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "key"), name="one_custom_field_per_key"
                    )
                ],
            },
        ),
    ]
