# Generated by Django 5.2.17 on 2026-10-07 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="cin",
            field=models.CharField(
                blank=True,
                help_text="Corporate identity number, for a company: U25209MH2015PTC123456.",
                max_length=21,
                verbose_name="CIN",
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="iec",
            field=models.CharField(
                blank=True,
                help_text="Importer-exporter code, for a party trading across the border.",
                max_length=10,
                verbose_name="IEC",
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="notes",
            field=models.TextField(
                blank=True, help_text="What the office should know that no field holds."
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The group or head company it belongs to: a cement group's several plants.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_members",
                to="core.party",
            ),
        ),
        migrations.AddField(
            model_name="party",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
