# Generated by Django 5.2.17 on 2026-10-07 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_notes_and_follow_ups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "screen",
                    models.CharField(
                        help_text="The list's place in the application: /sales/invoices.",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                (
                    "query",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The list's narrowing, as its address carries it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["screen", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "screen", "name"),
                        name="saved_filter_name_once_a_list",
                    )
                ],
            },
        ),
    ]
