# Generated by Django 5.2.17 on 2026-10-10 22:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_role_proposals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="roleproposal",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Waiting for confirmation"),
                    ("confirmed", "Confirmed"),
                    ("declined", "Declined"),
                    ("lapsed", "Lapsed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="KeptCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("password", "Password"), ("email", "Email")],
                        max_length=8,
                    ),
                ),
                ("value", models.CharField(max_length=254)),
                ("set_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lapsed", models.BooleanField(default=False)),
                (
                    "set_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kept_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "kind"), name="one_kept_credential_per_kind"
                    )
                ],
            },
        ),
    ]
