# Generated by Django 5.2.17 on 2026-09-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="journalentry",
            options={
                "ordering": ["-date", "-id"],
                "permissions": [
                    ("post_journalentry", "Can post and reverse journal entries")
                ],
                "verbose_name_plural": "journal entries",
            },
        ),
    ]
