# Generated by Django 5.2.17 on 2026-09-19 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_payment"),
        ("core", "0003_country_partytag_address_company_documentsequence_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="number",
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="unique_payment_number",
            ),
        ),
    ]
