# Generated by Django 5.2.17 on 2026-09-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_chargetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargetype",
            name="capitalise_into_inventory",
            field=models.BooleanField(
                default=False,
                help_text="Inbound only: add this charge to the value of the goods it brought in rather than expensing it, so cost of sales reflects what the stock actually cost to get here.",
            ),
        ),
    ]
