# Generated by Django 5.2.17 on 2026-09-20 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_chargetype_capitalise_into_inventory"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="voided_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The reversing entry, set when this payment is voided.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
    ]
