# Generated by Django 5.2.17 on 2026-09-27 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accountingperiod"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partytaxprofile",
            name="gst_registration",
            field=models.CharField(
                blank=True,
                choices=[
                    ("regular", "Registered, regular"),
                    ("composition", "Registered, composition"),
                    ("sez", "Special economic zone"),
                    ("unregistered", "Unregistered"),
                    ("overseas", "Overseas"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="partytaxprofile",
            name="gst_state",
            field=models.CharField(
                blank=True,
                help_text="Where the party is, as a GST state code. Read off the GSTIN when there is one; typed only for an unregistered party, whose state still decides which taxes a supply to it bears.",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="partytaxprofile",
            name="gstin",
            field=models.CharField(
                blank=True,
                help_text="The party's GST registration, checked character by character. Its first two digits are its state.",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="GstSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gstin", models.CharField(max_length=15)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("01", "Jammu and Kashmir"),
                            ("02", "Himachal Pradesh"),
                            ("03", "Punjab"),
                            ("04", "Chandigarh"),
                            ("05", "Uttarakhand"),
                            ("06", "Haryana"),
                            ("07", "Delhi"),
                            ("08", "Rajasthan"),
                            ("09", "Uttar Pradesh"),
                            ("10", "Bihar"),
                            ("11", "Sikkim"),
                            ("12", "Arunachal Pradesh"),
                            ("13", "Nagaland"),
                            ("14", "Manipur"),
                            ("15", "Mizoram"),
                            ("16", "Tripura"),
                            ("17", "Meghalaya"),
                            ("18", "Assam"),
                            ("19", "West Bengal"),
                            ("20", "Jharkhand"),
                            ("21", "Odisha"),
                            ("22", "Chhattisgarh"),
                            ("23", "Madhya Pradesh"),
                            ("24", "Gujarat"),
                            ("26", "Dadra and Nagar Haveli and Daman and Diu"),
                            ("27", "Maharashtra"),
                            ("29", "Karnataka"),
                            ("30", "Goa"),
                            ("31", "Lakshadweep"),
                            ("32", "Kerala"),
                            ("33", "Tamil Nadu"),
                            ("34", "Puducherry"),
                            ("35", "Andaman and Nicobar Islands"),
                            ("36", "Telangana"),
                            ("37", "Andhra Pradesh"),
                            ("38", "Ladakh"),
                            ("97", "Other Territory"),
                        ],
                        editable=False,
                        help_text="Taken from the GSTIN, never typed: the two cannot disagree if one is read off the other.",
                        max_length=2,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interstate_position",
                    models.ForeignKey(
                        help_text="What a supply across a state line maps its taxes through — central and state tax to integrated tax at the whole rate.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.fiscalposition",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GST settings",
                "verbose_name_plural": "GST settings",
            },
        ),
    ]
