# Generated by Django 5.2.17 on 2026-09-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_partytaxprofile_gst_registration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargetype",
            name="hsn_code",
            field=models.CharField(
                blank=True,
                help_text="SAC for a service charge — 9965 for goods transport, say.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="tax",
            name="gst_head",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cgst", "Central tax (CGST)"),
                    ("sgst", "State or union territory tax (SGST/UTGST)"),
                    ("igst", "Integrated tax (IGST)"),
                    ("cess", "Compensation cess"),
                    ("other", "Not GST"),
                ],
                help_text="Which column of a GST return this tax is reported in. Blank is refused on a document posted under GST: a return cannot put an unclassified tax anywhere.",
                max_length=8,
            ),
        ),
    ]
