# Generated by Django 5.2.17 on 2026-09-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0012_chargetype_hsn_code_tax_gst_head"),
    ]

    operations = [
        migrations.AddField(
            model_name="gstsettings",
            name="b2cl_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=100000,
                help_text="An inter-state invoice to an unregistered buyer above this is reported invoice by invoice (B2CL) rather than in the summary. 1,00,000 since August 2024; a setting because it is set by notification.",
                max_digits=18,
            ),
        ),
    ]
