# Generated by Django 5.2.17 on 2026-09-28 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0013_gstsettings_b2cl_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="gstsettings",
            name="einvoicing_from",
            field=models.DateField(
                blank=True,
                help_text="The first invoice date that must carry an IRN: from when aggregate turnover passed 5 crore. A fact the company declares, since turnover across every registration on its PAN is not in this system. A date, not a switch, so an invoice from before it is not asked for one.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="gstsettings",
            name="eway_bill_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=50000,
                help_text="A consignment worth more than this moves on an e-way bill. 50,000 by the central rule; some states set a higher one for movement inside the state, which this does not model.",
                max_digits=18,
            ),
        ),
    ]
