# Generated by Django 5.2.17 on 2026-09-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0014_gstsettings_einvoicing_from_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gstsettings",
            name="job_work_sac",
            field=models.CharField(
                blank=True,
                help_text="The SAC a job-work order's conversion is billed under: manufacturing services on goods the customer owns. A setting, because the code for plastic products is chosen with the company's adviser, not by this system.",
                max_length=8,
            ),
        ),
    ]
