# Generated by Django 5.2.17 on 2026-10-04 18:59

from django.conf import settings
from django.db import migrations, models

from apps.core.trigram import trigram_indexes


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_gstsettings_job_work_sac"),
        ("core", "0018_login_failures"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="journalentry",
            index=models.Index(fields=["date", "id"], name="journal_entry_by_date"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["payment_date", "id"], name="payment_by_date"),
        ),
        # ?search= on the lists (apps/core/trigram.py).
        trigram_indexes(
            ("accounting_payment", "number"),
            ("accounting_payment", "reference"),
            ("accounting_payment", "memo"),
            ("accounting_journalentry", "reference"),
            ("accounting_journalentry", "memo"),
        ),
    ]
