# Generated by Django 5.2.17 on 2026-10-06 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0016_list_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partytaxprofile",
            name="pan",
            field=models.CharField(
                blank=True,
                help_text="The party's PAN. Read off the GSTIN when there is one; without either, tax is deducted at the no-PAN rate.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="partytaxprofile",
            name="tds_rate_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="A rate of its own under that section: an individual's 1% under 194C, or a lower-deduction certificate (section 197). Empty for the section's rate.",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partytaxprofile",
            name="tds_rate_reference",
            field=models.CharField(
                blank=True,
                help_text="The certificate or reason the rate of its own rests on.",
                max_length=64,
            ),
        ),
        migrations.CreateModel(
            name="TdsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="194Q, 194C, 194J", max_length=16, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "rate_percent",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Deducted from a party whose PAN is on file.",
                        max_digits=7,
                    ),
                ),
                (
                    "no_pan_rate_percent",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Deducted from a party with no PAN on file (section 206AA).",
                        max_digits=7,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            (
                                "excess",
                                "On what the year passes the threshold by (194Q)",
                            ),
                            (
                                "whole",
                                "On the whole year once a limit is passed (194C, 194J)",
                            ),
                        ],
                        default="whole",
                        max_length=8,
                    ),
                ),
                (
                    "single_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="One bill above this is taxed. Empty for none.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "annual_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The year's bills from one party above this are taxed. Empty for none.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where tax the company deducts is owed until a challan pays it over.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "receivable_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where tax a customer deducted waits to be claimed against Form 26AS.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="partytaxprofile",
            name="tds_section",
            field=models.ForeignKey(
                blank=True,
                help_text="The section its bills are deducted under by default.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.tdssection",
            ),
        ),
        migrations.AddConstraint(
            model_name="tdssection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rate_percent__gte", 0), ("no_pan_rate_percent__gte", 0)
                ),
                name="tds_rates_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="tdssection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("mode", "excess"), _negated=True),
                    ("annual_threshold__isnull", False),
                    _connector="OR",
                ),
                name="tds_excess_has_an_annual_threshold",
            ),
        ),
    ]
