# Generated by Django 5.2.17 on 2026-10-06 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0017_tds_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="reverse_charge",
            field=models.BooleanField(
                default=False,
                help_text="Paid by the company rather than charged by the vendor: freight from a goods transport agency, say. Adds nothing to what the vendor is owed; the company owes it to the government and claims it back as credit.",
            ),
        ),
        migrations.AddField(
            model_name="tax",
            name="reverse_charge_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Reverse charge: where the tax the company owes on the vendor's supply waits to be paid in cash.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
    ]
