# Generated by Django 5.2.17 on 2026-10-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0018_tax_reverse_charge_tax_reverse_charge_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="partytaxprofile",
            name="msme_category",
            field=models.CharField(
                blank=True,
                choices=[("micro", "Micro"), ("small", "Small"), ("medium", "Medium")],
                help_text="As its Udyam registration says. A micro or small vendor is paid within 45 days, or the expense waits for the payment before it is deducted (section 43B(h)).",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="partytaxprofile",
            name="udyam_number",
            field=models.CharField(
                blank=True, help_text="UDYAM-XX-00-0000000", max_length=19
            ),
        ),
    ]
