# Generated by Django 5.2.17 on 2026-10-07 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0021_budgets_recurring_periods"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatementline",
            name="returned_payment",
            field=models.OneToOneField(
                blank=True,
                help_text="The payment the bank took back on this line: a cheque returned unpaid, a transfer recalled.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="returned_line",
                to="accounting.payment",
            ),
        ),
    ]
