# Generated by Django 5.2.17 on 2026-10-08 06:30

from django.db import migrations, models

from ._holds_money import mark


def money_went_through(apps, schema_editor):
    """Every bank a payment or a statement named, and the company's own."""
    ids = set(apps.get_model("accounting", "Payment").objects.values_list("bank_account", flat=True))
    ids |= set(apps.get_model("accounting", "BankStatement").objects.values_list("bank_account", flat=True))
    ids |= set(apps.get_model("core", "Company").objects.values_list("default_bank_account", flat=True))
    mark(apps, ids)


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0022_statement_line_returns_a_payment"),
        ("core", "0030_saved_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="holds_money",
            field=models.BooleanField(
                default=False,
                help_text="A bank, cash box, card or overdraft: what payments, claims and challans are paid from or into. Nothing else is offered as one.",
            ),
        ),
        migrations.RunPython(money_went_through, migrations.RunPython.noop),
    ]
