# Generated by Django 5.2.17 on 2026-10-10 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0023_account_holds_money"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bankstatementline",
            name="booked_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Money a document already booked through the bank, not as a payment: a TDS challan, an expense claim paid out. Matched to it, not posted again.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddConstraint(
            model_name="bankstatementline",
            constraint=models.UniqueConstraint(
                fields=("booked_entry",), name="one_statement_line_per_booked_entry"
            ),
        ),
    ]
