# Generated by Django 5.2.17 on 2026-09-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_item_created_by_item_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="allow_negative_stock",
            field=models.BooleanField(
                default=False,
                help_text="Permit shipping more than is on hand (backorders, in-transit stock).",
            ),
        ),
    ]
