# Generated by Django 5.2.17 on 2026-09-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_alter_payment_number_payment_unique_payment_number"),
        ("inventory", "0003_warehouse_allow_negative_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="cogs_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Expense account charged when this item is sold. Falls back to the company default.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="inventory_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset account holding this item's stock value. Falls back to the company default.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Cost per unit for this movement; set from the purchase price inbound, from the weighted average outbound.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
