# Generated by Django 5.2.17 on 2026-09-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_item_cogs_account_item_inventory_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default list price, used when no price list covers this item.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
