# Generated by Django 5.2.17 on 2026-09-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_item_sale_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="value_adjustment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Money added to (or taken off) the stock value without moving any quantity — landed cost, mainly. Raises the weighted average.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
