# Generated by Django 5.2.17 on 2026-09-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_stockmovement_value_adjustment"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="is_quarantine",
            field=models.BooleanField(
                default=False,
                help_text="Holds goods received but not yet accepted. The stock is owned and valued; it simply may not be shipped until someone has looked at it.",
            ),
        ),
    ]
