# Generated by Django 5.2.17 on 2026-09-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_paymenttermsline"),
        ("inventory", "0007_warehouse_is_quarantine"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="consignment_vendor",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the stock here belongs to a vendor until it is used. It is on the premises and not on the books.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consignment_warehouses",
                to="core.party",
            ),
        ),
    ]
