# Generated by Django 5.2.17 on 2026-09-20 14:22

import django.db.models.deletion
from django.db import migrations, models


def fill_uom_from_item(apps, schema_editor):
    """
    Nothing converted before this, so every existing movement's quantity
    already sits in the item's own unit by accident. Recording that is the
    truthful backfill: it changes no number, it writes down what the
    number already meant.
    """
    StockMovement = apps.get_model("inventory", "StockMovement")
    for movement in StockMovement.objects.select_related("item").iterator():
        StockMovement.objects.filter(pk=movement.pk).update(
            uom_id=movement.item.uom_id, document_quantity=movement.quantity
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_unitofmeasure_uom_conversion_factor_positive"),
        ("inventory", "0008_warehouse_consignment_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="document_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                editable=False,
                help_text="The quantity as the document wrote it, in `uom`. Kept so a movement can be read back against the paperwork that caused it.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="uom",
            field=models.ForeignKey(
                help_text="The unit the document spoke in. Required on write; the quantity stored alongside it has already been restated in the item's stocking unit, so the ledger only ever counts in one unit.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.unitofmeasure",
            ),
        ),
        migrations.RunPython(fill_uom_from_item, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="stockmovement",
            name="uom",
            field=models.ForeignKey(
                help_text="The unit the document spoke in. Required on write; the quantity stored alongside it has already been restated in the item's stocking unit, so the ledger only ever counts in one unit.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.unitofmeasure",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4,
                help_text="In the item's stocking unit. Positive for inbound movements (receipt, transfer_in), negative for outbound.",
                max_digits=18,
            ),
        ),
    ]
