# Generated by Django 5.2.17 on 2026-09-20 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accountingperiod"),
        ("core", "0015_unitofmeasure_uom_conversion_factor_positive"),
        (
            "inventory",
            "0009_stockmovement_document_quantity_stockmovement_uom_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdjustmentReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("increase", "Increase only"),
                            ("decrease", "Decrease only"),
                            ("both", "Either"),
                        ],
                        default="both",
                        help_text="Which way this reason may move stock. Shrinkage that can create stock is not shrinkage.",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Where the other side of the adjustment posts — a shrinkage expense, a write-off, a revaluation gain.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("count_date", models.DateField()),
                ("memo", models.CharField(blank=True, max_length=255)),
                ("counted_by", models.CharField(blank=True, max_length=255)),
                ("posted", models.BooleanField(default=False)),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        help_text="Where the variance posts. A count that finds less than the books said is normally shrinkage.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counts",
                        to="inventory.adjustmentreason",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counts",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-count_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("adjustment_date", models.DateField()),
                ("memo", models.CharField(blank=True, max_length=255)),
                ("posted", models.BooleanField(default=False)),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="inventory.adjustmentreason",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="The reversal raised when this was voided, so a reader can see what undid it rather than inferring it.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "count",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Set when this adjustment was raised by posting a count sheet.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="inventory.stockcount",
                    ),
                ),
            ],
            options={
                "ordering": ["-adjustment_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockCountLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counted_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="What was found, in `uom`.",
                        max_digits=18,
                    ),
                ),
                (
                    "system_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        editable=False,
                        help_text="What the books said when this line was written, in the item's stocking unit. Frozen: re-reading it at posting time would hide anything that moved in between.",
                        max_digits=18,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stockcount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="count_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        help_text="The unit the counter counted in — cases on the pallet, eaches on the shelf.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StockAdjustmentLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Signed: positive writes stock up, negative writes it down.",
                        max_digits=18,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="What a stocking unit is worth for this adjustment. Left blank it is taken from the weighted average when the line posts, and frozen there.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stockadjustment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustment_lines",
                        to="inventory.item",
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="The movement this line wrote, so voiding reverses exactly what was written rather than recomputing it.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "reversal_movement",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        help_text="The unit the quantity below is written in.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity", 0), _negated=True),
                        name="adjustment_line_quantity_not_zero",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="stockcount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="stock_count_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="stock_adjustment_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.UniqueConstraint(
                fields=("count", "item"), name="one_count_line_per_item"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.CheckConstraint(
                condition=models.Q(("counted_quantity__gte", 0)),
                name="count_line_quantity_not_negative",
            ),
        ),
    ]
