# Generated by Django 5.2.17 on 2026-09-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0011_warehouse_is_transit_stocktransfer_stocktransferline_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="value_adjustment",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Value added to (or taken off) the stock without moving any quantity — landed cost, and the remainder a conversion or a transfer cannot express in a unit cost. Four places, not two: a posted amount is money and rounds to the cent, but this also carries what is left when a value is divided by a quantity, and rounding that to the cent loses a little on every move.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
