# Generated by Django 5.2.17 on 2026-09-20 14:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0012_alter_stockmovement_value_adjustment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Claimed, in the item's stocking unit.",
                        max_digits=18,
                    ),
                ),
                (
                    "consumed",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        editable=False,
                        help_text="How much of the claim has actually shipped. Kept beside the claim rather than subtracted from it, so the record still says what was promised as well as what is left.",
                        max_digits=18,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(editable=False)),
                (
                    "released_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "released_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["item", "warehouse", "released_at"],
                        name="inventory_s_item_id_15655d_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="reservation_quantity_positive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("released_at__isnull", True)),
                        fields=("content_type", "object_id"),
                        name="one_open_reservation_per_source",
                    ),
                ],
            },
        ),
    ]
