# Generated by Django 5.2.17 on 2026-09-20 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_stockreservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="tracking",
            field=models.CharField(
                choices=[
                    ("none", "Not tracked"),
                    ("lot", "By lot or batch"),
                    ("serial", "By serial number"),
                ],
                default="none",
                help_text="Whether each movement of this item must name the batch it came from, or the individual unit. Defaults to neither, so nothing already in the ledger is retrospectively incomplete.",
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Batch number, or the serial number.", max_length=64
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(
                        blank=True,
                        help_text="After this date the goods may not be shipped. Left blank they do not expire.",
                        null=True,
                    ),
                ),
                ("manufactured_on", models.DateField(blank=True, null=True)),
                (
                    "supplier_reference",
                    models.CharField(
                        blank=True,
                        help_text="The vendor's own batch number, kept so a recall notice quoting it can be matched to stock here.",
                        max_length=64,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["item", "expires_on", "code"],
            },
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Which batch, or which unit. Required when the item is tracked, refused when it is not.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.lot",
            ),
        ),
        migrations.AddIndex(
            model_name="lot",
            index=models.Index(
                fields=["item", "expires_on"], name="inventory_l_item_id_3d1927_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lot",
            constraint=models.UniqueConstraint(
                fields=("item", "code"), name="one_lot_code_per_item"
            ),
        ),
    ]
