# Generated by Django 5.2.17 on 2026-09-20 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_unitofmeasure_uom_conversion_factor_positive"),
        ("inventory", "0014_item_tracking_lot_stockmovement_lot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stockcountline",
            name="one_count_line_per_item",
        ),
        migrations.RemoveConstraint(
            model_name="stocktransferline",
            name="one_transfer_line_per_item",
        ),
        migrations.AddField(
            model_name="stockadjustmentline",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Which batch is being written up or down. Required when the item is tracked.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.lot",
            ),
        ),
        migrations.AddField(
            model_name="stockcountline",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Which batch was counted. Required when the item is tracked: a shortfall that cannot say which batch is missing is not a traceable count.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.lot",
            ),
        ),
        migrations.AddField(
            model_name="stocktransferline",
            name="lot",
            field=models.ForeignKey(
                blank=True,
                help_text="Which batch is moving. Required when the item is tracked — a transfer that cannot say which batch left has broken the trail.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.lot",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lot__isnull", True)),
                fields=("count", "item"),
                name="one_count_line_per_untracked_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lot__isnull", False)),
                fields=("count", "item", "lot"),
                name="one_count_line_per_item_lot",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransferline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lot__isnull", True)),
                fields=("transfer", "item"),
                name="one_transfer_line_per_untracked_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransferline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("lot__isnull", False)),
                fields=("transfer", "item", "lot"),
                name="one_transfer_line_per_item_lot",
            ),
        ),
    ]
