# Generated by Django 5.2.17 on 2026-09-20 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_remove_stockcountline_one_count_line_per_item_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="requires_bins",
            field=models.BooleanField(
                default=False,
                help_text="Every movement in or out must name a bin. Off by default, so turning it on is a decision rather than something a warehouse acquires by accident — and stock booked in before it was turned on stays readable through unbinned().",
            ),
        ),
        migrations.CreateModel(
            name="StorageBin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(help_text="e.g. A-04-3", max_length=32)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Walking order. A pick list sorted by this is a route rather than a list of places in no particular order.",
                    ),
                ),
                (
                    "is_pickable",
                    models.BooleanField(
                        default=True,
                        help_text="False for a grouping level — an aisle or a zone — that names somewhere without being somewhere stock can sit.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The larger place this one sits in — a rack within an aisle.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="inventory.storagebin",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bins",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["warehouse", "sequence", "code"],
            },
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="bin",
            field=models.ForeignKey(
                blank=True,
                help_text="Where in the building. Required when the warehouse says so. Valuation ignores it: a bin changes where stock is, not what it is worth.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movements",
                to="inventory.storagebin",
            ),
        ),
        migrations.AddIndex(
            model_name="storagebin",
            index=models.Index(
                fields=["warehouse", "is_pickable"],
                name="inventory_s_warehou_f1fb15_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="storagebin",
            constraint=models.UniqueConstraint(
                fields=("warehouse", "code"), name="one_bin_code_per_warehouse"
            ),
        ),
    ]
