# Generated by Django 5.2.17 on 2026-09-20 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0016_warehouse_requires_bins_storagebin_stockmovement_bin_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stocktransfer",
            name="transfer_between_two_warehouses",
        ),
        migrations.AddField(
            model_name="stocktransferline",
            name="from_bin",
            field=models.ForeignKey(
                blank=True,
                help_text="Which shelf it is coming off.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.storagebin",
            ),
        ),
        migrations.AddField(
            model_name="stocktransferline",
            name="to_bin",
            field=models.ForeignKey(
                blank=True,
                help_text="Which shelf it is going on. On a two-step transfer this is where it lands at the far end, not where it rests in transit.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.storagebin",
            ),
        ),
    ]
