# Generated by Django 5.2.17 on 2026-09-20 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_unitofmeasure_uom_conversion_factor_positive"),
        (
            "inventory",
            "0017_remove_stocktransfer_transfer_between_two_warehouses_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stockcountline",
            name="one_count_line_per_untracked_item",
        ),
        migrations.RemoveConstraint(
            model_name="stockcountline",
            name="one_count_line_per_item_lot",
        ),
        migrations.AddField(
            model_name="stockadjustmentline",
            name="bin",
            field=models.ForeignKey(
                blank=True,
                help_text="Which shelf the difference is on.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.storagebin",
            ),
        ),
        migrations.AddField(
            model_name="stockcountline",
            name="bin",
            field=models.ForeignKey(
                blank=True,
                help_text="Which shelf was counted. A sheet that counts a whole warehouse names no bin; one that counts an aisle names each.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.storagebin",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bin__isnull", True), ("lot__isnull", True)),
                fields=("count", "item"),
                name="one_count_line_per_untracked_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bin__isnull", True), ("lot__isnull", False)),
                fields=("count", "item", "lot"),
                name="one_count_line_per_item_lot",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bin__isnull", False), ("lot__isnull", True)),
                fields=("count", "item", "bin"),
                name="one_count_line_per_item_bin",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("bin__isnull", False), ("lot__isnull", False)),
                fields=("count", "item", "lot", "bin"),
                name="one_count_line_per_item_lot_bin",
            ),
        ),
    ]
