# Generated by Django 5.2.17 on 2026-09-20 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0018_remove_stockcountline_one_count_line_per_untracked_item_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="costing_method",
            field=models.CharField(
                choices=[
                    ("average", "Weighted average"),
                    ("fifo", "First in, first out"),
                    ("standard", "Standard cost"),
                ],
                default="average",
                help_text="How this item's stock is valued. Average needs no layer bookkeeping and cannot be gamed by choosing which physical unit to ship, which is why it is the default — but a company reporting FIFO or running to a standard cannot bolt either on later without restating every period.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="standard_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="What a unit is deemed to cost under standard costing. Changing it revalues the stock on hand, which is a posting, so change it through set_standard_cost() rather than by assignment.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="adjusts",
            field=models.ForeignKey(
                blank=True,
                help_text="On a value-only movement, the inbound movement whose goods the value belongs to. Landed cost knows which receipt it was incurred on; under FIFO that decides which layer it raises, and spreading it over the shelf instead would misprice everything that was already there.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="adjustments",
                to="inventory.stockmovement",
            ),
        ),
    ]
