# Generated by Django 5.2.17 on 2026-09-20 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_unitofmeasure_uom_conversion_factor_positive"),
        ("inventory", "0019_item_costing_method_item_standard_cost_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stockadjustmentline",
            name="adjustment_line_quantity_not_zero",
        ),
        migrations.AddField(
            model_name="stockadjustmentline",
            name="revaluation",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Value added to (or taken off) stock without moving any of it — a change of standard cost, a write-down to net realisable value. A line carries this or a quantity, not both.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stockadjustmentline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Signed: positive writes stock up, negative writes it down. Zero on a line that only changes what the stock is worth.",
                max_digits=18,
            ),
        ),
        migrations.AddConstraint(
            model_name="stockadjustmentline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("quantity", 0),
                        ("revaluation__isnull", False),
                        models.Q(("revaluation", 0), _negated=True),
                    ),
                    models.Q(
                        models.Q(("quantity", 0), _negated=True),
                        ("revaluation__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="adjustment_line_moves_quantity_or_value",
            ),
        ),
    ]
