# Generated by Django 5.2.17 on 2026-09-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0020_remove_stockadjustmentline_adjustment_line_quantity_not_zero_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="stockadjustment",
            name="from_standard_change",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Set when a change of standard cost raised this. Such an adjustment is a consequence of the standard rather than an event of its own, so it cannot be voided on its own.",
            ),
        ),
    ]
