# Generated by Django 5.2.17 on 2026-09-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_itemvariantvalue_item_variant_key_itemattribute_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="costing_method",
            field=models.CharField(
                choices=[
                    ("average", "Weighted average"),
                    ("fifo", "First in, first out"),
                    ("standard", "Standard cost"),
                    ("specific", "Specific identification"),
                ],
                default="average",
                help_text="How this item's stock is valued. Average needs no layer bookkeeping and cannot be gamed by choosing which physical unit to ship, which is why it is the default — but a company reporting FIFO or running to a standard cannot bolt either on later without restating every period.",
                max_length=16,
            ),
        ),
    ]
