# Generated by Django 5.2.17 on 2026-09-21 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0023_alter_item_costing_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="input_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="The bay goods land in before they are put away. Stock here is owned and valued and has not been put anywhere yet.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receives_for",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="quality_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Where goods wait to be looked at. Must be a quarantine warehouse, which is what stops them being shipped.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inspects_for",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="receipt_route",
            field=models.CharField(
                choices=[
                    ("direct", "Straight to stock"),
                    ("input", "Receiving bay, then stock"),
                    ("inspect", "Receiving bay, then inspection, then stock"),
                ],
                default="direct",
                help_text="How many places goods pass through on the way in. Declared here rather than remembered on every order line, because it is a fact about the building.",
                max_length=16,
            ),
        ),
    ]
