# Generated by Django 5.2.17 on 2026-09-21 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0025_stockposition"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockValuationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=16)),
                (
                    "boundary_at",
                    models.DateTimeField(
                        help_text="When the last movement folded into this happened. Anything landing at or before it makes the fold wrong."
                    ),
                ),
                (
                    "boundary_id",
                    models.PositiveIntegerField(
                        help_text="That movement's id, which breaks the tie when two share a moment."
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("value", models.DecimalField(decimal_places=6, max_digits=18)),
                (
                    "state",
                    models.JSONField(
                        default=dict,
                        help_text="Whatever the method needs beyond a quantity and a value: FIFO's layers, specific identification's per-batch pools. Empty for the methods that need neither.",
                    ),
                ),
                ("folded_at", models.DateTimeField(auto_now=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="inventory.item",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for the valuation across every warehouse, which pools them into one running average and is not the sum of the separate ones.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["item", "warehouse", "method"],
                        name="inventory_s_item_id_45be17_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("warehouse__isnull", True)),
                        fields=("item", "method"),
                        name="one_snapshot_per_item_and_method",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("warehouse__isnull", False)),
                        fields=("item", "warehouse", "method"),
                        name="one_snapshot_per_position_and_method",
                    ),
                ],
            },
        ),
    ]
