# Generated by Django 5.2.17 on 2026-09-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_stockvaluationsnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="hsn_code",
            field=models.CharField(
                blank=True,
                help_text="The tariff code tax law classifies this under — HSN for goods, SAC for a service. Four, six or eight digits. On every GST invoice line and in the HSN summary of the return; the rate is still the tax's, not the code's.",
                max_length=8,
            ),
        ),
    ]
