# Generated by Django 5.2.17 on 2026-09-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("inventory", "0028_item_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="held_for",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when the stock here is a customer's, sent to be worked on. On the premises, not on the books, and for that customer's work only.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="held_warehouses",
                to="core.party",
            ),
        ),
    ]
