# Generated by Django 5.2.17 on 2026-09-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_refold_company_wide_valuation"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockadjustment",
            name="raised_by",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="The document that raised this, when one did — spares issued to a maintenance job. It is voided through that document, whose own rules decide whether it may be.",
                max_length=64,
            ),
        ),
    ]
