# Generated by Django 5.2.17 on 2026-10-04 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_adjustment_raised_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Cost per unit for this movement; set from the purchase price inbound, from the weighted average outbound.",
                max_digits=24,
                null=True,
            ),
        ),
    ]
