# Generated by Django 5.2.17 on 2026-10-04 18:59

from django.conf import settings
from django.db import migrations, models

from apps.core.trigram import trigram_indexes


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_login_failures"),
        ("inventory", "0032_movement_unit_cost_precision"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockmovement",
            options={"ordering": ["-occurred_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["occurred_at", "id"], name="movement_by_time"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["item", "warehouse", "occurred_at", "id"],
                name="movement_replay",
            ),
        ),
        # ?search= on the lists (apps/core/trigram.py).
        trigram_indexes(
            ("inventory_stockmovement", "reference"),
            ("inventory_lot", "code"),
            ("inventory_lot", "supplier_reference"),
        ),
    ]
