# Generated by Django 5.2.17 on 2026-10-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_list_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="stock_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("raw_material", "Raw material"),
                    ("packing", "Packing material"),
                    ("consumable", "Stores and spares"),
                    ("semi_finished", "Semi-finished"),
                    ("finished", "Finished goods"),
                ],
                db_default="",
                default="",
                help_text="How the bank's stock statement groups it: raw material, packing, stores and spares, semi-finished or finished. Blank shows on the statement as unclassified.",
                max_length=16,
            ),
        ),
    ]
