# Generated by Django 5.2.17 on 2026-10-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0034_item_stock_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="extra",
            field=models.JSONField(
                blank=True, db_default={}, default=dict, help_text="The custom fields' values, by key."
            ),
        ),
    ]
