# Generated by Django 5.2.17 on 2026-10-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0035_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockadjustmentline",
            name="posted_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                editable=False,
                help_text="Signed value this line moved, frozen when it posted: on a write-down, exactly what the shelf gave up. The entry books it to the cent and a void puts it back, rather than a four-place rate multiplied by the quantity. Blank on lines posted before it was kept, which read their rate.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
