# Generated by Django 5.2.17 on 2026-09-21 13:18

import apps.manufacturing.woven
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("inventory", "0026_stockvaluationsnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillOfMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Bumped rather than edited once anything has been made to it, so a work order raised last month still reads against what it was actually built from.",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "quantity_produced",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="How much of the item one run of this BOM makes, in `uom`.",
                        max_digits=18,
                    ),
                ),
                (
                    "is_computed",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Set when something else works this BOM's numbers out — a product specification, in this plant's case. Such a BOM refuses to be edited by hand: a hand edit would survive until the next rebuild and no longer, which is worse than refusing.",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=True,
                        help_text="The one an explosion picks when it reaches this item and nobody named a BOM. An item may have several ways of being made — one loom width or another — but only one of them can be the answer to an unqualified question.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="What this makes.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boms",
                        to="inventory.item",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        help_text="The unit the batch size above is written in.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["item__sku", "-version"],
            },
        ),
        migrations.CreateModel(
            name="BomByproduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Expected output per run of the BOM, in `uom`.",
                        max_digits=18,
                    ),
                ),
                (
                    "valuation",
                    models.CharField(
                        choices=[
                            ("standard", "At the item's standard cost"),
                            ("share", "At a share of what the run cost"),
                            ("none", "At nothing"),
                        ],
                        default="standard",
                        help_text="How much of the run's cost this carries out with it. Reground trim is worth a standard recovery value, well under virgin polymer; sweepings are worth nothing and should say so rather than quietly absorbing a share.",
                        max_length=16,
                    ),
                ),
                (
                    "cost_share_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Used only when valuation is 'share': the percentage of the run's total cost this by-product carries.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("line_number", models.PositiveIntegerField(default=0)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="byproducts",
                        to="manufacturing.billofmaterials",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="byproduct_of",
                        to="inventory.item",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["bom", "line_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="BomComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Net requirement for one run of the BOM, before waste — what ends up in the product. Six decimal places because a sack's stitching thread is grammes per thousand bags and rounding it to four loses the line.",
                        max_digits=18,
                    ),
                ),
                (
                    "waste_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="Percentage of what is FED IN that never reaches the product — extruder purge, loom breaks, cut-and-stitch offcut. Gross requirement is net / (1 - waste/100), not net x (1 + waste/100): the loss is measured on the input, and over the four stages a printed laminated sack passes through the two readings diverge.",
                        max_digits=6,
                    ),
                ),
                ("line_number", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="manufacturing.billofmaterials",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="component_of",
                        to="inventory.item",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        help_text="The unit the quantity above is written in.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["bom", "line_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="FabricSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "ends_per_inch",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Warp tapes per inch, measured around the tube.",
                        max_digits=6,
                    ),
                ),
                (
                    "picks_per_inch",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weft tapes per inch, along it.",
                        max_digits=6,
                    ),
                ),
                (
                    "lay_flat_width_cm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The width of the tube laid flat, which is the width of the sack it will become.",
                        max_digits=8,
                    ),
                ),
                (
                    "weave",
                    models.CharField(
                        choices=[
                            ("tubular", "Tubular (circular loom)"),
                            ("flat", "Flat"),
                        ],
                        default="tubular",
                        max_length=8,
                    ),
                ),
                (
                    "target_gsm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What the customer was quoted. The loom makes what the mesh and the denier make; this is what it is supposed to make.",
                        max_digits=8,
                    ),
                ),
                (
                    "gsm_tolerance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5"),
                        help_text="How far the mesh may put the fabric from the target before the specification is wrong rather than merely approximate.",
                        max_digits=5,
                    ),
                ),
                (
                    "weaving_waste_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("2"),
                        help_text="Of the tape fed in: loom starts, tape breaks, selvedge.",
                        max_digits=6,
                    ),
                ),
                (
                    "waste_recovered_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("85"),
                        help_text="How much of that loss is collected and reground.",
                        max_digits=6,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bom",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fabric_specification",
                        to="manufacturing.billofmaterials",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fabric_item",
                    models.ForeignKey(
                        help_text="The woven fabric this makes, stocked and valued by weight — rolls are weighed, not measured. `metres_per_kg()` converts for whoever is standing at the cutting table.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fabric_specifications",
                        to="inventory.item",
                    ),
                ),
                (
                    "loom_waste_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="What the collected loom waste is booked as — usually the same regrind the extruder feeds on, which closes the loop.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
            bases=(apps.manufacturing.woven.SpecificationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BagSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "bag_width_cm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The finished sack's width, which is the fabric's lay-flat width: the tube is woven at the width of the bag it becomes.",
                        max_digits=8,
                    ),
                ),
                (
                    "bag_length_cm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The finished sack's length, hems excluded.",
                        max_digits=8,
                    ),
                ),
                (
                    "bottom_hem_cm",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("3"),
                        help_text="Fabric turned up and stitched at the bottom. Real fabric, cut and paid for, and left out of more than one costing.",
                        max_digits=6,
                    ),
                ),
                (
                    "top_hem_cm",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2"),
                        help_text="Fabric folded at the mouth, hemmed or left raw.",
                        max_digits=6,
                    ),
                ),
                ("is_laminated", models.BooleanField(default=False)),
                (
                    "lamination_gsm",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Weight of the coating per square metre of fabric, typically 12 to 20. Applied over the same area the fabric covers.",
                        max_digits=6,
                    ),
                ),
                (
                    "lamination_waste_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("4"),
                        help_text="Of the coating polymer fed in. A coating line's own loss, separate from what cutting and stitching waste.",
                        max_digits=6,
                    ),
                ),
                ("print_colours", models.PositiveSmallIntegerField(default=0)),
                (
                    "printed_faces",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="How many faces of the sack carry the print. Two is the usual answer and it is twice the ink of one.",
                    ),
                ),
                (
                    "ink_grams_per_sqm_per_colour",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("3"),
                        help_text="Ink laid down per square metre per colour. Small, and the only reason it is here is that a plant printing four colours on a million sacks is buying ink by the tonne.",
                        max_digits=8,
                    ),
                ),
                (
                    "thread_grams_per_bag",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.2"),
                        help_text="Sewing thread in the bottom seam.",
                        max_digits=8,
                    ),
                ),
                (
                    "liner_grams_per_bag",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "conversion_waste_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("2.5"),
                        help_text="Of the fabric fed into cutting and stitching: the offcut at each end of the roll, rejects, mis-stitched bags.",
                        max_digits=6,
                    ),
                ),
                (
                    "waste_recovered_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("70"),
                        help_text="How much of that offcut is collected and reground. Lower than upstream, because a printed laminated offcut is harder to reprocess than clean tape waste.",
                        max_digits=6,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bag_item",
                    models.ForeignKey(
                        help_text="The finished sack, counted in pieces.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bag_specifications",
                        to="inventory.item",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cutting_waste_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "ink_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "lamination_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The polymer the coating is extruded from.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "liner_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="An inner LDPE liner, for sacks that must keep moisture out.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "thread_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bom",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bag_specification",
                        to="manufacturing.billofmaterials",
                    ),
                ),
                (
                    "fabric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bags",
                        to="manufacturing.fabricspecification",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
            bases=(apps.manufacturing.woven.SpecificationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TapeSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "denier",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Grammes per 9,000 metres of tape. 1,000-denier tape runs 9,000 metres to the kilo. Everything that converts between the length a loom sees and the weight the ledger counts goes through this number.",
                        max_digits=10,
                    ),
                ),
                (
                    "tape_width_mm",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Slit width. With denier it fixes the stretched thickness, and with the loom's reed it fixes whether the tapes lie flat or ride over one another.",
                        max_digits=8,
                    ),
                ),
                (
                    "draw_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="How far the tape is stretched in the orientation oven. Recorded because it sets the tensile strength the customer specified; nothing here computes from it.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "regrind_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="How much of the blend is reprocessed material. Capped in practice by what the tensile spec will bear, which is a decision for the plant rather than a rule here.",
                        max_digits=6,
                    ),
                ),
                (
                    "filler_percent",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "masterbatch_percent",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "uv_percent",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "extrusion_waste_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("3"),
                        help_text="Of what is fed in: purge at start-up, edge trim, tape breaks.",
                        max_digits=6,
                    ),
                ),
                (
                    "waste_recovered_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("80"),
                        help_text="How much of that loss is collected and reground rather than burnt off, swept up or lost as dust.",
                        max_digits=6,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bom",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tape_specification",
                        to="manufacturing.billofmaterials",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "filler_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Calcium carbonate masterbatch.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "masterbatch_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Colour concentrate.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "regrind_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reprocessed plant waste. Both an input to this blend and an output of this process, which is what makes the material graph cyclic and why an explosion has to carry its path.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "tape_item",
                    models.ForeignKey(
                        help_text="The tape this makes, stocked and valued by weight.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tape_specifications",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uv_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="UV stabiliser concentrate, for sacks that will stand in a yard.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "virgin_granule",
                    models.ForeignKey(
                        help_text="The PP homopolymer. Its share of the blend is whatever the other materials leave.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
            bases=(apps.manufacturing.woven.SpecificationMixin, models.Model),
        ),
        migrations.AddField(
            model_name="fabricspecification",
            name="warp_tape",
            field=models.ForeignKey(
                help_text="The tape running along the fabric.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="woven_as_warp",
                to="manufacturing.tapespecification",
            ),
        ),
        migrations.AddField(
            model_name="fabricspecification",
            name="weft_tape",
            field=models.ForeignKey(
                blank=True,
                help_text="The tape running across it. Blank means the same tape both ways, which is the common case; plants running a heavier warp for strength and a lighter weft for cost say so here and get two components instead of one.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="woven_as_weft",
                to="manufacturing.tapespecification",
            ),
        ),
        migrations.AddConstraint(
            model_name="billofmaterials",
            constraint=models.UniqueConstraint(
                fields=("item", "version"), name="one_bom_per_item_and_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="billofmaterials",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_default", True)),
                fields=("item",),
                name="one_default_bom_per_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="billofmaterials",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_produced__gt", 0)),
                name="bom_batch_is_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="bombyproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="bom_byproduct_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="bombyproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("valuation", "share"), _negated=True),
                    ("cost_share_percent__isnull", False),
                    _connector="OR",
                ),
                name="bom_byproduct_share_needs_a_percentage",
            ),
        ),
        migrations.AddConstraint(
            model_name="bomcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="bom_component_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="bomcomponent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("waste_percent__gte", 0), ("waste_percent__lt", 100)
                ),
                name="bom_component_waste_under_one_hundred",
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("bag_width_cm__gt", 0), ("bag_length_cm__gt", 0)),
                name="bag_dimensions_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_laminated", True), ("lamination_gsm", 0), _connector="OR"
                ),
                name="unlaminated_bag_has_no_coating_weight",
            ),
        ),
        migrations.AddConstraint(
            model_name="tapespecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("denier__gt", 0)), name="tape_denier_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="tapespecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("tape_width_mm__gt", 0)), name="tape_width_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="fabricspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_per_inch__gt", 0), ("picks_per_inch__gt", 0)),
                name="fabric_mesh_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fabricspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("lay_flat_width_cm__gt", 0)),
                name="fabric_width_positive",
            ),
        ),
    ]
