# Generated by Django 5.2.17 on 2026-09-21 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_stockvaluationsnapshot"),
        ("manufacturing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="billofmaterials",
            name="version",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Which revision of this BOM it is. Several may exist for one item; only one of them can be the default an unqualified explosion picks.",
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("waste_recovered_percent__gte", 0),
                    ("waste_recovered_percent__lte", 100),
                ),
                name="bag_recovery_is_a_fraction_of_the_loss",
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("conversion_waste_percent__gte", 0),
                    ("conversion_waste_percent__lt", 100),
                    ("lamination_waste_percent__gte", 0),
                    ("lamination_waste_percent__lt", 100),
                ),
                name="bag_waste_under_one_hundred",
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("bottom_hem_cm__gte", 0), ("top_hem_cm__gte", 0)),
                name="bag_hems_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fabricspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_gsm__gt", 0)),
                name="fabric_target_gsm_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="fabricspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("gsm_tolerance_percent__gte", 0)),
                name="fabric_tolerance_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fabricspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("waste_recovered_percent__gte", 0),
                    ("waste_recovered_percent__lte", 100),
                ),
                name="fabric_recovery_is_a_fraction_of_the_loss",
            ),
        ),
        migrations.AddConstraint(
            model_name="fabricspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("weaving_waste_percent__gte", 0),
                    ("weaving_waste_percent__lt", 100),
                ),
                name="fabric_waste_under_one_hundred",
            ),
        ),
        migrations.AddConstraint(
            model_name="tapespecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("waste_recovered_percent__gte", 0),
                    ("waste_recovered_percent__lte", 100),
                ),
                name="tape_recovery_is_a_fraction_of_the_loss",
            ),
        ),
        migrations.AddConstraint(
            model_name="tapespecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extrusion_waste_percent__gte", 0),
                    ("extrusion_waste_percent__lt", 100),
                ),
                name="tape_waste_under_one_hundred",
            ),
        ),
        migrations.AddConstraint(
            model_name="tapespecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("regrind_percent__gte", 0),
                    ("filler_percent__gte", 0),
                    ("masterbatch_percent__gte", 0),
                    ("uv_percent__gte", 0),
                ),
                name="tape_blend_shares_not_negative",
            ),
        ),
    ]
