# Generated by Django 5.2.17 on 2026-09-21 13:53

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0003_manufacturingsettings_workcentre_workorder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="over_production_percent",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("10"),
                help_text="How far past the ordered quantity this run may book output. A loom runs long and a shift books what it made, so some allowance is right; unlimited is how a mistyped 100,000 kg takes a million off work in progress and puts it on a shelf.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="planned_material_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                editable=False,
                help_text="The material side of that plan before the by-products are credited back, frozen with it. A by-product valued at a share of the run takes its share of this — a fixed number — rather than of what has been issued so far, which would value the same regrind differently on Tuesday and Thursday.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
