# Generated by Django 5.2.17 on 2026-09-21 15:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("manufacturing", "0004_workorder_over_production_percent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Routing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RoutingOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        help_text="The order the work passes through. Not the primary key's order: operations are inserted between existing ones all the time, and renumbering them would rewrite history."
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "setup_minutes",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Once a run, whatever its size — threading a loom, washing down a press between colours. The reason a plant hates short runs, and invisible in any model that costs only by the unit.",
                        max_digits=10,
                    ),
                ),
                (
                    "units_per_hour",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="The rate for THIS product on THIS machine, in the bill of materials' own unit. Blank falls back to the work centre's nominal rate, which is right for a line that runs everything at the same speed and wrong for one that does not — so it is stated when it differs.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["routing", "sequence", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=255)),
                (
                    "setup_minutes",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "units_per_hour",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="The rate this run was planned at, resolved at release — the operation's own, or the machine's nominal one where the operation did not say. Resolved rather than looked up again, so a machine re-rated next month does not re-time a run that has already happened.",
                        max_digits=18,
                    ),
                ),
                (
                    "planned_minutes",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Setup plus run time for the whole order, frozen.",
                        max_digits=14,
                    ),
                ),
            ],
            options={
                "ordering": ["work_order", "sequence", "id"],
            },
        ),
        migrations.AddField(
            model_name="workcentre",
            name="available_hours_per_day",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("24"),
                help_text="Hours this machine can run on a day it runs at all. Twenty-four for a continuous line; less where a shift pattern or a maintenance window says so.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="workcentre",
            name="days_per_week",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("7"),
                help_text="Days a week it runs. Deliberately a number rather than a calendar: a public holiday is a company-wide fact and this module has no business owning one.",
                max_digits=4,
            ),
        ),
        migrations.AlterField(
            model_name="workcentre",
            name="capacity_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="The nominal rate, in `capacity_uom`. A routing operation that does not state its own rate for the product falls back to this; one that runs slower than the line's nominal speed says so on the operation.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="work_centre",
            field=models.ForeignKey(
                blank=True,
                help_text="The machine a single-operation run sits on. A run with a routing spans several, and each operation names its own.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="manufacturing.workcentre",
            ),
        ),
        migrations.AddConstraint(
            model_name="workcentre",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("available_hours_per_day__gt", 0),
                    ("available_hours_per_day__lte", 24),
                ),
                name="work_centre_hours_in_a_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="workcentre",
            constraint=models.CheckConstraint(
                condition=models.Q(("days_per_week__gt", 0), ("days_per_week__lte", 7)),
                name="work_centre_days_in_a_week",
            ),
        ),
        migrations.AddField(
            model_name="routing",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="routing",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="routing",
            field=models.ForeignKey(
                blank=True,
                help_text="The machines this passes through. Named here rather than on the bill of materials, because a computed bill refuses to be edited and the routing is part of how the product is made — so the specification carries it in like everything else.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_specifications",
                to="manufacturing.routing",
            ),
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="routing",
            field=models.ForeignKey(
                blank=True,
                help_text="How the thing is made, as against what it is made of. Here rather than on the work order because it is a property of the product: every run of it passes the same machines.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boms",
                to="manufacturing.routing",
            ),
        ),
        migrations.AddField(
            model_name="fabricspecification",
            name="routing",
            field=models.ForeignKey(
                blank=True,
                help_text="The machines this passes through. Named here rather than on the bill of materials, because a computed bill refuses to be edited and the routing is part of how the product is made — so the specification carries it in like everything else.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_specifications",
                to="manufacturing.routing",
            ),
        ),
        migrations.AddField(
            model_name="tapespecification",
            name="routing",
            field=models.ForeignKey(
                blank=True,
                help_text="The machines this passes through. Named here rather than on the bill of materials, because a computed bill refuses to be edited and the routing is part of how the product is made — so the specification carries it in like everything else.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_specifications",
                to="manufacturing.routing",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="routing",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Copied off the bill of materials at release and frozen there, like everything else about a released run.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="manufacturing.routing",
            ),
        ),
        migrations.AddField(
            model_name="routingoperation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="routingoperation",
            name="routing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="manufacturing.routing",
            ),
        ),
        migrations.AddField(
            model_name="routingoperation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="routingoperation",
            name="work_centre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="manufacturing.workcentre",
            ),
        ),
        migrations.AddField(
            model_name="workorderoperation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workorderoperation",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workorderoperation",
            name="work_centre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_order_operations",
                to="manufacturing.workcentre",
            ),
        ),
        migrations.AddField(
            model_name="workorderoperation",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operations",
                to="manufacturing.workorder",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingoperation",
            constraint=models.UniqueConstraint(
                fields=("routing", "sequence"),
                name="one_operation_per_routing_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("setup_minutes__gte", 0)),
                name="setup_minutes_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("units_per_hour__isnull", True),
                    ("units_per_hour__gt", 0),
                    _connector="OR",
                ),
                name="operation_rate_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderoperation",
            constraint=models.UniqueConstraint(
                fields=("work_order", "sequence"),
                name="one_work_order_operation_per_sequence",
            ),
        ),
    ]
