# Generated by Django 5.2.17 on 2026-09-21 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("manufacturing", "0005_routing_routingoperation_workorderoperation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="routingoperation",
            name="rate_uom",
            field=models.ForeignKey(
                blank=True,
                help_text="What the rate counts. Required when a rate is given, and the whole point of it: one routing serves several bills of materials, a kilo is not a sack, and a rate with no unit on it is a number that will one day be read against the wrong one.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.unitofmeasure",
            ),
        ),
        migrations.AlterField(
            model_name="routingoperation",
            name="units_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="The rate for THIS product on THIS machine. Blank falls back to the work centre's nominal rate, which is right for a line that runs everything at the same speed and wrong for one that does not — so it is stated when it differs.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="routingoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("units_per_hour__isnull", True),
                    ("rate_uom__isnull", False),
                    _connector="OR",
                ),
                name="operation_rate_says_what_it_counts",
            ),
        ),
    ]
