# Generated by Django 5.2.17 on 2026-09-21 16:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accountingperiod"),
        ("core", "0016_company_net_pay_account"),
        ("manufacturing", "0006_routingoperation_rate_uom_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingsettings",
            name="conversion_absorbed_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Credited when machine time is charged to a run. A contra account against the power, wages and depreciation posted elsewhere: its balance is what the plant over- or under-absorbed, which is the question 'did the machines run as many hours as we costed them at'.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="manufacturingsettings",
            name="conversion_variance_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Where a run's time overrun lands at close, kept apart from the material variance. A blend that ran heavy and a loom that ran slow are different problems with different owners, and one number for both names neither.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="workcentre",
            name="labour_rate_per_hour",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="The crew this machine needs, an hour. A rate rather than a headcount: one operator minding four looms costs a quarter of themselves to each.",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="workcentre",
            name="machine_rate_per_hour",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Power and depreciation an hour. Twelve looms drawing three phase all night is not a rounding error on a sack.",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="workcentre",
            name="overhead_rate_per_hour",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="Everything else the hour carries — supervision, the building, maintenance. Three rates rather than one because a plant manager argues about them separately.",
                max_digits=18,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="planned_conversion_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                editable=False,
                help_text="The machine-time side of the plan, frozen. Kept apart so the close can tell a blend that ran heavy from a loom that ran slow.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="workcentre",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("machine_rate_per_hour__gte", 0),
                    ("labour_rate_per_hour__gte", 0),
                    ("overhead_rate_per_hour__gte", 0),
                ),
                name="work_centre_rates_not_negative",
            ),
        ),
    ]
