# Generated by Django 5.2.17 on 2026-09-22 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accountingperiod"),
        (
            "manufacturing",
            "0007_manufacturingsettings_conversion_absorbed_account_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("booking_date", models.DateField()),
                (
                    "minutes",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Time on the machine, setup included. Always positive: a booking made in error is voided, not negated.",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity_completed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="What came off this operation in that time, in the run's own unit. Blank where the shift did not count it.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("memo", models.CharField(blank=True, max_length=255)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        editable=False,
                        help_text="What the machine cost an hour when this posted, frozen here. A work centre re-rated in April must not re-price a shift that ran in March.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("posted", models.BooleanField(default=False)),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "posted_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        editable=False,
                        help_text="What this put into work in progress, frozen when it posted.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        help_text="Which of the run's operations ran. Its work centre is what sets the rate, so a booking cannot be made against a machine this run never went near.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="manufacturing.workorderoperation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_bookings",
                        to="manufacturing.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-booking_date", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("number", ""), _negated=True),
                        fields=("number",),
                        name="time_booking_number_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minutes__gt", 0)),
                        name="time_booking_minutes_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quantity_completed__isnull", True),
                            ("quantity_completed__gte", 0),
                            _connector="OR",
                        ),
                        name="time_booking_quantity_not_negative",
                    ),
                ],
            },
        ),
    ]
