# Generated by Django 5.2.17 on 2026-09-22 04:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0008_timebooking"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="time_allowance_percent",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("50"),
                help_text="How far past its planned time an operation may be booked. Wide on purpose — a breakdown, a bad batch of polymer or a new crew all cost real hours and none of them is an error. Forty-two times the plan is a typed zero, and it had put three hundred and sixty thousand rupees into work in progress.",
                max_digits=6,
            ),
        ),
    ]
