# Generated by Django 5.2.17 on 2026-09-22 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0009_workorder_time_allowance_percent"),
        ("sales", "0029_deliveryline_reverses_line"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="sales_order_line",
            field=models.ForeignKey(
                blank=True,
                help_text="The customer order this run is for, when it is one. The pointer is here rather than on the sales line because a make-to-order run is meaningless without the order and the order is perfectly meaningful without the run — and it keeps sales from having to know that manufacturing exists.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="sales.salesorderline",
            ),
        ),
    ]
