# Generated by Django 5.2.17 on 2026-09-22 08:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_timesheet_timesheetentry_and_more"),
        ("manufacturing", "0010_workorder_sales_order_line"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="timebooking",
            name="operators",
            field=models.ManyToManyField(
                blank=True,
                help_text="Who was on the machine. For attribution, not for costing: the labour in the cost comes from the work centre's rate, and adding these people's wages on top would charge the run twice for the same crew.",
                related_name="time_bookings",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="timebooking",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Wall clock when the machine started. Given, it decides both which shift this was and which day that shift belongs to, so nobody has to work out the night shift's date by hand.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="timebooking",
            name="booking_date",
            field=models.DateField(
                help_text="The day the shift is NAMED for, not the day the clock said. A night shift running to six in the morning books all its hours to the day before, or half a crew's work lands on the wrong day and two shifts both look wrong. Derived from `started_at` when that is given."
            ),
        ),
        migrations.CreateModel(
            name="DowntimeReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "is_planned",
                    models.BooleanField(
                        default=False,
                        help_text="A changeover, a scheduled service, a shutdown somebody chose. A warp break is not planned; a colour change is.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "starts_at",
                    models.TimeField(
                        help_text="Clock time the shift begins. Wall clock, not a duration from midnight: this is the number stuck on the noticeboard."
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("8"),
                        help_text="How long it runs. Eight for three shifts, twelve for two.",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at", "code"],
            },
        ),
        migrations.CreateModel(
            name="Downtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                (
                    "shift_date",
                    models.DateField(
                        help_text="The day the shift is named for. A stoppage at two in the morning belongs to the night shift of the day before."
                    ),
                ),
                ("minutes", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="downtime",
                        to="manufacturing.workcentre",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        help_text="The run that was on the machine, where there was one. A changeover between two runs belongs to neither.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="downtime",
                        to="manufacturing.workorder",
                    ),
                ),
                (
                    "reason",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="downtime",
                        to="manufacturing.downtimereason",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="downtime",
                        to="manufacturing.shift",
                    ),
                ),
            ],
            options={
                "ordering": ["-shift_date", "work_centre", "id"],
            },
        ),
        migrations.AddField(
            model_name="timebooking",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                help_text="Which crew's slot. A plant that does not run shifts leaves it empty and loses nothing but the by-shift reports.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time_bookings",
                to="manufacturing.shift",
            ),
        ),
        migrations.AddConstraint(
            model_name="shift",
            constraint=models.CheckConstraint(
                condition=models.Q(("hours__gt", 0), ("hours__lte", 24)),
                name="shift_hours_in_a_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="downtime",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="downtime_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="downtime",
            constraint=models.CheckConstraint(
                condition=models.Q(("minutes__gt", 0)), name="downtime_minutes_positive"
            ),
        ),
    ]
