# Generated by Django 5.2.17 on 2026-09-22 09:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0011_timebooking_operators_timebooking_started_at_and_more"),
        ("quality", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bagspecification",
            name="inspection_plan",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_specification",
                to="quality.inspectionplan",
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="weight_tolerance_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5"),
                help_text="How far a finished sack may be from its computed weight. The number a customer's own goods-in scale argues about.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="fabricspecification",
            name="inspection_plan",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_specification",
                to="quality.inspectionplan",
            ),
        ),
        migrations.AddField(
            model_name="tapespecification",
            name="denier_tolerance_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5"),
                help_text="How far the tape may be from its denier before a batch of it is out of specification. What the inspection plan generated from this uses.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="tapespecification",
            name="inspection_plan",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_specification",
                to="quality.inspectionplan",
            ),
        ),
    ]
