# Generated by Django 5.2.17 on 2026-09-22 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("manufacturing", "0012_bagspecification_inspection_plan_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="workcentre",
            name="work_centre_days_in_a_week",
        ),
        migrations.RemoveField(
            model_name="workcentre",
            name="days_per_week",
        ),
        migrations.AddField(
            model_name="workcentre",
            name="holiday_region",
            field=models.CharField(
                blank=True,
                help_text="Which public holiday list applies here. Blank takes the company-wide one only.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="workcentre",
            name="working_days",
            field=models.CharField(
                default="1234567",
                help_text="Which days this machine runs, as ISO weekday numbers — 1 for Monday through 7 for Sunday. '1234567' is a continuous line; '123456' is six days; '12345' is weekdays.",
                max_length=7,
            ),
        ),
        migrations.AddConstraint(
            model_name="workcentre",
            constraint=models.CheckConstraint(
                condition=models.Q(("working_days", ""), _negated=True),
                name="work_centre_works_some_day",
            ),
        ),
    ]
