# Generated by Django 5.2.17 on 2026-09-22 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0013_remove_workcentre_work_centre_days_in_a_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billofmaterials",
            name="backflush",
            field=models.BooleanField(
                default=False,
                help_text="Draw the components automatically when output is booked, rather than on a separate issue. Right for a continuous line where the material is metered in and nobody stands at a store counter; wrong where a storeman weighs out a blend and the difference between what was asked for and what went in is the number the plant manages.",
            ),
        ),
        migrations.AddField(
            model_name="productionentry",
            name="backflush_issue",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The issue this entry drew for itself, on a run that backflushes. Recorded rather than recomputed, because voiding this entry has to put back exactly what it took and the requirement will have moved by then.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="backflushed_by",
                to="manufacturing.materialissue",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="backflush",
            field=models.BooleanField(
                default=False,
                help_text="Frozen off the bill of materials at release. Whether output draws its own components, or a storeman issues them.",
            ),
        ),
    ]
