# Generated by Django 5.2.17 on 2026-09-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_stockvaluationsnapshot"),
        ("manufacturing", "0014_billofmaterials_backflush_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billofmaterials",
            name="is_rework",
            field=models.BooleanField(
                default=False,
                help_text="This recipe puts a failed batch back through the plant. It consumes the item it makes — a roll that missed its GSM is re-wound into a roll that meets it — plus whatever fresh material and machine time the second pass costs.",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="rework_of",
            field=models.ForeignKey(
                blank=True,
                help_text="The batch this run is putting right. Required on a rework recipe and refused on any other: rework is always of a particular roll that a particular inspection failed, and a rework order that does not say which is a licence to draw good stock and call it salvage.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rework_orders",
                to="inventory.lot",
            ),
        ),
    ]
