# Generated by Django 5.2.17 on 2026-09-22 17:56

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_stockvaluationsnapshot"),
        ("manufacturing", "0015_billofmaterials_is_rework_workorder_rework_of"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FabricRoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "width_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Lay-flat width as wound, in millimetres. The tube's own width, not twice it: the doubling is the weave's business.",
                        max_digits=10,
                    ),
                ),
                (
                    "length_m",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Running metres off the loom's counter.",
                        max_digits=12,
                    ),
                ),
                (
                    "net_weight_kg",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="What the scale said, core excluded.",
                        max_digits=12,
                    ),
                ),
                (
                    "core_weight_kg",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0"),
                        help_text="The tube it is wound on. Recorded so that a gross weight off the floor scale can be reconciled to the net one the ledger holds.",
                        max_digits=12,
                    ),
                ),
                (
                    "is_tubular",
                    models.BooleanField(
                        default=True,
                        help_text="A tube laid flat is two thicknesses of fabric and a square metre of it weighs twice what the GSM says. Getting this wrong halves or doubles every grammage the plant reads.",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        blank=True,
                        help_text="The booking that wound it, where there is one.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rolls",
                        to="manufacturing.productionentry",
                    ),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        help_text="The batch this roll is. One roll, one batch — a roll is the unit the plant moves, cuts and traces.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fabric_roll",
                        to="inventory.lot",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        blank=True,
                        help_text="What it was meant to be, for reading the measurements against. A roll with no specification is still a roll; it simply has nothing to be heavy or light against.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rolls",
                        to="manufacturing.fabricspecification",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["lot__item", "lot__code"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("width_mm__gt", 0),
                            ("length_m__gt", 0),
                            ("net_weight_kg__gt", 0),
                        ),
                        name="fabric_roll_is_a_real_roll",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("core_weight_kg__gte", 0)),
                        name="fabric_roll_core_not_negative",
                    ),
                ],
            },
        ),
    ]
