# Generated by Django 5.2.17 on 2026-09-22 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("manufacturing", "0016_fabricroll"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "colours",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="How many colours it prints in. One cylinder a colour, so this is also how many cylinders a full set is.",
                    ),
                ),
                (
                    "artwork_reference",
                    models.CharField(
                        blank=True,
                        help_text="Where the approved file lives. A reference rather than the file: this module has no business being a document store.",
                        max_length=255,
                    ),
                ),
                ("approved_on", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who at the customer signed it off.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.party",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Whose artwork it is. A design nobody owns is a design nobody can approve.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="print_designs",
                        to="core.party",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["customer", "code"],
            },
        ),
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cylinder", "Printing cylinder"),
                            ("die", "Cutting die"),
                            ("reed", "Loom reed"),
                            ("screen", "Extruder screen"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "life_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="How much it is good for before it has to be re-engraved or replaced, in `life_uom`. Empty means nobody has said, which is reported rather than treated as unlimited.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("worn", "Worn out"),
                            ("service", "Away for service"),
                            ("retired", "Retired"),
                        ],
                        default="available",
                        max_length=12,
                    ),
                ),
                ("acquired_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        blank=True,
                        help_text="The artwork this cylinder carries. Required on a cylinder and refused on anything else: a cylinder with no design is a cylinder nobody can find when that customer orders, which is the same as not having it.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tools",
                        to="manufacturing.printdesign",
                    ),
                ),
                (
                    "life_uom",
                    models.ForeignKey(
                        blank=True,
                        help_text="What the life is counted in — bags for a cylinder or a die, metres or hours for a reed. Output is converted into this unit, and refused rather than guessed when it will not convert.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_centre",
                    models.ForeignKey(
                        blank=True,
                        help_text="The machine it fits, where it only fits one.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tools",
                        to="manufacturing.workcentre",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "code"],
            },
        ),
        migrations.AddField(
            model_name="workorder",
            name="tools",
            field=models.ManyToManyField(
                blank=True,
                help_text="The cylinders, dies or reeds this run needs. Naming them is what lets the run refuse to start on a worn one, and what puts the wear against the right tool afterwards.",
                related_name="work_orders",
                to="manufacturing.tool",
            ),
        ),
        migrations.CreateModel(
            name="ToolUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="In the tool's own life unit, converted on the way in.",
                        max_digits=18,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tool_usages",
                        to="manufacturing.productionentry",
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="manufacturing.tool",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["entry", "tool"],
            },
        ),
        migrations.AddConstraint(
            model_name="tool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("life_limit__isnull", True), ("life_limit__gt", 0), _connector="OR"
                ),
                name="tool_life_limit_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="tool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("life_limit__isnull", True), ("life_uom__isnull", True)),
                    models.Q(
                        ("life_limit__isnull", False), ("life_uom__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="tool_life_needs_a_unit",
            ),
        ),
        migrations.AddConstraint(
            model_name="toolusage",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="tool_usage_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="toolusage",
            constraint=models.UniqueConstraint(
                fields=("tool", "entry"), name="one_tool_usage_per_entry"
            ),
        ),
    ]
