# Generated by Django 5.2.17 on 2026-09-22 20:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_stockvaluationsnapshot"),
        ("manufacturing", "0017_printdesign_tool_workorder_tools_toolusage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BomSubstitute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_per",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        help_text="How much of this stands in for one of the original, in the original's unit. One for one is the common case and the dangerous default: two grades of filler do not load the same.",
                        max_digits=18,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Lower is preferred. The original always wins.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutes",
                        to="manufacturing.bomcomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="substitutes_for",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["component", "priority", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_per__gt", 0)),
                        name="bom_substitute_ratio_positive",
                    ),
                    models.UniqueConstraint(
                        fields=("component", "item"),
                        name="one_substitute_per_component_item",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkOrderSubstitute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_per",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("1"), max_digits=18
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=1)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="substitutes",
                        to="manufacturing.workordercomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["component", "priority", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity_per__gt", 0)),
                        name="work_order_substitute_ratio_positive",
                    ),
                    models.UniqueConstraint(
                        fields=("component", "item"),
                        name="one_work_order_substitute_per_component_item",
                    ),
                ],
            },
        ),
    ]
