# Generated by Django 5.2.17 on 2026-09-22 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0018_bomsubstitute_workordersubstitute"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "every_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Calendar days between services. A gearbox is done every ninety days whether or not the machine ran.",
                        null=True,
                    ),
                ),
                (
                    "every_run_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Running hours between services, read off the time bookings. A shuttle is changed every five hundred hours whether that takes a month or a quarter.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "duration_minutes",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="How long the machine is down for it. This is what comes out of the plan's capacity.",
                        max_digits=10,
                    ),
                ),
                (
                    "last_done_on",
                    models.DateField(
                        blank=True,
                        help_text="When it was last done. Empty means never, and the first one is due now.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance",
                        to="manufacturing.workcentre",
                    ),
                ),
            ],
            options={
                "ordering": ["work_centre", "name"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_on", models.DateField()),
                (
                    "planned_minutes",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("done_on", models.DateField(blank=True, editable=False, null=True)),
                (
                    "actual_minutes",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        help_text="What it really took, recorded at completion.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "downtime",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="The stoppage this became once it happened, so the hours appear in effectiveness alongside every other stoppage.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance",
                        to="manufacturing.downtime",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="maintenance_jobs",
                        to="manufacturing.workcentre",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="Empty on a one-off — a breakdown repair booked in, which no schedule predicted.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="manufacturing.maintenanceschedule",
                    ),
                ),
            ],
            options={
                "ordering": ["due_on", "work_centre", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="maintenanceschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("duration_minutes__gt", 0)),
                name="maintenance_takes_some_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenanceschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("every_days__isnull", False),
                    ("every_run_hours__isnull", False),
                    _connector="OR",
                ),
                name="maintenance_has_a_clock",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenanceschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("every_days__isnull", True), ("every_days__gt", 0), _connector="OR"
                ),
                name="maintenance_days_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenanceschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("every_run_hours__isnull", True),
                    ("every_run_hours__gt", 0),
                    _connector="OR",
                ),
                name="maintenance_run_hours_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancejob",
            constraint=models.CheckConstraint(
                condition=models.Q(("planned_minutes__gt", 0)),
                name="maintenance_job_takes_some_time",
            ),
        ),
    ]
