# Generated by Django 5.2.17 on 2026-09-22 22:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accountingperiod"),
        ("inventory", "0026_stockvaluationsnapshot"),
        ("manufacturing", "0019_maintenanceschedule_maintenancejob_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="manufacturingsettings",
            name="revaluation_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Where a standard cost change lands. Stock valued at standard is worth quantity times the standard, so publishing a new one changes what every shelf is worth — and that gain or loss has to go somewhere. An asset account that quietly grows is the one place it must not.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.CreateModel(
            name="CostVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "effective_from",
                    models.DateField(
                        help_text="The date this set of prices is meant to apply from. What makes it real is publishing it, not this date."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "published_on",
                    models.DateField(
                        blank=True,
                        editable=False,
                        help_text="The date the revaluation was posted on.",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revaluation_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="What publishing this did to the books. A standard cost change is a revaluation, and a revaluation posts.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "code"],
            },
        ),
        migrations.CreateModel(
            name="StandardCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "material",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Everything that goes in, at this version's prices, per unit of output.",
                        max_digits=18,
                    ),
                ),
                (
                    "conversion",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="Machine time at the work centres' rates.",
                        max_digits=18,
                    ),
                ),
                (
                    "byproduct_credit",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("0"),
                        help_text="What comes off the line with it and is worth something.",
                        max_digits=18,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "is_rolled",
                    models.BooleanField(
                        default=False,
                        help_text="Computed from a bill of materials rather than entered. A bought item's cost is a decision somebody made; a made item's is arithmetic.",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "bom",
                    models.ForeignKey(
                        blank=True,
                        help_text="The recipe it was rolled against, frozen: the recipe will change and this version must not.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.billofmaterials",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standard_costs",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="manufacturing.costversion",
                    ),
                ),
            ],
            options={
                "ordering": ["version", "item__sku"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "item"), name="one_cost_per_item_per_version"
                    )
                ],
            },
        ),
    ]
