# Generated by Django 5.2.17 on 2026-09-23 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("manufacturing", "0020_manufacturingsettings_revaluation_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionentry",
            name="work_centre",
            field=models.ForeignKey(
                blank=True,
                help_text="Which bank this came off, when a run spans more than one.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_entries",
                to="manufacturing.workcentre",
            ),
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "capacity_per_hour",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="What this one does an hour, where it differs from the bank's nominal rate. An older loom at ninety picks a minute against a newer one at a hundred and ten is the reason this is not a property of the bank.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "available_hours_per_day",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hours this machine runs on a day it runs at all. Blank takes the work centre's.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "working_days",
                    models.CharField(
                        blank=True,
                        help_text="Which days this one runs, as ISO weekday numbers. Blank takes the work centre's — which is the usual case, and the exception is the loom kept on days only because there is nobody to mind it at night.",
                        max_length=7,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="A machine that has been sold or scrapped. Inactive takes it out of the bank's capacity from now on and leaves every run it ever made pointing at it.",
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "capacity_uom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.unitofmeasure",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_centre",
                    models.ForeignKey(
                        help_text="The bank this machine belongs to. A routing names the bank; a run names the machine.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="machines",
                        to="manufacturing.workcentre",
                    ),
                ),
            ],
            options={
                "ordering": ["work_centre", "code"],
            },
        ),
        migrations.AddField(
            model_name="downtime",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                help_text="Which machine stopped. Blank where the whole bank did — a power cut takes twelve looms, and splitting it across twelve rows invents a precision nobody measured.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="downtime",
                to="manufacturing.machine",
            ),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                help_text="The loom this came off. On the roll rather than on the entry because one entry books a shift's output and a roll is one physical roll off one machine — which is the whole point of weighing it at the loom rather than at the store.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rolls",
                to="manufacturing.machine",
            ),
        ),
        migrations.AddField(
            model_name="maintenancejob",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                help_text="Which machine goes out. Blank takes the bank, which is what a shared compressor does and what a beam change must not.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_jobs",
                to="manufacturing.machine",
            ),
        ),
        migrations.AddField(
            model_name="maintenanceschedule",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                help_text="Which machine this service is for. Blank services the bank as a whole, which is right for a compressor feeding twelve looms and wrong for the looms: a beam change on loom seventeen falls due on loom seventeen's hours, not on the shed's.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="maintenance_schedules",
                to="manufacturing.machine",
            ),
        ),
        migrations.AddField(
            model_name="productionentry",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                help_text="Which machine in that bank made it. Blank where the shed does not book output per machine — the effect is that the bank has a quality figure and its machines do not, which is the truth rather than a gap to be filled in with an average.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="production_entries",
                to="manufacturing.machine",
            ),
        ),
        migrations.AddField(
            model_name="timebooking",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                help_text="Which machine in the bank actually ran it. Taken from the operation's assignment when the booking does not say, and recorded on the booking rather than read back through the operation because a run moved to another loom mid-way is a run whose first shift still happened on the first loom.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time_bookings",
                to="manufacturing.machine",
            ),
        ),
        migrations.AddField(
            model_name="workorderoperation",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                help_text="Which machine in the bank this run was put on, where the planner said. Blank is the honest answer for a bank whose machines are interchangeable and where the shift decides on the day; the booking records what actually ran it.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_order_operations",
                to="manufacturing.machine",
            ),
        ),
        migrations.AddConstraint(
            model_name="machine",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("available_hours_per_day__isnull", True),
                    models.Q(
                        ("available_hours_per_day__gt", 0),
                        ("available_hours_per_day__lte", 24),
                    ),
                    _connector="OR",
                ),
                name="machine_hours_in_a_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="machine",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capacity_per_hour__isnull", True),
                    ("capacity_per_hour__gt", 0),
                    _connector="OR",
                ),
                name="machine_rate_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="machine",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("capacity_per_hour__isnull", True),
                    ("capacity_uom__isnull", False),
                    _connector="OR",
                ),
                name="machine_rate_says_what_it_counts",
            ),
        ),
    ]
