# Generated by Django 5.2.17 on 2026-09-23 03:37

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("inventory", "0026_stockvaluationsnapshot"),
        ("manufacturing", "0021_alter_productionentry_work_centre_machine_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="billofmaterials",
            name="expected_reject_percent",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Percentage of what comes OFF THE MACHINE that is expected to fail inspection. Not the same thing as a component's waste: that is material fed in and lost on the way, this is finished units made and then rejected. A plant that loses three per cent of its bags at the stitching table must START a hundred and three to DELIVER a hundred, and a plan that does not know it is three per cent short on every order it ever promises.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="quantity_to_start",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                editable=False,
                help_text="What must come off the machine to deliver the order, frozen at release in the order's own unit. Frozen, and never recomputed from the bill: the expected reject rate is a number a plant revises, and a run already on the floor would otherwise have its material allowance, its output ceiling and its earned time all move under it after the fact.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="quantity_ordered",
            field=models.DecimalField(
                decimal_places=4,
                help_text="What this run is to DELIVER. Where the bill expects to reject some of what it makes, more than this comes off the machine — see `quantity_to_start`.",
                max_digits=18,
            ),
        ),
        migrations.AddConstraint(
            model_name="billofmaterials",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expected_reject_percent__gte", 0),
                    ("expected_reject_percent__lt", 100),
                ),
                name="bom_reject_under_one_hundred",
            ),
        ),
    ]
