# Generated by Django 5.2.17 on 2026-09-26 20:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accountingperiod"),
        ("core", "0016_company_net_pay_account"),
        ("manufacturing", "0022_billofmaterials_expected_reject_percent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutsideMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("movement_date", models.DateField()),
                (
                    "is_return",
                    models.BooleanField(
                        default=False,
                        help_text="Sent back to the vendor. Takes the value back out of the run at what it went in at.",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="In the run's own unit. Always positive; `is_return` says which way.",
                        max_digits=18,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="What this movement is worth — the agreed price times the quantity, for a receipt.",
                        max_digits=18,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=64)),
                ("posted", models.BooleanField(default=False)),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "posted_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        editable=False,
                        help_text="Signed: what this put into work in progress, negative for a return. Frozen as the journal has it.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["movement_date", "id"],
            },
        ),
        migrations.AddField(
            model_name="routingoperation",
            name="is_outside",
            field=models.BooleanField(
                default=False,
                help_text="A vendor does this step. It takes the vendor's lead time and charge instead of our machine time.",
            ),
        ),
        migrations.AddField(
            model_name="routingoperation",
            name="outside_cost_per_unit",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="The standard charge per unit of `rate_uom`. What the plan and the standard cost use; what the vendor actually charges arrives on the purchase order, and the difference is a variance rather than a correction to this.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="routingoperation",
            name="outside_lead_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Days the work is away, door to door — in the world's days rather than this plant's working days, because the vendor keeps their own calendar.",
            ),
        ),
        migrations.AddField(
            model_name="workorderoperation",
            name="is_outside",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="workorderoperation",
            name="outside_lead_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="workorderoperation",
            name="planned_outside_cost",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0"),
                help_text="The vendor's standard charge for the whole run, frozen at release. What the run is credited with as its output comes off; what the vendor actually charged arrives through the goods receipt.",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="routingoperation",
            name="work_centre",
            field=models.ForeignKey(
                blank=True,
                help_text="The machine. Blank exactly when the step is done outside.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="manufacturing.workcentre",
            ),
        ),
        migrations.AlterField(
            model_name="workorderoperation",
            name="units_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Blank for an outside step, which has no rate on our machines. The rate this run was planned at, resolved at release — the operation's own, or the machine's nominal one where the operation did not say. Resolved rather than looked up again, so a machine re-rated next month does not re-time a run that has already happened.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workorderoperation",
            name="work_centre",
            field=models.ForeignKey(
                blank=True,
                help_text="Blank exactly when the step is done outside.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_order_operations",
                to="manufacturing.workcentre",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_outside", False),
                        ("work_centre__isnull", False),
                        ("outside_lead_days", 0),
                        ("outside_cost_per_unit__isnull", True),
                    ),
                    models.Q(
                        ("is_outside", True),
                        ("work_centre__isnull", True),
                        ("units_per_hour__isnull", True),
                        ("setup_minutes", 0),
                    ),
                    _connector="OR",
                ),
                name="operation_is_inside_or_outside",
            ),
        ),
        migrations.AddConstraint(
            model_name="routingoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("outside_cost_per_unit__isnull", True),
                    models.Q(
                        ("outside_cost_per_unit__gte", 0), ("rate_uom__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="outside_charge_says_what_it_counts",
            ),
        ),
        migrations.AddConstraint(
            model_name="workorderoperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("is_outside", False),
                        ("work_centre__isnull", False),
                        ("units_per_hour__isnull", False),
                    ),
                    models.Q(
                        ("is_outside", True),
                        ("work_centre__isnull", True),
                        ("units_per_hour__isnull", True),
                        ("machine__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="work_order_operation_is_inside_or_outside",
            ),
        ),
        migrations.AddField(
            model_name="outsidemovement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="outsidemovement",
            name="credit_account",
            field=models.ForeignKey(
                help_text="The accrual the other side of the entry lands in. Passed in by whoever raised the movement, because it is theirs: goods received not invoiced, for a purchase order.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="outsidemovement",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="outsidemovement",
            name="operation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outside_movements",
                to="manufacturing.workorderoperation",
            ),
        ),
        migrations.AddField(
            model_name="outsidemovement",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="outsidemovement",
            name="voided_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddConstraint(
            model_name="outsidemovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="outside_movement_moves_something",
            ),
        ),
        migrations.AddConstraint(
            model_name="outsidemovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", 0)),
                name="outside_movement_value_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="outsidemovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="outside_movement_number_unique",
            ),
        ),
    ]
