# Generated by Django 5.2.17 on 2026-09-26 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("inventory", "0026_stockvaluationsnapshot"),
        ("manufacturing", "0023_outsidemovement_routingoperation_is_outside_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="billofmaterials",
            name="one_default_bom_per_item",
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="valid_from",
            field=models.DateField(
                blank=True,
                help_text="The first date output made to this specification is due.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="valid_to",
            field=models.DateField(
                blank=True,
                help_text="The last date output made to this specification is due.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="is_phantom",
            field=models.BooleanField(
                default=False,
                help_text="Never made or stocked on its own: a run that needs it draws its components directly. For an intermediate that exists for a few metres between two machines on one run and is never put on a shelf — and whose separate run, stock movement and work in progress would be bookkeeping about nothing.",
            ),
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="valid_from",
            field=models.DateField(
                blank=True,
                help_text="The first date output made to this recipe is DUE. Blank is from the beginning. Read against when the output is wanted rather than when the run is released, because that is what a specification change means in this plant — sacks delivered from the first of the month are made the new way — and because the release date depends on the lead time, which depends on which recipe's routing is used: asking by release date would be a question that needs its own answer first.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="billofmaterials",
            name="valid_to",
            field=models.DateField(
                blank=True,
                help_text="The last date output made to this recipe is due. Blank is open-ended.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fabricspecification",
            name="valid_from",
            field=models.DateField(
                blank=True,
                help_text="The first date output made to this specification is due.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fabricspecification",
            name="valid_to",
            field=models.DateField(
                blank=True,
                help_text="The last date output made to this specification is due.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tapespecification",
            name="valid_from",
            field=models.DateField(
                blank=True,
                help_text="The first date output made to this specification is due.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tapespecification",
            name="valid_to",
            field=models.DateField(
                blank=True,
                help_text="The last date output made to this specification is due.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="billofmaterials",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_active", True),
                    ("is_default", True),
                    ("valid_to__isnull", True),
                ),
                fields=("item",),
                name="one_open_ended_default_bom_per_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="billofmaterials",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_active", True),
                    ("is_default", True),
                    ("valid_from__isnull", True),
                ),
                fields=("item",),
                name="one_unstarted_default_bom_per_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="billofmaterials",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="bom_window_runs_forwards",
            ),
        ),
        migrations.AddConstraint(
            model_name="billofmaterials",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_phantom", False),
                    models.Q(("routing__isnull", True), ("is_rework", False)),
                    _connector="OR",
                ),
                name="phantom_has_no_run_of_its_own",
            ),
        ),
    ]
