# Generated by Django 5.2.17 on 2026-09-26 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_stockvaluationsnapshot"),
        (
            "manufacturing",
            "0024_remove_billofmaterials_one_default_bom_per_item_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeoverRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_family", models.CharField(blank=True, max_length=32)),
                ("to_family", models.CharField(blank=True, max_length=32)),
                ("minutes", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changeover_rules",
                        to="manufacturing.workcentre",
                    ),
                ),
            ],
            options={
                "ordering": ["work_centre", "from_family", "to_family"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("work_centre", "from_family", "to_family"),
                        name="one_changeover_rule_per_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("minutes__gte", 0)),
                        name="changeover_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_family", ""),
                            ("to_family", ""),
                            models.Q(
                                ("from_family", models.F("to_family")), _negated=True
                            ),
                            _connector="OR",
                        ),
                        name="changeover_is_between_two_families",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SetupFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family",
                    models.CharField(
                        help_text="What this machine has to be changed for — 'WHITE-2C' on a press, '1000D-NATURAL' on an extruder. Items in one family follow each other here with no changeover.",
                        max_length=32,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="setup_families",
                        to="manufacturing.workcentre",
                    ),
                ),
            ],
            options={
                "ordering": ["work_centre", "family", "item"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "work_centre"),
                        name="one_setup_family_per_item_and_centre",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("family", ""), _negated=True),
                        name="setup_family_is_named",
                    ),
                ],
            },
        ),
    ]
