# Generated by Django 5.2.17 on 2026-09-27 12:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("hr", "0007_employee_pin_digest"),
        ("inventory", "0027_item_hsn_code"),
        ("manufacturing", "0025_changeoverrule_setupfamily"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField()),
                ("succeeded", models.BooleanField()),
            ],
            options={
                "ordering": ["-at"],
            },
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roll_overrides_approved",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="is_metres_exception",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="metres_from_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="What the net weight supports at the specification's GSM, frozen when it was weighed.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="metres_tolerance_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="The limit the station held it to, frozen: a tolerance changed next month does not re-judge this roll.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="metres_variance_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Declared metres against weight-derived, as a percentage.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="override_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="override_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scale_offline", "Scale not connected"),
                    ("calibration", "Scale under calibration"),
                    ("does_not_fit", "Roll does not fit platform"),
                    ("other", "Other"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="manufacturing.shift",
            ),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="shift_date",
            field=models.DateField(
                blank=True,
                help_text="The shift-day, not the calendar day: two in the morning is the night shift of the day before.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="weighed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="weighed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who put it on the scale, from their own PIN. Every roll names a person, so a shared login is never the answer.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rolls_weighed",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="weight_source",
            field=models.CharField(
                blank=True,
                choices=[("scale", "Scale"), ("manual", "Manual, supervisor-approved")],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                help_text="The in-premises contractor who runs this machine, where one does. Their declared output is checked against what the scale says it can have been.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operated_machines",
                to="core.party",
            ),
        ),
        migrations.CreateModel(
            name="CoreType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=128)),
                ("tare_kg", models.DecimalField(decimal_places=3, max_digits=8)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="core_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="manufacturing.coretype",
            ),
        ),
        migrations.CreateModel(
            name="LoomStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("scale_code", models.CharField(blank=True, max_length=32)),
                ("printer_code", models.CharField(blank=True, max_length=32)),
                (
                    "metres_tolerance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        help_text="How far declared metres may sit from what the weight supports before the roll is an exception.",
                        max_digits=5,
                    ),
                ),
                (
                    "unaccounted_threshold_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.50"),
                        help_text="Tape unaccounted for, as a share of tape consumed, above which the morning report flags it.",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machines",
                    models.ManyToManyField(
                        help_text="The looms this station weighs for.",
                        related_name="stations",
                        to="manufacturing.machine",
                    ),
                ),
                (
                    "supervisors",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Who may approve a typed weight here.",
                        related_name="supervised_stations",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        help_text="Where rolls weighed here go into stock.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "permissions": [("weigh_at_station", "Can run a loom exit station")],
            },
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rolls",
                to="manufacturing.loomstation",
            ),
        ),
        migrations.AddConstraint(
            model_name="fabricroll",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("weight_source", "manual"), _negated=True),
                    models.Q(
                        ("approved_by__isnull", False),
                        models.Q(("override_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="fabric_roll_manual_weight_is_approved",
            ),
        ),
        migrations.AddField(
            model_name="stationattempt",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="manufacturing.loomstation",
            ),
        ),
        migrations.AddConstraint(
            model_name="coretype",
            constraint=models.CheckConstraint(
                condition=models.Q(("tare_kg__gte", 0)), name="core_tare_not_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="loomstation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("metres_tolerance_percent__gt", 0),
                    ("unaccounted_threshold_percent__gt", 0),
                ),
                name="station_limits_positive",
            ),
        ),
    ]
