# Generated by Django 5.2.17 on 2026-09-27 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("hr", "0007_employee_pin_digest"),
        ("manufacturing", "0026_loom_station"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="materialissue",
            name="contractor",
            field=models.ForeignKey(
                blank=True,
                help_text="Whose looms the material went to, where a contractor runs them: the tape they are then accountable for.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.party",
            ),
        ),
        migrations.CreateModel(
            name="LoomWaste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shift_date", models.DateField()),
                ("kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("weighed_at", models.DateTimeField()),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.party",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="waste",
                        to="manufacturing.loomstation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weighed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-weighed_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("kg__gt", 0)), name="loom_waste_positive"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TapeCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shift_date", models.DateField()),
                ("kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("counted_at", models.DateTimeField()),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.party",
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tape_counts",
                        to="manufacturing.loomstation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-shift_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("station", "contractor", "shift_date"),
                        name="one_tape_count_per_contractor_per_day",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kg__gte", 0)),
                        name="tape_count_not_negative",
                    ),
                ],
            },
        ),
    ]
