# Generated by Django 5.2.17 on 2026-09-27 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("manufacturing", "0027_tape_balance"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobWorkChallan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("challan_date", models.DateField()),
                ("vehicle", models.CharField(blank=True, max_length=32)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "job_worker_gstin",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="As it stood when the challan was issued.",
                        max_length=15,
                    ),
                ),
                (
                    "job_worker_state",
                    models.CharField(blank=True, editable=False, max_length=2),
                ),
                ("posted", models.BooleanField(default=False)),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_work_challans",
                        to="core.party",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["challan_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="JobWorkLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(max_length=255)),
                ("hsn_code", models.CharField(max_length=8)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="In the run's own unit, the unit the vendor's returns are counted in.",
                        max_digits=18,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The taxable value the challan declares. Not posted anywhere: the goods are in work in progress already.",
                        max_digits=18,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The GST rate the goods would bear if supplied — reported on ITC-04, though none is charged.",
                        max_digits=5,
                    ),
                ),
                (
                    "is_capital_goods",
                    models.BooleanField(
                        default=False,
                        help_text="Capital goods have three years to come back; inputs have one.",
                    ),
                ),
                (
                    "challan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="manufacturing.jobworkchallan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        help_text="The outside step the goods go out for.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="challan_lines",
                        to="manufacturing.workorderoperation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["challan", "id"],
            },
        ),
        migrations.CreateModel(
            name="JobWorkLoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("loss_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="losses",
                        to="manufacturing.jobworkline",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["loss_date", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="jobworkchallan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="job_work_challan_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobworkline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity__gt", 0), ("value__gte", 0), ("tax_rate__gte", 0)
                ),
                name="job_work_line_sensible",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobworkloss",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="job_work_loss_positive"
            ),
        ),
    ]
