# Generated by Django 5.2.17 on 2026-09-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0028_job_work_challans"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorderoperation",
            name="planned_finish",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workorderoperation",
            name="planned_start",
            field=models.DateTimeField(
                blank=True,
                help_text="When the committed schedule has it starting — a plan, rewritten each time the dispatcher commits one.",
                null=True,
            ),
        ),
    ]
