# Generated by Django 5.2.17 on 2026-09-27 18:26

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_item_hsn_code"),
        ("manufacturing", "0029_operation_schedule"),
        ("quality", "0003_remove_inspectionplan_one_active_plan_per_item_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bagspecification",
            name="bopp_faces",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "One face (SS)"), (2, "Both faces (BS)")],
                default=2,
                help_text="Film laminated on one face of the flattened tube or on both.",
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="bopp_film_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Printed BOPP film laminated over the fabric. It is bonded by the extruded coating, so a BOPP sack is also laminated.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="bopp_micron",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Film thickness; 18 to 25 is usual. Covers the whole outer fabric area.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="bopp_waste_percent",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("4"),
                help_text="Of the film fed in: registration, trim and splices.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="closure",
            field=models.CharField(
                choices=[("sewn", "Sewn"), ("welded", "Welded (block bottom)")],
                default="sewn",
                help_text="Sewn with thread, or folded into a block bottom and welded with hot air, as valve sacks for cement are. A welded sack has no thread and must be coated: the coating is what melts.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="cover_patch_grams",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Both ends together.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="cover_patch_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The cover sheets welded over a block bottom's folds.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="gusset_cm",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="How deep each side's gusset folds in. A 28-inch sack with 2-inch gussets is a 28-inch tube with a 24-inch printed face: the gusset moves fabric from the face to the side, and adds none.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="liner_length_cm",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="liner_micron",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Liner film thickness, to compute its weight from its size.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="liner_width_cm",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="valve_patch_grams",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="valve_patch_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The valve a valve sack is filled through.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.item",
            ),
        ),
        migrations.AlterField(
            model_name="bagspecification",
            name="bag_width_cm",
            field=models.DecimalField(
                decimal_places=2,
                help_text="The finished sack's width, which is the fabric's lay-flat width: the tube is woven at the width of the bag it becomes. On a gusseted sack this is the whole width, gussets folded inside it, the way the trade quotes it.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="bagspecification",
            name="liner_grams_per_bag",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Typed, where the liner is bought or weighed as a finished piece. Leave at nought to compute it from the film below.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="bagspecification",
            name="top_hem_cm",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2"),
                help_text="Fabric folded at the mouth, hemmed or left raw. On a block-bottom valve sack, the top end's fold allowance.",
                max_digits=6,
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("gusset_cm__gte", 0),
                    ("bopp_micron__gte", 0),
                    ("valve_patch_grams__gte", 0),
                    ("cover_patch_grams__gte", 0),
                    ("liner_micron__gte", 0),
                    ("liner_width_cm__gte", 0),
                    ("liner_length_cm__gte", 0),
                    ("liner_grams_per_bag__gte", 0),
                    ("thread_grams_per_bag__gte", 0),
                ),
                name="bag_quantities_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("bopp_waste_percent__gte", 0), ("bopp_waste_percent__lt", 100)
                ),
                name="bag_film_waste_under_one_hundred",
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("closure__in", ["sewn", "welded"])),
                name="bag_closure_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "bag_width_cm__gt",
                        django.db.models.expressions.CombinedExpression(
                            models.F("gusset_cm"), "*", models.Value(2)
                        ),
                    )
                ),
                name="bag_gussets_leave_a_face",
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("bopp_faces__in", [1, 2])),
                name="bag_bopp_faces_known",
            ),
        ),
    ]
