# Generated by Django 5.2.17 on 2026-09-27 19:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_item_hsn_code"),
        ("manufacturing", "0030_bag_constructions"),
        ("quality", "0003_remove_inspectionplan_one_active_plan_per_item_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bagspecification",
            name="target_grams",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="The weight the customer contracted for. When given, the sack this specification computes must fall within the tolerance of it, and the weight check inspects against it.",
                max_digits=10,
                null=True,
            ),
        ),
        # Fabrics that already exist were weighed with no shrink, and
        # their sacks' bills were built from that weight. They keep it:
        # the column arrives at 0 for them, and only then does the
        # default become the plant's 4% for fabrics specified from now on.
        migrations.AddField(
            model_name="fabricspecification",
            name="shrink_percent",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=5),
        ),
        migrations.AlterField(
            model_name="fabricspecification",
            name="shrink_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("4"),
                help_text="How much finer the tape line runs than the fabric weighs. The tape card carries the fabric's denier less this; the tape specification is the line's denier, so the fabric weighs the tapes laid straight divided by (1 - shrink).",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="bagspecification",
            name="weight_tolerance_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("5"),
                help_text="How far a finished sack may be from its contracted weight, or its computed one when none was contracted. The number a customer's own goods-in scale argues about.",
                max_digits=5,
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target_grams__isnull", True),
                    ("target_grams__gt", 0),
                    _connector="OR",
                ),
                name="bag_target_weight_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight_tolerance_percent__gte", 0)),
                name="bag_weight_tolerance_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="fabricspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("shrink_percent__gte", 0), ("shrink_percent__lt", 100)
                ),
                name="fabric_shrink_under_one_hundred",
            ),
        ),
    ]
