# Generated by Django 5.2.17 on 2026-09-27 20:06

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def faces_to_back_colours(apps, schema_editor):
    Bag = apps.get_model("manufacturing", "BagSpecification")
    Bag.objects.filter(printed_faces__gte=2).update(print_colours_back=models.F("print_colours"))
    Bag.objects.filter(printed_faces=0).update(print_colours=0)


def back_colours_to_faces(apps, schema_editor):
    Bag = apps.get_model("manufacturing", "BagSpecification")
    Bag.objects.filter(print_colours_back__gt=0).update(printed_faces=2)
    Bag.objects.filter(print_colours_back=0).update(printed_faces=1)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_item_hsn_code"),
        ("manufacturing", "0031_weight_contract_and_shrink"),
        ("quality", "0003_remove_inspectionplan_one_active_plan_per_item_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bagspecification",
            name="fold_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not stated"),
                    ("SFSS", "Single fold, single stitch"),
                    ("SFDS", "Single fold, double stitch"),
                    ("DFSS", "Double fold, single stitch"),
                    ("DFDS", "Double fold, double stitch"),
                    ("EZWF", "Easy-open with fold"),
                    ("EZWOF", "Easy-open without fold"),
                ],
                default="",
                help_text="How the bottom is folded and stitched. Sets the stitch rows a computed thread is worked from, and offers the fold's fabric allowance when none is given.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="print_colours_back",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Colours printed on the back face; often fewer."
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="reducer_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Thins the ink on the press and evaporates: bought and used, never in the sack.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="reducer_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Of the ink's weight.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="solvent_item",
            field=models.ForeignKey(
                blank=True,
                help_text="MIBK or another press solvent. Like the reducer, used and gone.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="solvent_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Of the ink's weight.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="stitches_per_dm",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("12.5"),
                help_text="Stitch density; more stitches, more thread.",
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="thread_denier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="The sewing yarn's denier, to compute the thread from the seams: each row is the sack's width in chain stitch.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="bagspecification",
            name="ink_grams_per_sqm_per_colour",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.5"),
                help_text="Ink laid down per square metre per colour. Small, and the only reason it is here is that a plant printing four colours on a million sacks is buying ink by the tonne.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="bagspecification",
            name="print_colours",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Colours printed on the front face."
            ),
        ),
        migrations.AlterField(
            model_name="bagspecification",
            name="thread_grams_per_bag",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Sewing thread, typed. Leave at nought to compute it from the thread's denier and the stitch rows.",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="bagspecification",
            name="top_hem_cm",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2"),
                help_text="Fabric folded and hemmed at the mouth, one stitch row; nought for a raw mouth. On a block-bottom valve sack, the top end's fold allowance.",
                max_digits=6,
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("thread_denier__gte", 0),
                    ("stitches_per_dm__gt", 0),
                    ("reducer_percent__gte", 0),
                    ("solvent_percent__gte", 0),
                ),
                name="bag_thread_and_solvents_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "fold_type__in",
                        ["", "SFSS", "SFDS", "DFSS", "DFDS", "EZWF", "EZWOF"],
                    )
                ),
                name="bag_fold_type_known",
            ),
        ),
        # Before the faces go: ink was faces x colours on each face, so two
        # faces of N colours is N on the back too, and a sack printed on
        # no face carried no ink however many colours it named.
        migrations.RunPython(faces_to_back_colours, back_colours_to_faces),
        migrations.RemoveField(
            model_name="bagspecification",
            name="printed_faces",
        ),
    ]
