# Generated by Django 5.2.17 on 2026-09-27 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def single_polymer_to_blend(apps, schema_editor):
    Bag = apps.get_model("manufacturing", "BagSpecification")
    Line = apps.get_model("manufacturing", "BagCoatingLine")
    for bag in Bag.objects.filter(lamination_item__isnull=False):
        Line.objects.create(specification=bag, item_id=bag.lamination_item_id, parts=100)


def blend_to_single_polymer(apps, schema_editor):
    # Going back, a blend can only be named by its largest share.
    Bag = apps.get_model("manufacturing", "BagSpecification")
    Line = apps.get_model("manufacturing", "BagCoatingLine")
    for bag in Bag.objects.all():
        line = Line.objects.filter(specification=bag).order_by("-parts", "id").first()
        if line is not None:
            Bag.objects.filter(pk=bag.pk).update(lamination_item_id=line.item_id)


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_item_hsn_code"),
        ("manufacturing", "0032_fold_thread_colours_solvents"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BagCoatingLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parts",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Relative share by weight: 80 and 20, or 4 and 1.",
                        max_digits=10,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coating_lines",
                        to="manufacturing.bagspecification",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("specification", "item"),
                        name="one_coating_line_per_item",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("parts__gt", 0)),
                        name="coating_parts_positive",
                    ),
                ],
            },
        ),
        # Each laminated sack's one polymer becomes the whole of its blend
        # before the field that named it goes.
        migrations.RunPython(single_polymer_to_blend, blend_to_single_polymer),
        migrations.RemoveField(
            model_name="bagspecification",
            name="lamination_item",
        ),
    ]
