# Generated by Django 5.2.17 on 2026-09-27 21:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_item_hsn_code"),
        ("manufacturing", "0033_coating_blend"),
        ("quality", "0003_remove_inspectionplan_one_active_plan_per_item_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bagspecification",
            name="dcut_area_sqcm",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="The D-cut handle's hole, on one face. It is punched through both, fabric, coating and film with it: bought, cut, and not in the sack.",
                max_digits=8,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="handle_grams",
            field=models.DecimalField(
                decimal_places=3, default=Decimal("0"), max_digits=8
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="handle_item",
            field=models.ForeignKey(
                blank=True,
                help_text="A handle strip or loop sewn to the sack.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="metallic_coverage_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100"),
                help_text="Of the face the film covers: 100 for full metallic, less for a window film with the product showing through.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="metallic_film_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Metallised film on the front face, bonded by the coating.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="metallic_micron",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=6
            ),
        ),
        migrations.AddField(
            model_name="fabricspecification",
            name="is_leno",
            field=models.BooleanField(
                default=False,
                help_text="Open mesh, the warp tapes twisted in pairs around the weft: onion and potato sacks. It weighs what its mesh and denier make like any fabric, and there is nothing to coat.",
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("handle_grams__gte", 0),
                    ("dcut_area_sqcm__gte", 0),
                    ("metallic_micron__gte", 0),
                    ("metallic_coverage_percent__gt", 0),
                    ("metallic_coverage_percent__lte", 100),
                ),
                name="bag_handle_cut_and_metallic_in_range",
            ),
        ),
    ]
