# Generated by Django 5.2.17 on 2026-09-27 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_item_hsn_code"),
        ("manufacturing", "0034_leno_dcut_handle_metallic"),
        ("sales", "0031_recorded_taxes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Sacks in the enquiry.",
                        max_digits=14,
                    ),
                ),
                ("costed_on", models.DateField()),
                ("bag_grams", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "overhead_percent",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("margin_percent", models.DecimalField(decimal_places=2, max_digits=6)),
                ("material", models.DecimalField(decimal_places=6, max_digits=16)),
                ("conversion", models.DecimalField(decimal_places=6, max_digits=16)),
                ("credit", models.DecimalField(decimal_places=6, max_digits=16)),
                ("overhead", models.DecimalField(decimal_places=6, max_digits=16)),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Per sack, overhead included.",
                        max_digits=16,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Per sack, margin included, before rounding.",
                        max_digits=16,
                    ),
                ),
                (
                    "quoted_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What goes on the quotation: the price to the paisa.",
                        max_digits=14,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quotation_line",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cost_sheet",
                        to="sales.quotationline",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cost_sheets",
                        to="manufacturing.bagspecification",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-costed_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CostSheetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("material", "Material"),
                            ("conversion", "Conversion"),
                            ("credit", "By-product credit"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tape", "Tape extrusion"),
                            ("weaving", "Weaving"),
                            ("lamination", "Lamination"),
                            ("printing", "Printing"),
                            ("cutting", "Cutting and stitching"),
                            ("valve", "Valve fixing"),
                            ("dcut", "D-cut punching"),
                            ("handle", "Handle attachment"),
                            ("liner", "Liner insertion"),
                            ("packing", "Bale packing"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Per sack: kilogrammes of material, of by-product, or made by the stage; one for a per-sack operation.",
                        max_digits=16,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=6, help_text="Per sack.", max_digits=16
                    ),
                ),
                (
                    "last_receipt_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="What the item last came in at, beside the rate it was costed at.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="manufacturing.costsheet",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MaterialRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateField()),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Per unit the item is stocked in — per kilogramme for polymer.",
                        max_digits=14,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="material_rates",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["item__sku", "-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="QuotePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateField()),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "overhead_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="On material and conversion together.",
                        max_digits=6,
                    ),
                ),
                (
                    "margin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="On cost, unless a cost sheet is given its own.",
                        max_digits=6,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="StageRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateField()),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("tape", "Tape extrusion"),
                            ("weaving", "Weaving"),
                            ("lamination", "Lamination"),
                            ("printing", "Printing"),
                            ("cutting", "Cutting and stitching"),
                            ("valve", "Valve fixing"),
                            ("dcut", "D-cut punching"),
                            ("handle", "Handle attachment"),
                            ("liner", "Liner insertion"),
                            ("packing", "Bale packing"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Per kilogramme the stage makes, or per sack for the per-sack operations (valve, D-cut, handle, liner, packing).",
                        max_digits=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["stage", "-valid_from"],
            },
        ),
        migrations.AddConstraint(
            model_name="costsheet",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="cost_sheet_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="costsheetline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity__gte", 0), ("rate__gte", 0), ("amount__gte", 0)
                ),
                name="cost_sheet_line_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="materialrate",
            constraint=models.UniqueConstraint(
                fields=("item", "valid_from"), name="one_material_rate_a_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="materialrate",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__gte", 0)), name="material_rate_not_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotepolicy",
            constraint=models.UniqueConstraint(
                fields=("valid_from",), name="one_quote_policy_a_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotepolicy",
            constraint=models.CheckConstraint(
                condition=models.Q(("overhead_percent__gte", 0)),
                name="overhead_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagerate",
            constraint=models.UniqueConstraint(
                fields=("stage", "valid_from"), name="one_stage_rate_a_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="stagerate",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__gte", 0)), name="stage_rate_not_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="stagerate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "stage__in",
                        [
                            "tape",
                            "weaving",
                            "lamination",
                            "printing",
                            "cutting",
                            "valve",
                            "dcut",
                            "handle",
                            "liner",
                            "packing",
                        ],
                    )
                ),
                name="stage_rate_stage_known",
            ),
        ),
    ]
