# Generated by Django 5.2.17 on 2026-09-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0035_quoting"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobworkloss",
            name="voided_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Withdrawn as recorded in error. Kept, and counted nowhere.",
                null=True,
            ),
        ),
    ]
