# Generated by Django 5.2.17 on 2026-09-28 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("hr", "0007_employee_pin_digest"),
        ("manufacturing", "0036_job_work_loss_void"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tapecount",
            name="one_tape_count_per_contractor_per_day",
        ),
        migrations.AddField(
            model_name="loomwaste",
            name="voided_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="loomwaste",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="tapecount",
            name="voided_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="tapecount",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="tapecount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("voided_at__isnull", True)),
                fields=("station", "contractor", "shift_date"),
                name="one_tape_count_per_contractor_per_day",
            ),
        ),
    ]
