# Generated by Django 5.2.17 on 2026-09-28 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        ("manufacturing", "0038_test_certificates"),
    ]

    operations = [
        migrations.AddField(
            model_name="fabricroll",
            name="woven_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The weaver, from their own PIN, where the plant pays by the piece. Not whoever weighed it: at a loom exit station those are different people, and piece work paid to the weigher pays for somebody else's cloth.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rolls_woven",
                to="hr.employee",
            ),
        ),
    ]
