# Generated by Django 5.2.17 on 2026-09-28 05:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        ("manufacturing", "0039_fabricroll_woven_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workcentre",
            name="standard_kwh_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="What an hour of this work centre should draw, for reading the meters against. Blank where nobody has set one.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="EnergyMeter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "multiplier",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1"),
                        help_text="kWh per unit the dial moves. A meter behind current transformers reads a fraction of what passes; its factor is on the meter card.",
                        max_digits=10,
                    ),
                ),
                ("installed_on", models.DateField()),
                (
                    "initial_reading",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("retired_on", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="energy_meters",
                        to="manufacturing.machine",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="energy_meters",
                        to="manufacturing.workcentre",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EnergyTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateField()),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, help_text="Per kWh.", max_digits=10
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shift_date", models.DateField()),
                ("reading", models.DecimalField(decimal_places=3, max_digits=14)),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="manufacturing.energymeter",
                    ),
                ),
                (
                    "read_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.shift",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["meter", "-shift_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="energymeter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("machine__isnull", False), ("work_centre__isnull", True)),
                    models.Q(("machine__isnull", True), ("work_centre__isnull", False)),
                    _connector="OR",
                ),
                name="energy_meter_serves_one_thing",
            ),
        ),
        migrations.AddConstraint(
            model_name="energymeter",
            constraint=models.CheckConstraint(
                condition=models.Q(("multiplier__gt", 0)),
                name="energy_meter_multiplier_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="energymeter",
            constraint=models.CheckConstraint(
                condition=models.Q(("initial_reading__gte", 0)),
                name="energy_meter_initial_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="energymeter",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("retired_on__isnull", True),
                    ("retired_on__gte", models.F("installed_on")),
                    _connector="OR",
                ),
                name="energy_meter_retired_after_installed",
            ),
        ),
        migrations.AddConstraint(
            model_name="energytariff",
            constraint=models.UniqueConstraint(
                fields=("valid_from",), name="one_energy_tariff_a_day"
            ),
        ),
        migrations.AddConstraint(
            model_name="energytariff",
            constraint=models.CheckConstraint(
                condition=models.Q(("rate__gte", 0)), name="energy_tariff_not_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="meterreading",
            constraint=models.UniqueConstraint(
                condition=models.Q(("voided_at__isnull", True)),
                fields=("meter", "shift_date", "shift"),
                name="one_standing_reading_a_shift",
            ),
        ),
    ]
