# Generated by Django 5.2.17 on 2026-09-28 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        (
            "manufacturing",
            "0041_customermaterialreceipt_customermaterialreceiptline_and_more",
        ),
        ("quality", "0003_remove_inspectionplan_one_active_plan_per_item_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BagCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shift_date", models.DateField()),
                ("counted_at", models.DateTimeField()),
                ("bags", models.PositiveIntegerField()),
                (
                    "target_grams",
                    models.DecimalField(
                        decimal_places=3,
                        editable=False,
                        help_text="The weight it was checked against, frozen with the count.",
                        max_digits=10,
                    ),
                ),
                (
                    "sample_mean_grams",
                    models.DecimalField(
                        decimal_places=3, editable=False, max_digits=10
                    ),
                ),
                ("passed", models.BooleanField(editable=False)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bag_count",
                        to="manufacturing.productionentry",
                    ),
                ),
                (
                    "inspection",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bag_count",
                        to="quality.inspection",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bag_counts",
                        to="manufacturing.machine",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bags_counted",
                        to="hr.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.shift",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bag_counts",
                        to="manufacturing.loomstation",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who took an off-weight bundle by concession.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bag_counts",
                        to="manufacturing.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-counted_at", "-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("bags__gt", 0)), name="bag_count_positive"
                    )
                ],
            },
        ),
    ]
