# Generated by Django 5.2.17 on 2026-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0043_bale_baleline_bale_bale_number_unique_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tapespecification",
            name="elongation_max_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="And at most: over-stretchy tape makes a sack that sags.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tapespecification",
            name="elongation_min_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="How far the tape must stretch before it breaks, at least.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tapespecification",
            name="min_tenacity_gpd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The least strength a batch may have, in grammes per denier. Given, every batch is tested for it: filler is cheap and weak, and this is where that shows.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
