# Generated by Django 5.2.17 on 2026-09-28 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_refold_company_wide_valuation"),
        (
            "manufacturing",
            "0045_manufacturingsettings_scrap_needs_reason_scrapreason_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rebatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, editable=False, max_length=32)),
                ("rebatched_on", models.DateField()),
                ("reason", models.CharField(max_length=255)),
                ("posted", models.BooleanField(default=False, editable=False)),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-rebatched_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RebatchLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "side",
                    models.CharField(
                        choices=[("in", "Taken from"), ("out", "Made into")],
                        max_length=3,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="In the item's stocking unit.",
                        max_digits=18,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rebatch_lines",
                        to="inventory.lot",
                    ),
                ),
                (
                    "rebatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="manufacturing.rebatch",
                    ),
                ),
                (
                    "stock_movement",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["rebatch", "side", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="rebatch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="rebatch_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="rebatchline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="rebatch_line_positive"
            ),
        ),
    ]
