# Generated by Django 5.2.17 on 2026-09-28 19:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        (
            "manufacturing",
            "0046_rebatch_rebatchline_rebatch_rebatch_number_unique_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workcentre",
            name="efficiency_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("100"),
                help_text="What the machine really achieves against its rated speed, over a run: breaks, slow starts, speed held below maximum. 600 kg an hour rated at 85 per cent is planned and costed at 510.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="workcentre",
            name="line_speed_m_per_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tape line: winding speed, metres a minute.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workcentre",
            name="loom_rpm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Circular loom: revolutions a minute.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workcentre",
            name="shuttles",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Circular loom: shuttles, each laying one pick a revolution.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workcentre",
            name="speed_basis",
            field=models.CharField(
                choices=[
                    ("stated", "Stated rate"),
                    ("tape_line", "Tape line"),
                    ("circular_loom", "Circular loom"),
                ],
                default="stated",
                help_text="Where its speed comes from: the rate stated here, or worked out from the product and the machine's settings.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="workcentre",
            name="tape_ends",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Tape line: tapes wound at once (the take-up's positions).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workorderoperation",
            name="units_per_hour",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Blank for an outside step, which has no rate on our machines. The machine's rated speed for this run, before its efficiency, which `planned_minutes` allows for and overall equipment effectiveness measures against, resolved at release — the operation's own, or the machine's nominal one where the operation did not say. Resolved rather than looked up again, so a machine re-rated next month does not re-time a run that has already happened.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="workcentre",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("efficiency_percent__gt", 0), ("efficiency_percent__lte", 100)
                ),
                name="work_centre_efficiency_a_percentage",
            ),
        ),
    ]
