# Generated by Django 5.2.17 on 2026-09-28 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        ("manufacturing", "0047_workcentre_efficiency_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="downtime",
            name="booked_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="downtime",
            name="station",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Where it was booked, when it was booked on the floor.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stoppages",
                to="manufacturing.loomstation",
            ),
        ),
        migrations.AddField(
            model_name="downtime",
            name="voided_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="downtime",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="downtime",
            name="voided_reason",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
