# Generated by Django 5.2.17 on 2026-09-28 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        ("inventory", "0030_refold_company_wide_valuation"),
        ("manufacturing", "0049_machineclock"),
        (
            "quality",
            "0005_inspection_lot_size_inspection_sampling_planline_aql_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loomstation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("loom_exit", "Loom exit"),
                    ("conversion", "Cutting and stitching"),
                    ("extrusion", "Tape line"),
                    ("printing", "Printing"),
                    ("coating", "Coating and lamination"),
                ],
                default="loom_exit",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="TapeDoff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gross_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("bobbins", models.PositiveIntegerField()),
                ("net_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("mean_denier", models.DecimalField(decimal_places=2, max_digits=10)),
                ("weighed_at", models.DateTimeField()),
                ("shift_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "conceded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "core_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.coretype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.productionentry",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="quality.inspection",
                    ),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doff",
                        to="inventory.lot",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doffs",
                        to="manufacturing.machine",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.shift",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="doffs",
                        to="manufacturing.loomstation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weighed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-weighed_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("net_kg__gt", 0)),
                        name="tape_doff_net_positive",
                    )
                ],
            },
        ),
    ]
