# Generated by Django 5.2.17 on 2026-09-28 22:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        ("inventory", "0030_refold_company_wide_valuation"),
        ("manufacturing", "0050_loomstation_kind_tapedoff"),
        (
            "quality",
            "0005_inspection_lot_size_inspection_sampling_planline_aql_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoatingCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metres", models.DecimalField(decimal_places=2, max_digits=12)),
                ("disc_sq_cm", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "samples",
                    models.JSONField(
                        help_text="[[coated g, uncoated g], ...] as weighed."
                    ),
                ),
                ("target_gsm", models.DecimalField(decimal_places=2, max_digits=6)),
                ("lower_gsm", models.DecimalField(decimal_places=3, max_digits=8)),
                ("upper_gsm", models.DecimalField(decimal_places=3, max_digits=8)),
                ("mean_gsm", models.DecimalField(decimal_places=2, max_digits=8)),
                ("passed", models.BooleanField()),
                ("checked_at", models.DateTimeField()),
                ("shift_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["-checked_at"],
            },
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="lamination_tolerance_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10"),
                help_text="How far the coating weighed off the coater may sit from its GSM. Over it is polymer given away; under it, a sack that sifts or will not weld.",
                max_digits=5,
            ),
        ),
        migrations.AddConstraint(
            model_name="bagspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("lamination_tolerance_percent__gte", 0)),
                name="bag_coating_tolerance_not_negative",
            ),
        ),
        migrations.AddField(
            model_name="coatingcheck",
            name="checked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="coatingcheck",
            name="conceded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="coatingcheck",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coatingcheck",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coating_checks",
                to="manufacturing.machine",
            ),
        ),
        migrations.AddField(
            model_name="coatingcheck",
            name="report",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coating_check",
                to="manufacturing.operationreport",
            ),
        ),
        migrations.AddField(
            model_name="coatingcheck",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="manufacturing.shift",
            ),
        ),
        migrations.AddField(
            model_name="coatingcheck",
            name="specification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="manufacturing.bagspecification",
            ),
        ),
        migrations.AddField(
            model_name="coatingcheck",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coating_checks",
                to="manufacturing.loomstation",
            ),
        ),
        migrations.AddField(
            model_name="coatingcheck",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="coatingcheck",
            constraint=models.CheckConstraint(
                condition=models.Q(("metres__gt", 0)),
                name="coating_check_metres_positive",
            ),
        ),
    ]
