# Generated by Django 5.2.17 on 2026-09-28 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        ("inventory", "0030_refold_company_wide_valuation"),
        ("manufacturing", "0051_coating_check"),
        (
            "quality",
            "0005_inspection_lot_size_inspection_sampling_planline_aql_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScaleReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scale_code", models.CharField(db_index=True, max_length=32)),
                ("gross_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("stable", models.BooleanField()),
                (
                    "read_at",
                    models.DateTimeField(help_text="When the server received it."),
                ),
            ],
            options={
                "ordering": ["-read_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="loomstation",
            name="scale_bridged",
            field=models.BooleanField(
                default=False,
                help_text="The scale posts its readings through a bridge: a scale weight here is what the scale reported, never a typed figure.",
            ),
        ),
        migrations.AddField(
            model_name="tapedoff",
            name="typed_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="tapedoff",
            name="typed_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scale_offline", "Scale not connected"),
                    ("calibration", "Scale under calibration"),
                    ("does_not_fit", "Roll does not fit platform"),
                    ("other", "Other"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="tapedoff",
            name="weight_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="tapedoff",
            name="weight_source",
            field=models.CharField(
                choices=[("scale", "Scale"), ("manual", "Manual, supervisor-approved")],
                default="scale",
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="loomstation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scale_bridged", False),
                    models.Q(("scale_code", ""), _negated=True),
                    _connector="OR",
                ),
                name="bridged_station_names_its_scale",
            ),
        ),
        migrations.AddField(
            model_name="scalereading",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scalereading",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="scale_reading",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                help_text="What a bridged scale reported for it.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fabric_roll",
                to="manufacturing.scalereading",
            ),
        ),
        migrations.AddField(
            model_name="tapedoff",
            name="scale_reading",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tape_doff",
                to="manufacturing.scalereading",
            ),
        ),
        migrations.AddConstraint(
            model_name="tapedoff",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("weight_source", "manual"), _negated=True),
                    models.Q(
                        ("weight_approved_by__isnull", False),
                        models.Q(("typed_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="tape_doff_typed_weight_is_approved",
            ),
        ),
    ]
