# Generated by Django 5.2.17 on 2026-09-29 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        ("manufacturing", "0052_scale_bridge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceLabour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("worked_on", models.DateField()),
                ("minutes", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "ordering": ["job", "worked_on", "id"],
            },
        ),
        migrations.AddField(
            model_name="maintenancejob",
            name="action_taken",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="maintenancejob",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="maintenancejob",
            name="cancelled_reason",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="maintenancejob",
            name="cause",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="maintenancejob",
            name="fault",
            field=models.CharField(
                blank=True, help_text="What failed, as reported.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="maintenancejob",
            name="is_breakdown",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="maintenancejob",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancejob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_breakdown", False),
                    models.Q(("downtime__isnull", False), ("schedule__isnull", True)),
                    _connector="OR",
                ),
                name="breakdown_rests_on_a_stoppage",
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancejob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("cancelled_at__isnull", True), ("downtime__isnull", False)
                ),
                fields=("downtime",),
                name="one_standing_job_per_stoppage",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelabour",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="maintenancelabour",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="labour",
                to="manufacturing.maintenancejob",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelabour",
            name="technician",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="maintenancelabour",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancelabour",
            constraint=models.CheckConstraint(
                condition=models.Q(("minutes__gt", 0)),
                name="maintenance_labour_positive",
            ),
        ),
    ]
