# Generated by Django 5.2.17 on 2026-09-29 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        ("inventory", "0031_adjustment_raised_by"),
        ("manufacturing", "0054_spare_issues"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, editable=False, max_length=32)),
                ("received_on", models.DateField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("weight", "Weight or size"),
                            ("strength", "Strength or bursting"),
                            ("seam", "Stitching or seam"),
                            ("print", "Print"),
                            ("lamination", "Lamination or coating"),
                            ("contamination", "Contamination"),
                            ("count", "Count short"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "quantity_affected",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("rejected", "Rejected"),
                        ],
                        default="open",
                        editable=False,
                        max_length=12,
                    ),
                ),
                ("root_cause", models.TextField(blank=True, editable=False)),
                ("decided_on", models.DateField(blank=True, editable=False, null=True)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "reopened_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complaints",
                        to="core.party",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-received_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ComplaintLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="complained_lots",
                        to="manufacturing.complaint",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.lot",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["complaint", "id"],
            },
        ),
        migrations.CreateModel(
            name="CorrectiveAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("containment", "Containment"),
                            ("corrective", "Corrective"),
                            ("preventive", "Preventive"),
                        ],
                        max_length=12,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("due_on", models.DateField()),
                ("done_on", models.DateField(blank=True, editable=False, null=True)),
                (
                    "done_note",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "verified_on",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="manufacturing.complaint",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["complaint", "due_on", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="complaint",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="complaint_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="complaint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_affected__isnull", True),
                    ("quantity_affected__gt", 0),
                    _connector="OR",
                ),
                name="complaint_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="complaintlot",
            constraint=models.UniqueConstraint(
                fields=("complaint", "lot"), name="complaint_names_a_lot_once"
            ),
        ),
    ]
