# Generated by Django 5.2.17 on 2026-09-29 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0055_complaints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="stagerate",
            name="stage_rate_not_negative",
        ),
        migrations.AddField(
            model_name="stagerate",
            name="work_centre",
            field=models.ForeignKey(
                blank=True,
                help_text="The centre that does this stage. Named, the rate is its hourly conversion rate over what it achieves an hour on the specification being costed — the same hour a run is charged.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="manufacturing.workcentre",
            ),
        ),
        migrations.AlterField(
            model_name="stagerate",
            name="rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Per kilogramme the stage makes, or per sack for the per-sack operations (valve, D-cut, handle, liner, packing). Blank when the rate comes from the work centre.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="stagerate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rate__isnull", True), ("rate__gte", 0), _connector="OR"
                ),
                name="stage_rate_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagerate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("rate__isnull", False), ("work_centre__isnull", True)),
                    models.Q(("rate__isnull", True), ("work_centre__isnull", False)),
                    _connector="OR",
                ),
                name="stage_rate_typed_or_from_a_work_centre",
            ),
        ),
    ]
