# Generated by Django 5.2.17 on 2026-09-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0056_stage_rate_from_work_centre"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productionentry",
            name="production_entry_books_something",
        ),
    ]
