# Generated by Django 5.2.17 on 2026-09-29 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        ("inventory", "0031_adjustment_raised_by"),
        ("manufacturing", "0057_entry_may_book_waste_alone"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessRoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=40, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("coated", "Laminated (coated)"),
                            ("bopp", "BOPP laminated"),
                            ("metallic", "Metallic laminated"),
                            ("printed", "Printed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("gross_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("net_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("metres", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "added_gsm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="What the lamination added, measured.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "expected_gsm",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "lower_gsm",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "upper_gsm",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                ("passed", models.BooleanField(null=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("weighed_at", models.DateTimeField()),
                ("shift_date", models.DateField()),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "conceded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "core_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.coretype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.machine",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.shift",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.loomstation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weighed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-weighed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RollMount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mounted_at", models.DateTimeField()),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.materialissue",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        help_text="A roll from stock.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mounts",
                        to="inventory.lot",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mounts",
                        to="manufacturing.machine",
                    ),
                ),
                (
                    "mounted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mounts",
                        to="manufacturing.workorderoperation",
                    ),
                ),
                (
                    "returned",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.materialissue",
                    ),
                ),
                (
                    "roll",
                    models.ForeignKey(
                        blank=True,
                        help_text="A roll made earlier in this run.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mounts",
                        to="manufacturing.processroll",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mounts",
                        to="manufacturing.loomstation",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-mounted_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="processroll",
            name="mount",
            field=models.ForeignKey(
                help_text="What was on the machine when this came off it.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="made",
                to="manufacturing.rollmount",
            ),
        ),
        migrations.AddField(
            model_name="bagcount",
            name="mount",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The roll on the machine when the bundle was counted.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bag_counts",
                to="manufacturing.rollmount",
            ),
        ),
        migrations.AddConstraint(
            model_name="rollmount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("lot__isnull", False), ("roll__isnull", True)),
                    models.Q(("lot__isnull", True), ("roll__isnull", False)),
                    _connector="OR",
                ),
                name="mount_is_a_stock_roll_or_one_made_here",
            ),
        ),
        migrations.AddConstraint(
            model_name="rollmount",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("finished_at__isnull", True), ("voided_at__isnull", True)
                ),
                fields=("machine",),
                name="one_roll_mounted_per_machine",
            ),
        ),
        migrations.AddConstraint(
            model_name="processroll",
            constraint=models.CheckConstraint(
                condition=models.Q(("net_kg__gt", 0), ("metres__gt", 0)),
                name="process_roll_is_a_real_roll",
            ),
        ),
    ]
