# Generated by Django 5.2.17 on 2026-09-29 09:16

import apps.manufacturing.woven
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        ("inventory", "0031_adjustment_raised_by"),
        ("manufacturing", "0058_roll_mounts"),
        (
            "quality",
            "0005_inspection_lot_size_inspection_sampling_planline_aql_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FilmRoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gross_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "weight_source",
                    models.CharField(
                        choices=[
                            ("scale", "Scale"),
                            ("manual", "Manual, supervisor-approved"),
                        ],
                        default="scale",
                        max_length=8,
                    ),
                ),
                (
                    "typed_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("scale_offline", "Scale not connected"),
                            ("calibration", "Scale under calibration"),
                            ("does_not_fit", "Roll does not fit platform"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("typed_note", models.CharField(blank=True, max_length=255)),
                ("net_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("metres", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "mean_micron",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What the gauge read, on average.",
                        max_digits=8,
                    ),
                ),
                (
                    "weighed_micron",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="What the roll's weight over its length and width says.",
                        max_digits=8,
                    ),
                ),
                ("weighed_at", models.DateTimeField()),
                ("shift_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["-weighed_at"],
            },
        ),
        migrations.CreateModel(
            name="FilmSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="The first date output made to this specification is due.",
                        null=True,
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="The last date output made to this specification is due.",
                        null=True,
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "micron",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Thickness of one layer of the tube.",
                        max_digits=6,
                    ),
                ),
                (
                    "lay_flat_width_cm",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "lldpe_percent",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "masterbatch_percent",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "extrusion_waste_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("3"),
                        help_text="Of what is fed in: start-up, gauge bands trimmed off, bubble breaks.",
                        max_digits=6,
                    ),
                ),
                (
                    "waste_recovered_percent",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("80"), max_digits=6
                    ),
                ),
                (
                    "micron_tolerance_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10"),
                        help_text="How far a gauge reading may be from the thickness.",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
            bases=(apps.manufacturing.woven.SpecificationMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LinerSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="The first date output made to this specification is due.",
                        null=True,
                    ),
                ),
                (
                    "valid_to",
                    models.DateField(
                        blank=True,
                        help_text="The last date output made to this specification is due.",
                        null=True,
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "cut_length_cm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tube cut for one liner, the seal included.",
                        max_digits=8,
                    ),
                ),
                (
                    "seal_waste_percent",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("2"),
                        help_text="Of the film fed in: bad seals, the roll's ends.",
                        max_digits=6,
                    ),
                ),
                (
                    "waste_recovered_percent",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("80"), max_digits=6
                    ),
                ),
                (
                    "weight_tolerance_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5"), max_digits=5
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["code"],
            },
            bases=(apps.manufacturing.woven.SpecificationMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name="stagerate",
            name="stage_rate_stage_known",
        ),
        migrations.AddField(
            model_name="processroll",
            name="scale_reading",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="process_roll",
                to="manufacturing.scalereading",
            ),
        ),
        migrations.AddField(
            model_name="processroll",
            name="typed_note",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="processroll",
            name="typed_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("scale_offline", "Scale not connected"),
                    ("calibration", "Scale under calibration"),
                    ("does_not_fit", "Roll does not fit platform"),
                    ("other", "Other"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="processroll",
            name="weight_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="processroll",
            name="weight_source",
            field=models.CharField(
                choices=[("scale", "Scale"), ("manual", "Manual, supervisor-approved")],
                default="scale",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="costsheetline",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("tape", "Tape extrusion"),
                    ("weaving", "Weaving"),
                    ("lamination", "Lamination"),
                    ("printing", "Printing"),
                    ("cutting", "Cutting and stitching"),
                    ("blown_film", "Liner film blowing"),
                    ("valve", "Valve fixing"),
                    ("dcut", "D-cut punching"),
                    ("handle", "Handle attachment"),
                    ("liner", "Liner insertion"),
                    ("packing", "Bale packing"),
                    ("sealing", "Liner cutting and sealing"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="loomstation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("loom_exit", "Loom exit"),
                    ("conversion", "Cutting and stitching"),
                    ("extrusion", "Tape line"),
                    ("printing", "Printing"),
                    ("coating", "Coating and lamination"),
                    ("blown_film", "Blown film"),
                ],
                default="loom_exit",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="stagerate",
            name="stage",
            field=models.CharField(
                choices=[
                    ("tape", "Tape extrusion"),
                    ("weaving", "Weaving"),
                    ("lamination", "Lamination"),
                    ("printing", "Printing"),
                    ("cutting", "Cutting and stitching"),
                    ("blown_film", "Liner film blowing"),
                    ("valve", "Valve fixing"),
                    ("dcut", "D-cut punching"),
                    ("handle", "Handle attachment"),
                    ("liner", "Liner insertion"),
                    ("packing", "Bale packing"),
                    ("sealing", "Liner cutting and sealing"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="processroll",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("weight_source", "manual"), _negated=True),
                    models.Q(
                        ("weight_approved_by__isnull", False),
                        models.Q(("typed_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="process_roll_typed_weight_is_approved",
            ),
        ),
        migrations.AddConstraint(
            model_name="stagerate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "stage__in",
                        [
                            "tape",
                            "weaving",
                            "lamination",
                            "printing",
                            "cutting",
                            "blown_film",
                            "valve",
                            "dcut",
                            "handle",
                            "liner",
                            "packing",
                            "sealing",
                        ],
                    )
                ),
                name="stage_rate_stage_known",
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="conceded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="core_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="manufacturing.coretype",
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="entry",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="manufacturing.productionentry",
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="inspection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="quality.inspection",
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="lot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="film_roll",
                to="inventory.lot",
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="film_rolls",
                to="manufacturing.machine",
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="scale_reading",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="film_roll",
                to="manufacturing.scalereading",
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="manufacturing.shift",
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="film_rolls",
                to="manufacturing.loomstation",
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="weighed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="filmroll",
            name="weight_approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="filmspecification",
            name="base_polymer",
            field=models.ForeignKey(
                help_text="LDPE. Its share is whatever the rest of the blend leaves.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="filmspecification",
            name="bom",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="film_specification",
                to="manufacturing.billofmaterials",
            ),
        ),
        migrations.AddField(
            model_name="filmspecification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filmspecification",
            name="film_item",
            field=models.ForeignKey(
                help_text="The film roll this makes, stocked by weight.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="film_specifications",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="filmspecification",
            name="inspection_plan",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="film_specification",
                to="quality.inspectionplan",
            ),
        ),
        migrations.AddField(
            model_name="filmspecification",
            name="lldpe_item",
            field=models.ForeignKey(
                blank=True,
                help_text="LLDPE, for toughness and seal strength.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="filmspecification",
            name="masterbatch_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="filmspecification",
            name="routing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="film_specifications",
                to="manufacturing.routing",
            ),
        ),
        migrations.AddField(
            model_name="filmspecification",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="filmspecification",
            name="waste_item",
            field=models.ForeignKey(
                blank=True,
                help_text="What the collected film waste is stocked as.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="linerspecification",
            name="bom",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liner_specification",
                to="manufacturing.billofmaterials",
            ),
        ),
        migrations.AddField(
            model_name="linerspecification",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="linerspecification",
            name="film",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liners",
                to="manufacturing.filmspecification",
            ),
        ),
        migrations.AddField(
            model_name="linerspecification",
            name="inspection_plan",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="liner_specification",
                to="quality.inspectionplan",
            ),
        ),
        migrations.AddField(
            model_name="linerspecification",
            name="liner_item",
            field=models.ForeignKey(
                help_text="The liner, counted.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liner_specifications",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="linerspecification",
            name="routing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liner_specifications",
                to="manufacturing.routing",
            ),
        ),
        migrations.AddField(
            model_name="linerspecification",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="filmroll",
            constraint=models.CheckConstraint(
                condition=models.Q(("net_kg__gt", 0), ("metres__gt", 0)),
                name="film_roll_is_a_real_roll",
            ),
        ),
        migrations.AddConstraint(
            model_name="filmroll",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("weight_source", "manual"), _negated=True),
                    models.Q(
                        ("weight_approved_by__isnull", False),
                        models.Q(("typed_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="film_roll_typed_weight_is_approved",
            ),
        ),
        migrations.AddConstraint(
            model_name="filmspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("micron__gt", 0), ("lay_flat_width_cm__gt", 0)),
                name="film_has_a_size",
            ),
        ),
        migrations.AddConstraint(
            model_name="filmspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lldpe_percent__gte", 0), ("masterbatch_percent__gte", 0)
                ),
                name="film_blend_shares_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="filmspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("extrusion_waste_percent__gte", 0),
                    ("extrusion_waste_percent__lt", 100),
                    ("waste_recovered_percent__gte", 0),
                    ("waste_recovered_percent__lte", 100),
                    ("micron_tolerance_percent__gte", 0),
                ),
                name="film_percentages_sensible",
            ),
        ),
        migrations.AddConstraint(
            model_name="linerspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(("cut_length_cm__gt", 0)), name="liner_has_a_length"
            ),
        ),
        migrations.AddConstraint(
            model_name="linerspecification",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("seal_waste_percent__gte", 0),
                    ("seal_waste_percent__lt", 100),
                    ("waste_recovered_percent__gte", 0),
                    ("waste_recovered_percent__lte", 100),
                    ("weight_tolerance_percent__gte", 0),
                ),
                name="liner_percentages_sensible",
            ),
        ),
    ]
