# Generated by Django 5.2.17 on 2026-09-29 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("manufacturing", "0059_liner_line"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="inserts_liner",
            field=models.BooleanField(
                blank=True,
                help_text="A BCS: yes for the one that puts the liner in, no for the rest. Blank on machines where a liner is not their business.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="max_colours",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="A press: colours it prints, front and back together.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="max_length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Longest.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="max_width_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Widest.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="min_length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Shortest cut length it cuts: a BCS or a cut-and-seal machine.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="min_width_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Narrowest tube, web or sack it takes: a loom's smallest tube, a BCS's narrowest sack.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workcentre",
            name="line_speed_m_per_min",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Tape line: winding speed. Web: the speed the fabric, film or tube runs through a laminator, press, BCS or blown-film haul-off. Metres a minute, both.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="workcentre",
            name="speed_basis",
            field=models.CharField(
                choices=[
                    ("stated", "Stated rate"),
                    ("tape_line", "Tape line"),
                    ("circular_loom", "Circular loom"),
                    ("web", "Web speed (metres a minute)"),
                ],
                default="stated",
                help_text="Where its speed comes from: the rate stated here, or worked out from the product and the machine's settings.",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="machine",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("min_width_cm__isnull", True),
                        ("min_width_cm__gt", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("max_width_cm__isnull", True),
                        ("max_width_cm__gt", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("min_length_cm__isnull", True),
                        ("min_length_cm__gt", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("max_length_cm__isnull", True),
                        ("max_length_cm__gt", 0),
                        _connector="OR",
                    ),
                    models.Q(
                        ("min_width_cm__isnull", True),
                        ("max_width_cm__isnull", True),
                        ("min_width_cm__lte", models.F("max_width_cm")),
                        _connector="OR",
                    ),
                    models.Q(
                        ("min_length_cm__isnull", True),
                        ("max_length_cm__isnull", True),
                        ("min_length_cm__lte", models.F("max_length_cm")),
                        _connector="OR",
                    ),
                ),
                name="machine_size_range_sensible",
            ),
        ),
    ]
