# Generated by Django 5.2.17 on 2026-09-29 10:48

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0060_machine_capability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="changeoverrule",
            name="changeover_not_negative",
        ),
        migrations.AddField(
            model_name="changeoverrule",
            name="purge_kg",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Polymer run through to clear the old colour or recipe out of an extruder: material spent on the change, not only minutes.",
                max_digits=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="changeoverrule",
            constraint=models.CheckConstraint(
                condition=models.Q(("minutes__gte", 0), ("purge_kg__gte", 0)),
                name="changeover_not_negative",
            ),
        ),
    ]
