# Generated by Django 5.2.17 on 2026-09-29 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("manufacturing", "0061_changeover_purge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bagspecification",
            name="print_design",
            field=models.ForeignKey(
                blank=True,
                help_text="The artwork it is printed with: whose cylinders a run needs.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bag_specifications",
                to="manufacturing.printdesign",
            ),
        ),
        migrations.AddField(
            model_name="printdesign",
            name="engraving_lead_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Days from ordering a cylinder to having it at the press. What a run waits for when its set is short and nothing is on order.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="expected_on",
            field=models.DateField(
                blank=True,
                help_text="On order: the day it is due at the press.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("worn", "Worn out"),
                    ("service", "Away for service"),
                    ("ordered", "On order"),
                    ("retired", "Retired"),
                ],
                default="available",
                max_length=12,
            ),
        ),
        migrations.AddConstraint(
            model_name="tool",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "ordered"), _negated=True),
                    ("expected_on__isnull", False),
                    _connector="OR",
                ),
                name="tool_on_order_says_when",
            ),
        ),
    ]
