# Generated by Django 5.2.17 on 2026-09-29 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0063_tape_loads"),
        (
            "quality",
            "0005_inspection_lot_size_inspection_sampling_planline_aql_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bagspecification",
            name="bond_strength_min_n",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Laminated sacks: least peel strength of the coating, newtons a 15 mm strip.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="drop_test_drops",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Drops a filled sack must survive; every one of three tested.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="seam_strength_min_n",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Least load the bottom seam holds, newtons, on the mean of five.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="uv_exposure_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The hours of exposure that share is after.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="uv_retention_min_percent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Least share of its strength the fabric keeps after UV exposure.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fabricspecification",
            name="mesh_tolerance_per_inch",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Given, the lab counts ends and picks an inch against the mesh, give or take this many.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fabricspecification",
            name="warp_strength_min_n",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Least tensile strength along the warp, newtons a 5 cm strip.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fabricspecification",
            name="weft_strength_min_n",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Across the weft.",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bagcount",
            name="inspection",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bag_count",
                to="quality.inspection",
            ),
        ),
    ]
