# Generated by Django 5.2.17 on 2026-09-29 13:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_adjustment_raised_by"),
        ("manufacturing", "0064_lab_tests"),
    ]

    operations = [
        migrations.AddField(
            model_name="bagspecification",
            name="seconds_item",
            field=models.ForeignKey(
                blank=True,
                help_text="What an off-grade sack is sold as: counted, at its own lower value.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="seconds_percent",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0"),
                help_text="Of what is fed into conversion, the share that comes out a second rather than a first or offcut. Out of the conversion waste, not on top of it.",
                max_digits=6,
            ),
        ),
    ]
