# Generated by Django 5.2.17 on 2026-09-29 13:31

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0065_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="bagspecification",
            name="max_delta_e",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.00"),
                help_text="Printed: the most a roll's shade may differ from the approved proof.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="bagspecification",
            name="registration_tolerance_mm",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Printed: how far out of register a roll off the press may be.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="processroll",
            name="delta_e",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Off the press: shade against the approved proof.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="processroll",
            name="design",
            field=models.ForeignKey(
                blank=True,
                help_text="The artwork confirmed on the press.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="manufacturing.printdesign",
            ),
        ),
        migrations.AddField(
            model_name="processroll",
            name="registration_mm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Off the press: how far out of register the colours are, the worst seen.",
                max_digits=6,
                null=True,
            ),
        ),
    ]
