# Generated by Django 5.2.17 on 2026-10-03 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0066_print_check"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternateRouting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        help_text="1 is tried first after the bill's own routing."
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternate_routings",
                        to="manufacturing.billofmaterials",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "routing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.routing",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["bom", "priority"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("bom", "routing"), name="one_alternate_per_routing"
                    ),
                    models.UniqueConstraint(
                        fields=("bom", "priority"), name="one_alternate_per_priority"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("priority__gt", 0)),
                        name="alternate_priority_positive",
                    ),
                ],
            },
        ),
    ]
