# Generated by Django 5.2.17 on 2026-10-03 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        ("manufacturing", "0067_alternaterouting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrewAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["work_centre", "shift", "employee"],
            },
        ),
        migrations.AddField(
            model_name="workcentre",
            name="operators_per_machine",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="People a machine here takes: 0.25 where a weaver minds four looms, 2 on a BCS. Given, the bank runs only as many machines as its crew present can; blank, its crew is not a limit.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="workcentre",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("operators_per_machine__isnull", True),
                    ("operators_per_machine__gt", 0),
                    _connector="OR",
                ),
                name="work_centre_crew_per_machine_positive",
            ),
        ),
        migrations.AddField(
            model_name="crewassignment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crewassignment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crew_assignments",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="crewassignment",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crew",
                to="manufacturing.shift",
            ),
        ),
        migrations.AddField(
            model_name="crewassignment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="crewassignment",
            name="work_centre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crew",
                to="manufacturing.workcentre",
            ),
        ),
        migrations.AddConstraint(
            model_name="crewassignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="crew_assignment_window_forwards",
            ),
        ),
    ]
