# Generated by Django 5.2.17 on 2026-10-06 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0069_complaintsettlement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TapeRunSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("draw_ratio", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "quench_temperature_c",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="The water bath the film is chilled in.",
                        max_digits=5,
                    ),
                ),
                (
                    "oven_temperature_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="The orientation oven, where the tape is stretched.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.machine",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tape_settings",
                        to="manufacturing.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["recorded_at", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("draw_ratio__gt", 1)),
                        name="tape_draw_ratio_stretches",
                    )
                ],
            },
        ),
    ]
