# Generated by Django 5.2.17 on 2026-10-06 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0014_attendance"),
        ("manufacturing", "0070_tape_run_settings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="meterreading",
            name="max_demand_kva",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The maximum demand the meter shows, in kVA, as it stands at this reading.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meterreading",
            name="power_factor",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="The power factor the meter shows, over 0 and up to 1.",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="meterreading",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_demand_kva__isnull", True),
                    ("max_demand_kva__gt", 0),
                    _connector="OR",
                ),
                name="meter_reading_demand_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="meterreading",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("power_factor__isnull", True),
                    models.Q(("power_factor__gt", 0), ("power_factor__lte", 1)),
                    _connector="OR",
                ),
                name="meter_reading_power_factor_within_one",
            ),
        ),
    ]
