# Generated by Django 5.2.17 on 2026-10-07 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0074_custom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BomChangeOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, editable=False, max_length=32)),
                (
                    "effective_from",
                    models.DateField(
                        help_text="The first day output is made to the new version."
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "decision_note",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "draft",
                    models.ForeignKey(
                        help_text="The new version, made with the order and edited until it is applied.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes_to",
                        to="manufacturing.billofmaterials",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        help_text="The version being replaced.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes_from",
                        to="manufacturing.billofmaterials",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "permissions": [
                    ("apply_bomchangeorder", "Can apply or reject a BOM change order")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("number", ""), _negated=True),
                        fields=("number",),
                        name="unique_bom_change_number",
                    )
                ],
            },
        ),
    ]
