# Generated by Django 5.2.17 on 2026-10-07 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0017_custom_fields"),
        ("inventory", "0035_custom_fields"),
        ("manufacturing", "0075_bom_change_orders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="correctiveaction",
            options={"ordering": ["complaint", "alert", "due_on", "id"]},
        ),
        migrations.AlterField(
            model_name="correctiveaction",
            name="complaint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actions",
                to="manufacturing.complaint",
            ),
        ),
        migrations.CreateModel(
            name="QualityAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, editable=False, max_length=32)),
                ("raised_on", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("cancelled", "Not a defect"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                (
                    "quantity_affected",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=18, null=True
                    ),
                ),
                ("root_cause", models.TextField(blank=True, editable=False)),
                ("decided_on", models.DateField(blank=True, editable=False, null=True)),
                (
                    "cancelled_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "reopened_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.lot",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_alerts",
                        to="manufacturing.machine",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who is to deal with it.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "raised_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who saw it.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_centre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_alerts",
                        to="manufacturing.workcentre",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_alerts",
                        to="manufacturing.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-raised_on", "-id"],
            },
        ),
        migrations.AddField(
            model_name="correctiveaction",
            name="alert",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actions",
                to="manufacturing.qualityalert",
            ),
        ),
        migrations.AddConstraint(
            model_name="correctiveaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("alert__isnull", True), ("complaint__isnull", False)),
                    models.Q(("alert__isnull", False), ("complaint__isnull", True)),
                    _connector="OR",
                ),
                name="corrective_action_on_a_complaint_or_an_alert",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityalert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="unique_quality_alert_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="qualityalert",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_affected__isnull", True),
                    ("quantity_affected__gte", 0),
                    _connector="OR",
                ),
                name="quality_alert_quantity_not_negative",
            ),
        ),
    ]
