# Generated by Django 5.2.17 on 2026-10-08 03:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0018_people"),
        ("manufacturing", "0076_quality_alerts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="maintenancejob",
            name="replaced_last_done_on",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="When its schedule said it was last done before this job was completed, so a completion withdrawn puts the clock back where it found it. Empty: never done before.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="maintenancejob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("cancelled_at__isnull", True), ("done_on__isnull", True)
                ),
                fields=("schedule",),
                name="one_open_job_per_schedule",
            ),
        ),
    ]
