# Generated by Django 5.2.17 on 2026-10-08 12:40

import django.db.models.deletion
from django.db import migrations, models


def freeze_the_present_account(apps, schema_editor):
    """
    Runs already released or closed were posted to the account set now:
    the setting refused to move while any run was released. A closed one
    that ran before an earlier move cannot be told apart, and keeps
    today's behaviour.
    """
    settings = apps.get_model("manufacturing", "ManufacturingSettings").objects.first()
    if settings is None or settings.wip_account_id is None:
        return
    apps.get_model("manufacturing", "WorkOrder").objects.filter(
        status__in=("released", "closed"), wip_account__isnull=True,
    ).update(wip_account_id=settings.wip_account_id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0023_account_holds_money"),
        ("manufacturing", "0077_maintenance_completion_withdrawn"),
    ]

    operations = [
        migrations.AddField(
            model_name="workorder",
            name="wip_account",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The work-in-progress account this run's material is kept on, frozen at release. Everything the run posts, its close and its reopening land there, whatever the setting says later: a run closed, reopened after the account moved and closed again left 93,195.89 on the old account and the same credit on the new one.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.RunPython(freeze_the_present_account, migrations.RunPython.noop),
    ]
