# Generated by Django 5.2.17 on 2026-10-08 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0023_account_holds_money"),
        ("manufacturing", "0078_workorder_wip_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialissue",
            name="void_variance_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="On the void of a return: what taking the material back off the shelf removed, against what it came back at, booked to material variance. The shelf may have moved in between.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddField(
            model_name="productionentry",
            name="void_variance_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="On the void: what taking the output and by-products back off the shelf removed, against what they went on at, booked to material variance. The shelf may have moved in between.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
    ]
