# Generated by Django 5.2.17 on 2026-10-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0079_materialissue_void_variance_entry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialissueline",
            name="posted_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                editable=False,
                help_text="What this line moved, the total, frozen when it posted: what the issue took off the shelf, or what a return put back. A return and a void work from it rather than from the rate: 30,000 kg taken at 2,125,670.33 came back at a six-place rate as 2,125,670.34, and work in progress was left at -0.01.",
                max_digits=24,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="materialissueline",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                editable=False,
                help_text="What a unit was worth when it moved, frozen here, to read. Nothing is worked out from it: see `posted_value`.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
