"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import unquote, urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
def _env_list(name):
    return [value.strip() for value in os.environ.get(name, "").split(",") if value.strip()]


# DJANGO_ENV=production is the plant's server. There the defaults are the
# safe ones and a missing secret stops it starting; anywhere else is a
# developer's machine, where `manage.py test` must work with nothing set.
PRODUCTION = os.environ.get("DJANGO_ENV", "development").lower() == "production"

DEV_SECRET_KEY = "django-insecure-!9b4h^4ur4@@q_&9k-)e2^yo+ge*%436b)7olcl5ydq%#4+0=1"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY") or DEV_SECRET_KEY
if PRODUCTION and SECRET_KEY == DEV_SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is not set. Every session and password reset is signed with "
        "it; the server will not start on the published development key."
    )

DEBUG = os.environ.get("DJANGO_DEBUG", "false" if PRODUCTION else "true").lower() == "true"

ALLOWED_HOSTS = _env_list("DJANGO_ALLOWED_HOSTS")
if PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("DJANGO_ALLOWED_HOSTS is not set: name the server's host names.")
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

# Signing in from the address bar lands on the office application; the
# station screens pass their own ?next=.
LOGIN_REDIRECT_URL = "/app/"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "apps.core",
    "apps.inventory",
    "apps.accounting",
    "apps.sales",
    "apps.purchasing",
    "apps.hr",
    "apps.manufacturing",
    "apps.quality",
    "apps.planning",
    "apps.assets",
    "apps.gst",
    "apps.web",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "apps.core.middleware.RequestMemo",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _database(url):
    """
    postgres://user:password@host:5432/name, or nothing for the local
    SQLite file. SQLite is for one person on one laptop: several
    stations writing at once queue behind its single lock.
    """
    if not url:
        return {"ENGINE": "django.db.backends.sqlite3", "NAME": BASE_DIR / "db.sqlite3"}
    parts = urlparse(url)
    if parts.scheme not in ("postgres", "postgresql"):
        raise ImproperlyConfigured(f"DATABASE_URL must be postgres://..., not {parts.scheme}.")
    return {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": unquote(parts.path.lstrip("/")),
        "USER": unquote(parts.username or ""),
        "PASSWORD": unquote(parts.password or ""),
        "HOST": parts.hostname or "",
        "PORT": str(parts.port or ""),
        "CONN_MAX_AGE": int(os.environ.get("DATABASE_CONN_MAX_AGE", "60")),
        "CONN_HEALTH_CHECKS": True,
        "ATOMIC_REQUESTS": False,
        # PostgreSQL compiles any plan it guesses costs over 100,000 to
        # machine code first. For a report that answers in 100 ms that was
        # half the time (AR aging: 53 ms of 107), and AP aging went from
        # 0.43 to 0.30 seconds without it. It pays off on analytical
        # queries that run for minutes, which this application has none of.
        "OPTIONS": {"options": "-c jit=off"},
    }


DATABASES = {"default": _database(os.environ.get("DATABASE_URL", ""))}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Counts and limits password guesses: the login page, the admin and the
# API's basic authentication all come through here (apps/core/auth.py).
AUTHENTICATION_BACKENDS = ["apps.core.auth.LockoutModelBackend"]

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

# The plant's own clock: shifts start at 08:00 there, not in Greenwich.
# Set DJANGO_TIME_ZONE=Asia/Kolkata in production.
TIME_ZONE = os.environ.get("DJANGO_TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = Path(os.environ.get("DJANGO_STATIC_ROOT", BASE_DIR / "staticfiles"))

if PRODUCTION:
    # Behind the reverse proxy, which terminates TLS. DJANGO_HTTPS=false is
    # for a plant that serves plain HTTP on its own network: the cookies
    # must then go without the secure flag or nobody can log in, and every
    # password and PIN crosses that network readable. A deliberate choice,
    # never a default.
    if os.environ.get("DJANGO_HTTPS", "true").lower() == "true":
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
        SECURE_SSL_REDIRECT = True
        SESSION_COOKIE_SECURE = True
        CSRF_COOKIE_SECURE = True
        SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "3600"))
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # The admin's and the API's own stylesheets, served by the application
    # itself: one container, no separate web server to keep in step.
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }
    # Files whose names carry a hash of their content may be kept by a
    # browser for good: Django's (name.0123456789ab.css) and the office
    # application's (web/assets/name-AbCd_123.js). Matched against the
    # address; a pattern here replaces WhiteNoise's own test, so it names
    # Django's form too. The application's page (apps/web) is never cached.
    WHITENOISE_IMMUTABLE_FILE_TEST = (
        r"(\.[0-9a-f]{12}\.[^/]+$)|(/web/assets/[^/]+-[A-Za-z0-9_-]{8}\.[a-z0-9]+$)"
    )

    # To the container's output, where `docker compose logs` finds it.
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {"plain": {"format": "%(asctime)s %(levelname)s %(name)s %(message)s"}},
        "handlers": {"console": {"class": "logging.StreamHandler", "formatter": "plain"}},
        "root": {"handlers": ["console"], "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO")},
    }

# Invoices, quotations, statements and dunning reminders go by email.
# With no mail server named, production refuses to send rather than
# reaching for one that is not there; a developer's machine keeps
# Django's default, and tests capture mail in memory either way.
if os.environ.get("EMAIL_HOST"):
    EMAIL_HOST = os.environ["EMAIL_HOST"]
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)
elif PRODUCTION:
    EMAIL_BACKEND = "apps.core.mail.NotConfiguredBackend"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# No anonymous writes: audit stamping (created_by/updated_by) requires a
# real authenticated user on every request, not AnonymousUser.
# ModelPermissions enforces view/add/change/delete per model; ActionPermission
# adds segregation of duties on posting actions (see apps/core/permissions.py).
REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "apps.core.permissions.ModelPermissions",
        "apps.core.permissions.ActionPermission",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    # Documents enforce their rules in save(), which raises Django's
    # ValidationError. Without this a caller who broke a rule got a 500
    # instead of the sentence the model wrote for them.
    "EXCEPTION_HANDLER": "apps.core.api.exception_handler",
    # Lists in pages of 50; the body stays a list, the count is in the
    # X-Total-Count header (apps/core/api.py).
    # Every Decimal as its exact string, never a float (apps/core/renderers.py).
    "DEFAULT_RENDERER_CLASSES": [
        "apps.core.renderers.ExactJSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_PAGINATION_CLASS": "apps.core.api.HeaderPagination",
    "PAGE_SIZE": 50,
    # ?search=, ?<field>=, ?from=&to= and ?ordering= on a list, each over
    # only the fields its view names (apps/core/api.py).
    "DEFAULT_FILTER_BACKENDS": [
        "apps.core.api.Search",
        "apps.core.api.FieldFilter",
        "apps.core.api.Ordering",
    ],
}
