# Generated by Django 5.2.17 on 2026-09-19 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={
                "ordering": ["-start_date"],
                "permissions": [
                    ("decide_leaverequest", "Can approve or reject leave requests")
                ],
            },
        ),
    ]
