# Generated by Django 5.2.17 on 2026-09-21 05:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accountingperiod"),
        ("hr", "0002_alter_leaverequest_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Country or office code. Blank means it applies to everyone.",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "region"],
            },
        ),
        migrations.AddField(
            model_name="department",
            name="cost_centre",
            field=models.ForeignKey(
                blank=True,
                help_text="Where this department's payroll is charged. Falls back to the company default when blank.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="holiday_region",
            field=models.CharField(
                blank=True,
                help_text="Which public holidays apply. Blank means the company-wide set only.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="working_days",
            field=models.CharField(
                default="12345",
                help_text="ISO weekday numbers this person works: 1 is Monday, 7 is Sunday. A four-day week is '1234'. Leave is counted against this, so a part-timer is not charged for days they were never going to work.",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="days_taken",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Working days this cost, frozen when it was approved. The working pattern and the public holiday list both change; what an approved holiday cost does not.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="half_day",
            field=models.BooleanField(
                default=False,
                help_text="A single day taken as a half. Only meaningful when the request is one day long.",
            ),
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("vacation", "Vacation"),
                            ("sick", "Sick"),
                            ("unpaid", "Unpaid"),
                            ("other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "annual_days",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Working days a full year grants.",
                        max_digits=6,
                    ),
                ),
                (
                    "accrues_monthly",
                    models.BooleanField(
                        default=False,
                        help_text="Earn it a twelfth at a time rather than all of it on day one. A joiner in November has not earned a year's holiday.",
                    ),
                ),
                (
                    "carry_over_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Most days that may be carried into the next year. Anything above it lapses.",
                        max_digits=6,
                    ),
                ),
                (
                    "allows_negative",
                    models.BooleanField(
                        default=False,
                        help_text="Permit booking beyond the balance — for sick leave, which is not earned, and for companies that let holiday go overdrawn.",
                    ),
                ),
                ("is_paid", models.BooleanField(default=True)),
                ("requires_approval", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "leave policies",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LeaveEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveIntegerField()),
                ("days", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "carried_over",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Brought in from last year, already capped by that year's policy.",
                        max_digits=6,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entitlements",
                        to="hr.leavepolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "employee"],
            },
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="policy",
            field=models.ForeignKey(
                blank=True,
                help_text="Which allowance this draws against. Without one the request is recorded and counts against nothing.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requests",
                to="hr.leavepolicy",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaverequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="leave_ends_after_it_starts",
            ),
        ),
        migrations.AddField(
            model_name="publicholiday",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="publicholiday",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="leaveentitlement",
            constraint=models.UniqueConstraint(
                fields=("employee", "policy", "year"), name="one_entitlement_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="leaveentitlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("days__gte", 0)),
                name="entitlement_days_not_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="publicholiday",
            index=models.Index(fields=["date"], name="hr_publicho_date_698c37_idx"),
        ),
        migrations.AddConstraint(
            model_name="publicholiday",
            constraint=models.UniqueConstraint(
                fields=("date", "region"), name="one_public_holiday_per_date_and_region"
            ),
        ),
    ]
