# Generated by Django 5.2.17 on 2026-09-21 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accountingperiod"),
        ("hr", "0003_publicholiday_department_cost_centre_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("earning", "Earning"),
                            ("deduction", "Employee deduction"),
                            ("employer_cost", "Employer cost"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed amount"),
                            ("percent", "Percentage of taxable gross"),
                            ("per_hour", "Rate per hour"),
                        ],
                        default="fixed",
                        max_length=16,
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(
                        default=True,
                        help_text="Counts towards the gross that percentage components are worked out from. An expense reimbursement is pay that is not.",
                    ),
                ),
                (
                    "reduces_for_unpaid_leave",
                    models.BooleanField(
                        default=False,
                        help_text="Prorate this down for unpaid days in the period. True for salary; false for a fixed allowance that is paid regardless.",
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Order on the payslip, and the order components are worked out in — a percentage can only be taken of what has been computed before it.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Where an earning or an employer cost is charged. A department's cost centre overrides it for that department's staff.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "liability_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="What a deduction or employer contribution is owed into — tax payable, pension payable.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "code"],
            },
        ),
        migrations.CreateModel(
            name="PayRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("pay_date", models.DateField()),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("calculated", "Calculated"),
                            ("posted", "Posted"),
                            ("voided", "Voided"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start", "-id"],
                "permissions": [("post_payrun", "Can post a pay run to the ledger")],
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="hr.employee",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="What settled the net pay. Until it is set, net pay payable holds this slip's balance.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="accounting.payment",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="hr.payrun",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["employee"],
            },
        ),
        migrations.CreateModel(
            name="PayslipLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("earning", "Earning"),
                            ("deduction", "Employee deduction"),
                            ("employer_cost", "Employer cost"),
                        ],
                        editable=False,
                        max_length=16,
                    ),
                ),
                (
                    "basis",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed amount"),
                            ("percent", "Percentage of taxable gross"),
                            ("per_hour", "Rate per hour"),
                        ],
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="What the component was set to when this slip was worked out. Kept so the payslip can still be explained after the next rise.",
                        max_digits=18,
                    ),
                ),
                ("is_taxable", models.BooleanField(default=True, editable=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.paycomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payslip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="hr.payslip",
                    ),
                ),
                (
                    "posted_account",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Where this line actually landed when the run posted, frozen so a reversal gives it back to the same place.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["component__sequence", "component__code"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeCompensation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="The period amount for a fixed component, the percentage for a percentage one, the hourly rate for an hourly one.",
                        max_digits=18,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensation",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.paycomponent",
                    ),
                ),
            ],
            options={
                "ordering": ["employee", "component", "-effective_from"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gte", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="compensation_dates_in_order",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="payrun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="pay_run_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="pay_period_ends_after_it_starts",
            ),
        ),
        migrations.AddConstraint(
            model_name="payslip",
            constraint=models.UniqueConstraint(
                fields=("run", "employee"), name="one_payslip_per_employee_per_run"
            ),
        ),
    ]
