# Generated by Django 5.2.17 on 2026-09-21 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accountingperiod"),
        ("hr", "0004_paycomponent_payrun_payslip_payslipline_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="employeecompensation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="compensation_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="payslipline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="payslip_line_amount_positive",
            ),
        ),
    ]
