# Generated by Django 5.2.17 on 2026-09-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0006_timesheet_timesheetentry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="pin_digest",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="A keyed digest of the person's shop-floor PIN, never the PIN. Unique, because a station knows who you are from the PIN alone.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
