# Generated by Django 5.2.17 on 2026-09-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0007_employee_pin_digest"),
    ]

    operations = [
        migrations.AddField(
            model_name="paycomponent",
            name="measure",
            field=models.CharField(
                blank=True,
                help_text="For piece work, what is counted: a measure the production side records against a person, such as metres woven.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="payslipline",
            name="quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                editable=False,
                help_text="On piece work, the units this line pays for: what was made to the end of the period less what earlier runs paid.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="paycomponent",
            name="basis",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed amount"),
                    ("percent", "Percentage of taxable gross"),
                    ("per_hour", "Rate per hour"),
                    ("per_unit", "Rate per unit produced"),
                ],
                default="fixed",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="payslipline",
            name="basis",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed amount"),
                    ("percent", "Percentage of taxable gross"),
                    ("per_hour", "Rate per hour"),
                    ("per_unit", "Rate per unit produced"),
                ],
                editable=False,
                max_length=16,
            ),
        ),
    ]
