# Generated by Django 5.2.17 on 2026-10-04 11:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def owed_into(apps, schema_editor):
    """
    Lines already posted: a deduction was owed into the account it
    landed on; an employer contribution into its component's liability
    account, the only record there is of where it went.
    """
    PayslipLine = apps.get_model("hr", "PayslipLine")
    posted = PayslipLine.objects.filter(payslip__run__status="posted",
                                        posted_liability_account__isnull=True)
    for line in posted.filter(kind="deduction").exclude(posted_account__isnull=True):
        line.posted_liability_account_id = line.posted_account_id
        line.save(update_fields=["posted_liability_account"])
    for line in posted.filter(kind="employer_cost").select_related("component"):
        line.posted_liability_account_id = line.component.liability_account_id
        line.save(update_fields=["posted_liability_account"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_gstsettings_job_work_sac"),
        ("hr", "0008_paycomponent_measure_payslipline_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paycomponent",
            name="base_ceiling",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The base is capped here: 15,000 for provident fund.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paycomponent",
            name="base_components",
            field=models.ManyToManyField(
                blank=True,
                help_text="What a percentage or slab is taken of: these components' amounts on the slip. Empty means the taxable gross so far.",
                related_name="+",
                to="hr.paycomponent",
            ),
        ),
        migrations.AddField(
            model_name="paycomponent",
            name="coverage_ceiling",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Applies only while what decides coverage is at or under this: 21,000 for ESI.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paycomponent",
            name="coverage_components",
            field=models.ManyToManyField(
                blank=True,
                help_text="What decides whether it applies at all. Empty means the base. ESI leaves overtime out of deciding, and charges on it all the same.",
                related_name="+",
                to="hr.paycomponent",
            ),
        ),
        migrations.AddField(
            model_name="paycomponent",
            name="coverage_period_months",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Coverage is decided by the first slip in each block of this many months from April, and holds for the block: 6 for ESI.",
            ),
        ),
        migrations.AddField(
            model_name="paycomponent",
            name="remit_by_day",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Day of the following month what is owed must be paid over: 15 for PF and ESI, 7 for TDS.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paycomponent",
            name="rounding",
            field=models.CharField(
                choices=[
                    ("paisa", "To the paisa"),
                    ("rupee", "To the nearest rupee"),
                    ("rupee_up", "Up to the next rupee"),
                ],
                default="paisa",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="payslipline",
            name="posted_liability_account",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="On a deduction or employer contribution, what it was owed into when the run posted: what the liabilities report counts it against.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AlterField(
            model_name="paycomponent",
            name="basis",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed amount"),
                    ("percent", "Percentage of its base (taxable gross unless named)"),
                    ("per_hour", "Rate per hour"),
                    ("per_unit", "Rate per unit produced"),
                    ("slab", "Amount from a slab of its base"),
                ],
                default="fixed",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="payslipline",
            name="basis",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed amount"),
                    ("percent", "Percentage of its base (taxable gross unless named)"),
                    ("per_hour", "Rate per hour"),
                    ("per_unit", "Rate per unit produced"),
                    ("slab", "Amount from a slab of its base"),
                ],
                editable=False,
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="PayComponentSlab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "above",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "up_to",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slabs",
                        to="hr.paycomponent",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["component", "month", "above"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="slab_amount_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("above__gte", 0)),
                        name="slab_above_not_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("up_to__isnull", True),
                            ("up_to__gt", models.F("above")),
                            _connector="OR",
                        ),
                        name="slab_up_to_above_its_floor",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("month__isnull", True),
                            models.Q(("month__gte", 1), ("month__lte", 12)),
                            _connector="OR",
                        ),
                        name="slab_month_is_a_month",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StatutoryRemittance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.DateField(
                        help_text="The month the deductions were made for."
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "liability_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="remittances",
                        to="accounting.payment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "liability_account", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="remittance_amount_positive",
                    )
                ],
            },
        ),
        migrations.RunPython(owed_into, migrations.RunPython.noop),
    ]
