# Generated by Django 5.2.17 on 2026-10-05 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0009_statutory_contributions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={
                "ordering": ["-start_date"],
                "permissions": [
                    ("decide_leaverequest", "Can approve or reject leave requests"),
                    (
                        "view_every_leaverequest",
                        "Can read everyone's leave requests, not only their own and their reports'",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="The login this person signs in with. Decisions they take in the office application (approving a colleague's leave) are taken as this employee, and they read their own requests and their reports'.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
