# Generated by Django 5.2.17 on 2026-10-05 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0010_employee_login"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={
                "ordering": ["-start_date"],
                "permissions": [
                    ("decide_leaverequest", "Can approve or reject leave requests"),
                    (
                        "view_every_leaverequest",
                        "Can read everyone's leave requests, not only their own and their reports'",
                    ),
                    (
                        "decide_unmanaged_leaverequest",
                        "Can decide leave for someone with no manager",
                    ),
                ],
            },
        ),
    ]
