# Generated by Django 5.2.17 on 2026-10-06 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_login_failure_address"),
        ("hr", "0012_decide_any_leave"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabourContractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("licence_number", models.CharField(max_length=32)),
                ("licence_valid_to", models.DateField()),
                (
                    "work_nature",
                    models.CharField(
                        help_text="Loom operation, bag stitching, loading",
                        max_length=128,
                    ),
                ),
                (
                    "max_workers",
                    models.PositiveIntegerField(
                        help_text="As many as the licence allows at once."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "party",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labour_contractor",
                        to="core.party",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["party__name"],
            },
        ),
        migrations.CreateModel(
            name="ContractWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("other", "Other"),
                        ],
                        max_length=8,
                    ),
                ),
                ("designation", models.CharField(blank=True, max_length=64)),
                ("daily_wage", models.DecimalField(decimal_places=2, max_digits=10)),
                ("joined_on", models.DateField()),
                ("left_on", models.DateField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workers",
                        to="hr.labourcontractor",
                    ),
                ),
            ],
            options={
                "ordering": ["contractor", "name", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="labourcontractor",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_workers__gt", 0)),
                name="contractor_licence_covers_someone",
            ),
        ),
        migrations.AddConstraint(
            model_name="contractworker",
            constraint=models.CheckConstraint(
                condition=models.Q(("daily_wage__gt", 0)), name="contract_wage_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="contractworker",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("left_on__isnull", True),
                    ("left_on__gte", models.F("joined_on")),
                    _connector="OR",
                ),
                name="contract_worker_leaves_after_joining",
            ),
        ),
    ]
