# Generated by Django 5.2.17 on 2026-10-06 20:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0013_contract_labour"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="paid_by_attendance",
            field=models.BooleanField(
                default=False,
                help_text="A day-rated worker: paid for the days the attendance register shows and no other, so a pay run waits until every working day of theirs is marked.",
            ),
        ),
        migrations.AlterField(
            model_name="paycomponent",
            name="basis",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed amount"),
                    ("percent", "Percentage of its base (taxable gross unless named)"),
                    ("per_hour", "Rate per hour"),
                    ("per_unit", "Rate per unit produced"),
                    ("overtime", "Rate per overtime hour on the attendance register"),
                    ("slab", "Amount from a slab of its base"),
                ],
                default="fixed",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="payslipline",
            name="basis",
            field=models.CharField(
                choices=[
                    ("fixed", "Fixed amount"),
                    ("percent", "Percentage of its base (taxable gross unless named)"),
                    ("per_hour", "Rate per hour"),
                    ("per_unit", "Rate per unit produced"),
                    ("overtime", "Rate per overtime hour on the attendance register"),
                    ("slab", "Amount from a slab of its base"),
                ],
                editable=False,
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("half_day", "Half a day"),
                            ("absent", "Absent"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        blank=True,
                        help_text="The shift's code, as the floor names it.",
                        max_length=16,
                    ),
                ),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                (
                    "late_minutes",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Worked out from the shift's start where the shift and the time in are known.",
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Overtime agreed for the day, paid at the overtime rate.",
                        max_digits=5,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Entered"),
                            ("import", "From the punch file"),
                        ],
                        default="manual",
                        editable=False,
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["on", "employee_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "on"), name="one_attendance_a_day"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("overtime_hours__gte", 0), ("overtime_hours__lte", 24)
                        ),
                        name="attendance_overtime_in_a_day",
                    ),
                ],
            },
        ),
    ]
