# Generated by Django 5.2.17 on 2026-10-07 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0020_cost_centres"),
        ("hr", "0014_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="centre",
            field=models.ForeignKey(
                blank=True,
                help_text="The cost centre this department's wages are read under in the analytic view (accounting/analytic.py); stamped on the payroll's ledger lines when a run posts.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.costcentre",
            ),
        ),
    ]
