# Generated by Django 5.2.17 on 2026-10-07 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0015_department_centre"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="esi_number",
            field=models.CharField(
                blank=True,
                help_text="The ESI insurance number (IP number), ten digits: what the monthly contribution file names the person by.",
                max_length=17,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="uan",
            field=models.CharField(
                blank=True,
                help_text="The provident fund's Universal Account Number, twelve digits: what the monthly ECR file names the person by.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="paycomponent",
            name="statutory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not a statutory line"),
                    ("pf", "Provident fund, the employee's share"),
                    (
                        "pf_employer",
                        "Provident fund, the employer's share (pension inside it unless named)",
                    ),
                    ("eps", "Pension (EPS), the employer's share named on its own"),
                    ("esi", "ESI, the employee's share"),
                    ("esi_employer", "ESI, the employer's share"),
                    ("pt", "Professional tax"),
                ],
                default="",
                help_text="Which statutory line this is, so the monthly PF and ESI files know which of the slip's lines to read.",
                max_length=16,
            ),
        ),
    ]
