# Generated by Django 5.2.17 on 2026-10-07 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0021_budgets_recurring_periods"),
        ("hr", "0017_custom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, editable=False, max_length=32)),
                ("claim_date", models.DateField()),
                ("purpose", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "decision_note",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                ("paid_on", models.DateField(blank=True, editable=False, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_claims",
                        to="hr.employee",
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "paid_from",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="The cash or bank account it was paid from.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-claim_date", "-id"],
                "permissions": [
                    (
                        "decide_expenseclaim",
                        "Can approve or reject an expense claim of a report",
                    ),
                    (
                        "decide_any_expenseclaim",
                        "Can approve or reject anyone's expense claim",
                    ),
                    ("view_every_expenseclaim", "Can read everyone's expense claims"),
                    ("pay_expenseclaim", "Can pay an approved expense claim"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExpenseLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("spent_on", models.DateField()),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "receipt_reference",
                    models.CharField(
                        blank=True,
                        help_text="The bill or ticket number, if there is one.",
                        max_length=64,
                    ),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="hr.expenseclaim",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["spent_on", "id"],
            },
        ),
        migrations.CreateModel(
            name="JobOpening",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "openings",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="How many people are wanted."
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("on_hold", "On hold"),
                            ("filled", "Filled"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("opened_on", models.DateField()),
                ("closed_on", models.DateField(blank=True, editable=False, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="openings",
                        to="hr.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("applied_on", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walk_in", "Walk-in"),
                            ("referral", "Referral"),
                            ("agency", "Agency"),
                            ("portal", "Job portal"),
                            ("other", "Other"),
                        ],
                        default="walk_in",
                        max_length=12,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("applied", "Applied"),
                            ("screening", "Screening"),
                            ("interview", "Interview"),
                            ("offered", "Offered"),
                            ("hired", "Hired"),
                            ("rejected", "Rejected"),
                        ],
                        default="applied",
                        max_length=12,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Out of five, after the interview.",
                        null=True,
                    ),
                ),
                (
                    "expected_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="A month.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "rejected_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applicants",
                        to="hr.jobopening",
                    ),
                ),
            ],
            options={
                "ordering": ["opening", "applied_on", "id"],
            },
        ),
        migrations.CreateModel(
            name="Appraisal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("acknowledged", "Acknowledged"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Out of five.", null=True
                    ),
                ),
                ("strengths", models.TextField(blank=True)),
                ("improvements", models.TextField(blank=True)),
                ("goals", models.TextField(blank=True, help_text="For the next span.")),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("employee_comment", models.TextField(blank=True, editable=False)),
                (
                    "acknowledged_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appraisals",
                        to="hr.employee",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appraisals_given",
                        to="hr.employee",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start", "-id"],
                "permissions": [
                    ("view_every_appraisal", "Can read everyone's appraisals"),
                    ("acknowledge_appraisal", "Can acknowledge one's own appraisal"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "period_start"),
                        name="one_appraisal_per_employee_per_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("rating__isnull", True),
                            models.Q(("rating__gte", 1), ("rating__lte", 5)),
                            _connector="OR",
                        ),
                        name="appraisal_rating_out_of_five",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("period_end__gte", models.F("period_start"))
                        ),
                        name="appraisal_period_in_order",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="expenseclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="unique_expense_claim_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="expenseline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="expense_line_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="jobopening",
            constraint=models.CheckConstraint(
                condition=models.Q(("openings__gte", 1)), name="opening_wants_someone"
            ),
        ),
        migrations.AddConstraint(
            model_name="applicant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating__isnull", True),
                    models.Q(("rating__gte", 1), ("rating__lte", 5)),
                    _connector="OR",
                ),
                name="applicant_rating_out_of_five",
            ),
        ),
    ]
