# Generated by Django 5.2.17 on 2026-10-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0019_claims_paid_from_hold_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Hours handed in for hourly pay when the run was calculated; empty when they were read from approved timesheets. Posting works the slip out again from these.",
                max_digits=10,
                null=True,
            ),
        ),
    ]
