# Generated by Django 5.2.17 on 2026-10-10 20:38

from django.db import migrations, models


def keep_what_each_claim_still_names(apps, schema_editor):
    """Its current entry, its last reversal and what that reversed: all a claim still names (O164)."""
    ExpenseClaim = apps.get_model("hr", "ExpenseClaim")
    for claim in ExpenseClaim.objects.exclude(journal_entry__isnull=True, voided_entry__isnull=True):
        named = [claim.journal_entry_id, claim.voided_entry_id,
                 claim.voided_entry.reverses_id if claim.voided_entry_id else None]
        claim.bank_entries.add(*[pk for pk in named if pk])


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0024_statement_line_matches_a_booked_entry"),
        ("hr", "0020_payslip_hours_handed_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="expenseclaim",
            name="bank_entries",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                help_text="Every entry a payment of this claim, or a reversal of one, posted: the bank's record of it.",
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.RunPython(keep_what_each_claim_still_names, migrations.RunPython.noop),
    ]
