# Generated by Django 5.2.17 on 2026-09-27 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitQuantityCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("BAG", "Bags"),
                            ("BAL", "Bale"),
                            ("BDL", "Bundles"),
                            ("BOX", "Box"),
                            ("BTL", "Bottles"),
                            ("CTN", "Cartons"),
                            ("DOZ", "Dozens"),
                            ("GMS", "Grammes"),
                            ("KGS", "Kilograms"),
                            ("KLR", "Kilolitre"),
                            ("LTR", "Litres"),
                            ("MTR", "Metres"),
                            ("MTS", "Metric ton"),
                            ("NOS", "Numbers"),
                            ("PAC", "Packs"),
                            ("PCS", "Pieces"),
                            ("QTL", "Quintal"),
                            ("ROL", "Rolls"),
                            ("SQF", "Square feet"),
                            ("SQM", "Square metres"),
                            ("TON", "Tonnes"),
                            ("UNT", "Units"),
                            ("OTH", "Others"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gst_uqc",
                        to="core.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": [("compile_returns", "Can compile GST returns")],
            },
        ),
    ]
