# Generated by Django 5.2.17 on 2026-09-28 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gst", "0001_initial"),
        ("manufacturing", "0038_test_certificates"),
        ("sales", "0033_customer_material_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("payload", models.JSONField(editable=False)),
                ("irn", models.CharField(blank=True, editable=False, max_length=64)),
                (
                    "ack_number",
                    models.CharField(blank=True, editable=False, max_length=20),
                ),
                (
                    "ack_date",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("signed_qr", models.TextField(blank=True, editable=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="einvoice",
                        to="sales.invoice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "e-invoice",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("irn", ""), _negated=True),
                        fields=("irn",),
                        name="einvoice_irn_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EwayBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("1", "Road"),
                            ("2", "Rail"),
                            ("3", "Air"),
                            ("4", "Ship"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                (
                    "distance_km",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="0 lets the portal work it out from the two PINs.",
                    ),
                ),
                ("transporter_id", models.CharField(blank=True, max_length=15)),
                ("transporter_name", models.CharField(blank=True, max_length=100)),
                ("vehicle_number", models.CharField(blank=True, max_length=15)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("R", "Regular"), ("O", "Over-dimensional cargo")],
                        default="R",
                        max_length=1,
                    ),
                ),
                ("transport_doc_number", models.CharField(blank=True, max_length=15)),
                ("transport_doc_date", models.DateField(blank=True, null=True)),
                ("payload", models.JSONField(editable=False)),
                ("required", models.BooleanField(editable=False)),
                ("required_because", models.CharField(editable=False, max_length=255)),
                ("number", models.CharField(blank=True, editable=False, max_length=12)),
                (
                    "generated_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "valid_until",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "cancel_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Duplicate"),
                            ("2", "Order cancelled"),
                            ("3", "Data entry mistake"),
                            ("4", "Others"),
                        ],
                        editable=False,
                        max_length=1,
                    ),
                ),
                (
                    "cancel_remarks",
                    models.CharField(blank=True, editable=False, max_length=100),
                ),
                (
                    "challan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eway_bills",
                        to="manufacturing.jobworkchallan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="eway_bills",
                        to="sales.invoice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "e-way bill",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("invoice__isnull", False), ("challan__isnull", True)
                            ),
                            models.Q(
                                ("invoice__isnull", True), ("challan__isnull", False)
                            ),
                            _connector="OR",
                        ),
                        name="eway_bill_one_document",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("number", ""), _negated=True),
                        fields=("number",),
                        name="eway_bill_number_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("cancelled_at__isnull", True)),
                        fields=("invoice",),
                        name="one_standing_eway_bill_per_invoice",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("cancelled_at__isnull", True)),
                        fields=("challan",),
                        name="one_standing_eway_bill_per_challan",
                    ),
                ],
            },
        ),
    ]
