# Generated by Django 5.2.17 on 2026-09-28 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gst", "0002_einvoice_ewaybill"),
        (
            "manufacturing",
            "0041_customermaterialreceipt_customermaterialreceiptline_and_more",
        ),
        ("sales", "0033_customer_material_rules"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ewaybill",
            name="eway_bill_one_document",
        ),
        migrations.AddField(
            model_name="ewaybill",
            name="delivery",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="eway_bills",
                to="sales.delivery",
            ),
        ),
        migrations.AddConstraint(
            model_name="ewaybill",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("invoice__isnull", False),
                        ("challan__isnull", True),
                        ("delivery__isnull", True),
                    ),
                    models.Q(
                        ("invoice__isnull", True),
                        ("challan__isnull", False),
                        ("delivery__isnull", True),
                    ),
                    models.Q(
                        ("invoice__isnull", True),
                        ("challan__isnull", True),
                        ("delivery__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="eway_bill_one_document",
            ),
        ),
        migrations.AddConstraint(
            model_name="ewaybill",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cancelled_at__isnull", True)),
                fields=("delivery",),
                name="one_standing_eway_bill_per_delivery",
            ),
        ),
    ]
