# Generated by Django 5.2.17 on 2026-10-07 08:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gst", "0003_remove_ewaybill_eway_bill_one_document_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Gstr2bStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period",
                    models.CharField(help_text="YYYY-MM", max_length=7, unique=True),
                ),
                (
                    "gstin",
                    models.CharField(
                        blank=True,
                        help_text="The registration the file is for.",
                        max_length=15,
                    ),
                ),
                (
                    "generated_on",
                    models.DateField(
                        blank=True, help_text="The portal's generation date.", null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(blank=True, help_text="json or csv", max_length=8),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GSTR-2B statement",
                "ordering": ["-period"],
            },
        ),
        migrations.CreateModel(
            name="Gstr2bLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_gstin", models.CharField(max_length=15)),
                ("supplier_name", models.CharField(blank=True, max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("invoice", "Invoice"),
                            ("credit_note", "Credit note"),
                            ("debit_note", "Debit note"),
                        ],
                        default="invoice",
                        max_length=16,
                    ),
                ),
                ("number", models.CharField(max_length=64)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "taxable",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "igst",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "cgst",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "sgst",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                (
                    "cess",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=18
                    ),
                ),
                ("reverse_charge", models.BooleanField(default=False)),
                ("itc_available", models.BooleanField(default=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Why the portal says the credit is not available.",
                        max_length=255,
                    ),
                ),
                ("irn", models.CharField(blank=True, max_length=64)),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="gst.gstr2bstatement",
                    ),
                ),
            ],
            options={
                "ordering": ["supplier_gstin", "date", "number"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("number", ""), _negated=True),
                        fields=("statement", "supplier_gstin", "kind", "number"),
                        name="one_2b_line_per_document",
                    )
                ],
            },
        ),
    ]
