# Generated by Django 5.2.17 on 2026-09-20 13:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0009_bankstatement_bankstatementline"),
        ("core", "0014_paymenttermsline"),
        ("purchasing", "0028_purchaserequisitionline_expense_account"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("default_life_months", models.PositiveSmallIntegerField(default=60)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("straight_line", "Straight line"),
                            ("none", "Not depreciated"),
                        ],
                        default="straight_line",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "accumulated_account",
                    models.ForeignKey(
                        help_text="Depreciation charged to date (a contra-asset).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "asset_account",
                    models.ForeignKey(
                        help_text="What the asset cost (an asset).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disposal_account",
                    models.ForeignKey(
                        blank=True,
                        help_text="Gain or loss on disposal. Without one, disposal is refused rather than quietly written to depreciation.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "expense_account",
                    models.ForeignKey(
                        help_text="This period's depreciation (an expense).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.account",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "asset categories",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, editable=False, max_length=32)),
                ("name", models.CharField(max_length=255)),
                ("acquisition_date", models.DateField()),
                (
                    "in_service_date",
                    models.DateField(
                        blank=True,
                        help_text="Depreciation starts here, not at acquisition — a machine in a crate is not being consumed.",
                        null=True,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "salvage_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="What it will still be worth at the end of its life.",
                        max_digits=18,
                    ),
                ),
                ("life_months", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_service", "In service"),
                            ("disposed", "Disposed"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "disposed_on",
                    models.DateField(blank=True, editable=False, null=True),
                ),
                (
                    "bill_line",
                    models.ForeignKey(
                        blank=True,
                        help_text="The purchase this asset was capitalised from, when there was one.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="purchasing.billline",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets",
                        to="assets.assetcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "disposal_entry",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assets_sold",
                        to="core.party",
                    ),
                ),
            ],
            options={
                "ordering": ["-acquisition_date", "-id"],
                "permissions": [("dispose_fixedasset", "Can dispose of fixed assets")],
            },
        ),
        migrations.CreateModel(
            name="DepreciationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_end", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "journal_entry",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="depreciation_entries",
                        to="assets.fixedasset",
                    ),
                ),
            ],
            options={
                "ordering": ["period_end", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="unique_asset_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("cost__gt", 0)), name="asset_cost_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("salvage_value__gte", 0)),
                name="asset_salvage_not_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="depreciationentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="depreciation_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="depreciationentry",
            constraint=models.UniqueConstraint(
                fields=("asset", "period_end"), name="one_charge_per_asset_and_period"
            ),
        ),
    ]
