# Generated by Django 5.2.17 on 2026-09-27 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_accountingperiod"),
        ("assets", "0001_initial"),
        ("core", "0016_company_net_pay_account"),
        ("purchasing", "0038_billline_accrued_base_billline_accrued_doc_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="capitalisation_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The entry that moved this asset's cost onto the asset account, when it came from a bill — kept so that it can be reversed rather than left behind.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AlterField(
            model_name="fixedasset",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("in_service", "In service"),
                    ("disposed", "Disposed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("salvage_value__lt", models.F("cost"))),
                name="asset_salvage_below_cost",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("in_service_date__isnull", True),
                    ("in_service_date__gte", models.F("acquisition_date")),
                    _connector="OR",
                ),
                name="asset_in_service_after_acquisition",
            ),
        ),
    ]
