# Generated by Django 5.2.17 on 2026-10-04 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_gstsettings_job_work_sac"),
        ("assets", "0002_fixedasset_capitalisation_entry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="depreciationentry",
            name="reversal",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Set when the asset was disposed of before this month: the entry that took the charge back.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
    ]
