# Generated by Django 5.2.17 on 2026-10-07 06:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_depreciation_reversal"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="depreciated_before",
            field=models.DateField(
                blank=True,
                help_text="Depreciation to this date was taken in the old system and is carried in the opening balances; the months after it are this system's. Set when the register is brought in at go-live, and never after.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="opening_depreciation",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="What the old system had depreciated by that date, counted in what is accumulated here; its journal side is in the opening balances.",
                max_digits=18,
            ),
        ),
    ]
