# Generated by Django 5.2.17 on 2026-10-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_depreciated_before_go_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="extra",
            field=models.JSONField(
                blank=True, default=dict, help_text="The custom fields' values, by key."
            ),
        ),
    ]
