# Generated by Django 5.2.17 on 2026-10-08 02:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0022_statement_line_returns_a_payment"),
        ("assets", "0005_custom_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="depreciationentry",
            name="one_charge_per_asset_and_period",
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="reinstatement_entry",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The entry that took back a disposal recorded in error, when one was.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.journalentry",
            ),
        ),
        migrations.AddConstraint(
            model_name="depreciationentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reversal__isnull", True)),
                fields=("asset", "period_end"),
                name="one_standing_charge_per_asset_and_period",
            ),
        ),
    ]
