# Generated by Django 5.2.17 on 2026-10-08 08:06

import django.db.models.deletion
from django.db import migrations, models


def keep_what_each_stands_on(apps, schema_editor):
    """
    Assets already on the books keep what they stand on. The asset account
    is the one its capitalisation debited, where there was one: that entry
    is the record of where its cost went. Otherwise, and for the
    accumulated account and the method, its category's as it stands, which
    is what each of its entries read until now. A draft keeps the rest when
    it goes into service.
    """
    FixedAsset = apps.get_model("assets", "FixedAsset")
    JournalLine = apps.get_model("accounting", "JournalLine")
    for asset in FixedAsset.objects.select_related("category"):
        if asset.capitalisation_entry_id:
            debited = JournalLine.objects.filter(entry_id=asset.capitalisation_entry_id, debit__gt=0).first()
            if debited is not None:
                asset.asset_account_id = debited.account_id
        if asset.status in ("in_service", "disposed"):
            asset.asset_account_id = asset.asset_account_id or asset.category.asset_account_id
            asset.accumulated_account_id = asset.category.accumulated_account_id
            asset.method = asset.category.method
        asset.save(update_fields=["asset_account", "accumulated_account", "method"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0023_account_holds_money"),
        ("assets", "0006_disposal_in_error_reinstated"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="accumulated_account",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Where its depreciation is held: its category's when it went into service. Every charge is credited here and its disposal clears it.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="asset_account",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The account its cost stands on: the one its capitalisation debited, or its category's when it went into service. Its disposal takes the cost off this one, whatever the category says by then.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("straight_line", "Straight line"),
                    ("none", "Not depreciated"),
                ],
                editable=False,
                help_text="How it is depreciated: its category's when it went into service. Its charges are worked out from this; a change to the category is for assets to come.",
                max_length=16,
            ),
        ),
        migrations.RunPython(keep_what_each_stands_on, migrations.RunPython.noop),
    ]
