# Generated by Django 5.2.17 on 2026-10-08 08:06

import django.db.models.deletion
from django.db import migrations, models


# The methods in this schema that post a monthly charge. Straight line is the only one, so an
# asset with charges was depreciated by it, whatever its category says now.
CHARGING_METHODS = ("straight_line",)


def keep_what_each_stands_on(apps, schema_editor):
    """
    Assets already on the books keep what they stand on, read from what
    they posted wherever that says it:

    - The asset account is the one its capitalisation debited, where there
      was one: that entry is the record of where its cost went.
    - The accumulated account is the one its posted charges credited (those
      still standing, or, if a disposal took them all back, all of them).
      The category can have moved since: a lathe charged to 1590 from January
      to March, whose category was given 1595 in April, read 1595, and its
      disposal would have left 1590 holding 3,000 for good.
    - The method: an asset with charges was depreciated, and straight line is
      the only method here that charges, so it is straight line even where
      its category has since been switched to not depreciated (which would
      stop it with its life still to run).

    Otherwise, its category's as it stands, which is what each of its
    entries read until now. A draft keeps the rest when it goes into
    service. What cannot be told from the books is printed for the keeper,
    by asset number: charges credited to more than one account (it is kept
    on the last one's), and an asset its category says is not depreciated
    that the old system depreciated and this one has charged nothing (its
    method is left as its category's).
    """
    FixedAsset = apps.get_model("assets", "FixedAsset")
    DepreciationEntry = apps.get_model("assets", "DepreciationEntry")
    JournalLine = apps.get_model("accounting", "JournalLine")
    notes = []
    for asset in FixedAsset.objects.select_related("category").order_by("pk"):
        name = asset.number or f"FA-draft-{asset.pk}"
        if asset.capitalisation_entry_id:
            debited = JournalLine.objects.filter(entry_id=asset.capitalisation_entry_id, debit__gt=0).first()
            if debited is not None:
                asset.asset_account_id = debited.account_id
        if asset.status in ("in_service", "disposed"):
            asset.asset_account_id = asset.asset_account_id or asset.category.asset_account_id
            charges = DepreciationEntry.objects.filter(asset_id=asset.pk)
            standing = charges.filter(reversal__isnull=True)
            credited = []
            for charge in (standing if standing.exists() else charges).order_by("period_end", "pk"):
                line = JournalLine.objects.filter(entry_id=charge.journal_entry_id, credit__gt=0) \
                    .select_related("account").first()
                if line is not None:
                    credited.append(line.account)
            if credited:
                asset.accumulated_account_id = credited[-1].pk
                codes = sorted({account.code for account in credited})
                if len(codes) > 1:
                    notes.append(f"{name} {asset.name}: its charges were credited to {', '.join(codes)}; it is "
                                 f"kept on {credited[-1].code}, where its last charge went. Move what the others "
                                 "hold for it there by journal.")
            else:
                asset.accumulated_account_id = asset.category.accumulated_account_id
            if charges.exists() and asset.category.method not in CHARGING_METHODS:
                asset.method = CHARGING_METHODS[0]
            else:
                asset.method = asset.category.method
                if asset.method not in CHARGING_METHODS and not charges.exists() and asset.opening_depreciation:
                    notes.append(f"{name} {asset.name}: its category says not depreciated, it has charged nothing "
                                 f"here, and the old system depreciated it ({asset.opening_depreciation}). Its "
                                 "method is left as its category's; set it if it is to be depreciated.")
        asset.save(update_fields=["asset_account", "accumulated_account", "method"])
    if notes:
        print("\nassets.0007: for the keeper to set by hand:\n  " + "\n  ".join(notes))


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0023_account_holds_money"),
        ("assets", "0006_disposal_in_error_reinstated"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="accumulated_account",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="Where its depreciation is held: its category's when it went into service. Every charge is credited here and its disposal clears it.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="asset_account",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The account its cost stands on: the one its capitalisation debited, or its category's when it went into service. Its disposal takes the cost off this one, whatever the category says by then.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="accounting.account",
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("straight_line", "Straight line"),
                    ("none", "Not depreciated"),
                ],
                editable=False,
                help_text="How it is depreciated: its category's when it went into service. Its charges are worked out from this; a change to the category is for assets to come.",
                max_length=16,
            ),
        ),
        migrations.RunPython(keep_what_each_stands_on, migrations.RunPython.noop),
    ]
