# Generated by Django 5.2.17 on 2026-09-22 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("inventory", "0026_stockvaluationsnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Characteristic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("measured", "Measured against limits"),
                            ("attribute", "Present or absent"),
                        ],
                        default="measured",
                        max_length=16,
                    ),
                ),
                (
                    "decimal_places",
                    models.PositiveSmallIntegerField(
                        default=2,
                        help_text="How precisely the instrument reads. A balance to two places and a micrometer to four are different instruments and a report that shows both to the same precision is claiming something about one of them.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        blank=True,
                        help_text="What the reading is in. Required for anything measured — a number with no unit is the mistake this codebase keeps finding; left blank for something that is simply present or absent.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.unitofmeasure",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="InspectionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="A batch of this item is not released until somebody has measured it and passed it. Off for an item where the plan is advisory — a record of what was checked rather than a gate.",
                    ),
                ),
                (
                    "is_computed",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        help_text="Set when a product specification works this plan out. Such a plan refuses to be edited by hand: the edit would survive until the next rebuild and no longer.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspection_plans",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["item__sku"],
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, max_length=32)),
                ("inspected_on", models.DateField()),
                (
                    "disposition",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accept", "Accepted"),
                            ("concession", "Accepted by concession"),
                            ("rework", "Held for rework"),
                            ("reject", "Rejected"),
                        ],
                        help_text="What was decided. Not the same question as whether it passed: a roll at 84 against 87.5 has failed, and the customer may still take it at a discount.",
                        max_length=16,
                    ),
                ),
                ("decision_note", models.CharField(blank=True, max_length=255)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pass", "Within specification"),
                            ("fail", "Outside specification"),
                        ],
                        editable=False,
                        help_text="Worked out from the readings when this posted, and frozen. The plan's limits will move; what this batch was judged against must not.",
                        max_length=8,
                    ),
                ),
                ("posted", models.BooleanField(default=False)),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("voided_reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who took a batch that did not pass. Required for a concession: an out-of-specification batch released by nobody in particular is what there is nothing to answer with when the next one is argued about.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quality_decisions",
                        to="core.party",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections_taken",
                        to="core.party",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        help_text="The batch that was measured. A lot rather than a document, because a lot is the subject every module already shares and attaching to one of their documents would make this app depend on that module.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections",
                        to="inventory.lot",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections",
                        to="quality.inspectionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-inspected_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PlanLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="What it is supposed to be. Recorded even where the limits do the gating, because the distance from target is what a process is steered by and a pass/fail is not.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "lower_limit",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "upper_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="One of the two may be blank: a tensile strength has a floor and no ceiling, and a contamination count has a ceiling and no floor. Both blank would be a line that cannot fail.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "sample_size",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many to look at. Nobody weighs every sack.",
                    ),
                ),
                (
                    "evaluation",
                    models.CharField(
                        choices=[
                            ("every", "Every reading must pass"),
                            ("mean", "The average must pass"),
                        ],
                        default="every",
                        help_text="Whether every reading must be inside the limits or only their average. Both are used in practice and they disagree, so the plan says which rather than the reader guessing.",
                        max_length=8,
                    ),
                ),
                (
                    "derived_from",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Which figure on the specification produced this line — 'gsm', 'denier', 'bag_weight'. Recorded so that whatever wants to read the measured GSM back can find it without matching on a name somebody may translate.",
                        max_length=32,
                    ),
                ),
                ("line_number", models.PositiveIntegerField(default=0)),
                (
                    "characteristic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_lines",
                        to="quality.characteristic",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="quality.inspectionplan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "line_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="For a measured characteristic. Blank for one that is simply present or absent.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "present",
                    models.BooleanField(
                        blank=True,
                        help_text="For a characteristic that is present or absent.",
                        null=True,
                    ),
                ),
                (
                    "sample_reference",
                    models.CharField(
                        blank=True,
                        help_text="Which roll, which bag off the stack. Kept so a second opinion can be taken on the same sample.",
                        max_length=64,
                    ),
                ),
                (
                    "lower_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        editable=False,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "upper_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        editable=False,
                        help_text="The limits as they stood when this was judged, frozen here. A tolerance tightened next year must not retrospectively fail a batch that was inside the one it was sold to.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("passed", models.BooleanField(blank=True, editable=False, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="quality.inspection",
                    ),
                ),
                (
                    "plan_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="readings",
                        to="quality.planline",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["inspection", "plan_line", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="inspectionplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("item",),
                name="one_active_plan_per_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspection",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="inspection_number_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="planline",
            constraint=models.UniqueConstraint(
                fields=("plan", "characteristic"),
                name="one_plan_line_per_characteristic",
            ),
        ),
        migrations.AddConstraint(
            model_name="planline",
            constraint=models.CheckConstraint(
                condition=models.Q(("sample_size__gt", 0)), name="sample_size_positive"
            ),
        ),
    ]
