# Generated by Django 5.2.17 on 2026-09-26 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_stockvaluationsnapshot"),
        ("quality", "0002_qualitysettings"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="inspectionplan",
            name="one_active_plan_per_item",
        ),
        migrations.AddField(
            model_name="inspectionplan",
            name="valid_from",
            field=models.DateField(
                blank=True,
                help_text="The first day these limits apply. Blank is from the beginning.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inspectionplan",
            name="valid_to",
            field=models.DateField(
                blank=True,
                help_text="The last day these limits apply. Blank is open-ended.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="inspectionplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("valid_to__isnull", True)),
                fields=("item",),
                name="one_open_ended_plan_per_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspectionplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("valid_from__isnull", True)),
                fields=("item",),
                name="one_unstarted_plan_per_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="inspectionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_to__isnull", True),
                    ("valid_to__gte", models.F("valid_from")),
                    _connector="OR",
                ),
                name="plan_window_runs_forwards",
            ),
        ),
    ]
