# Generated by Django 5.2.17 on 2026-09-28 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0003_remove_inspectionplan_one_active_plan_per_item_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="characteristic",
            name="needs_calibrated_instrument",
            field=models.BooleanField(
                default=False,
                help_text="Every reading names the instrument it was taken on, and that instrument is in calibration on the day.",
            ),
        ),
        migrations.CreateModel(
            name="Calibration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(blank=True, editable=False, max_length=32)),
                ("calibrated_on", models.DateField()),
                (
                    "due_on",
                    models.DateField(
                        blank=True,
                        help_text="When it is due again. Left blank, the instrument's interval on.",
                        null=True,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pass", "Found in tolerance"),
                            ("adjusted", "Found out of tolerance and adjusted"),
                            ("fail", "Out of tolerance; taken out of service"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "performed_by",
                    models.CharField(
                        help_text="The lab or the person who did it.", max_length=128
                    ),
                ),
                ("certificate_reference", models.CharField(blank=True, max_length=64)),
                (
                    "traceable_to",
                    models.CharField(
                        blank=True,
                        help_text="The reference standard, e.g. NABL weights.",
                        max_length=128,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("posted", models.BooleanField(default=False, editable=False)),
                (
                    "posted_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "voided_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-calibrated_on", "-id"],
            },
        ),
        migrations.AddField(
            model_name="reading",
            name="calibration",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                help_text="The calibration the instrument was under when this posted, frozen.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="readings",
                to="quality.calibration",
            ),
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("serial_number", models.CharField(blank=True, max_length=64)),
                ("location", models.CharField(blank=True, max_length=128)),
                (
                    "interval_days",
                    models.PositiveIntegerField(
                        help_text="How long a calibration holds, unless the calibration says less."
                    ),
                ),
                (
                    "range_low",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                (
                    "range_high",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="What it was calibrated across. A reading outside it was never checked.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "measures",
                    models.ManyToManyField(
                        blank=True,
                        help_text="What it may be used for. Blank, anything.",
                        related_name="instruments",
                        to="quality.characteristic",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="calibration",
            name="instrument",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="calibrations",
                to="quality.instrument",
            ),
        ),
        migrations.AddField(
            model_name="reading",
            name="instrument",
            field=models.ForeignKey(
                blank=True,
                help_text="What it was measured on.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="readings",
                to="quality.instrument",
            ),
        ),
        migrations.AddConstraint(
            model_name="instrument",
            constraint=models.CheckConstraint(
                condition=models.Q(("interval_days__gt", 0)),
                name="instrument_interval_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="instrument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("range_low__isnull", True),
                    ("range_high__isnull", True),
                    ("range_low__lt", models.F("range_high")),
                    _connector="OR",
                ),
                name="instrument_range_in_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="calibration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("number", ""), _negated=True),
                fields=("number",),
                name="calibration_number_unique",
            ),
        ),
    ]
