# Generated by Django 5.2.17 on 2026-09-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quality", "0004_characteristic_needs_calibrated_instrument_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspection",
            name="lot_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="How many units the sample was drawn from. Needed where a line samples by AQL; left blank for a counted item, what is on hand.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="inspection",
            name="sampling",
            field=models.JSONField(
                blank=True,
                default=dict,
                editable=False,
                help_text="The sampling plan each AQL line was judged by, frozen at posting.",
            ),
        ),
        migrations.AddField(
            model_name="planline",
            name="aql",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Acceptance quality limit, per cent nonconforming. Given, the sample and how many may fail come from the lot size (ISO 2859-1, normal, single sampling) and `sample_size` is not used.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planline",
            name="inspection_level",
            field=models.CharField(
                default="II",
                help_text="General I, II, III or special S-1 to S-4. II unless the buyer says.",
                max_length=4,
            ),
        ),
    ]
