# Generated by Django 5.2.17 on 2026-09-22 09:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0016_company_net_pay_account"),
        ("inventory", "0026_stockvaluationsnapshot"),
        ("manufacturing", "0012_bagspecification_inspection_plan_and_more"),
        ("purchasing", "0035_purchaseorderline_bom_and_more"),
        ("sales", "0030_salesorderline_delivery_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("make", "Make"), ("buy", "Buy")], max_length=8
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="In the item's stocking unit, which is the unit the netting was done in. A plan that mixes a sales line's bales with a bill of materials' kilos nets neither.",
                        max_digits=18,
                    ),
                ),
                (
                    "needed_by",
                    models.DateField(help_text="The date the shortage bites."),
                ),
                (
                    "release_on",
                    models.DateField(
                        help_text="`needed_by` less the lead time. A date in the past is not moved forward to today: how late the plan already is, is the number a planner needs."
                    ),
                ),
                ("lead_days", models.PositiveIntegerField()),
                (
                    "level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Low-level code; the order this was planned in.",
                    ),
                ),
                (
                    "rounded_up_by",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        help_text="How much of this quantity nothing asked for, because a lot multiple rounded it up. Shown rather than buried, because it is stock the plan chose to carry.",
                        max_digits=18,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("suggested", "Suggested"),
                            ("firmed", "Firmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="suggested",
                        max_length=12,
                    ),
                ),
                (
                    "firmed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        blank=True,
                        help_text="The bill of materials a make was exploded against, frozen because it is computed from a specification and the specification will change.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.billofmaterials",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planned_orders",
                        to="inventory.item",
                    ),
                ),
                (
                    "requisition_line",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planned_from",
                        to="purchasing.purchaserequisitionline",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who a buy was priced and lead-timed against.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.party",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planned_from",
                        to="manufacturing.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "level", "needed_by", "item__sku", "id"],
            },
        ),
        migrations.CreateModel(
            name="PlannedDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("sales", "Sales order"),
                            ("work_order", "Open work order"),
                            ("planned", "Another planned order"),
                            ("safety", "Safety stock"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="How much of the planned order this reason accounts for, in the item's stocking unit.",
                        max_digits=18,
                    ),
                ),
                ("needed_by", models.DateField()),
                ("line_number", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sales_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_demands",
                        to="sales.salesorderline",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_demands",
                        to="manufacturing.workorder",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The planned order whose components this demand is part of.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="planning.plannedorder",
                    ),
                ),
                (
                    "planned_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demands",
                        to="planning.plannedorder",
                    ),
                ),
            ],
            options={
                "ordering": ["planned_order", "line_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="PlanningRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "planned_on",
                    models.DateField(
                        help_text="The date the plan treats as today. Everything due before it is already late."
                    ),
                ),
                ("horizon_end", models.DateField()),
                (
                    "ran_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "cut_links",
                    models.TextField(
                        blank=True,
                        editable=False,
                        help_text="Bill-of-materials links this run had to break to give every item a level, one per line. A cut link means that item's demand was netted against stock and firm supply only.",
                    ),
                ),
                (
                    "deferred_demand",
                    models.TextField(
                        blank=True,
                        editable=False,
                        help_text="Dependent demand this run could not net, because the item it was for had already been planned. A consequence of a cut link, and the one thing a planner must read before trusting the rest.",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_runs",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-ran_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="plannedorder",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="planning.planningrun",
            ),
        ),
        migrations.CreateModel(
            name="PlanningSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "horizon_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="How far ahead to plan. Demand beyond this is left alone: an order for a date further out than anything can be bought or made for is not a shortage yet, and reporting it as one fills the list with noise.",
                    ),
                ),
                (
                    "default_buy_lead_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Used when no agreed vendor price names a lead time. Left empty, an item with no agreed lead time refuses to be planned rather than being planned as if it arrived the day it was ordered.",
                        null=True,
                    ),
                ),
                (
                    "default_make_lead_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Used when a bill of materials has no routing, so nothing can compute how long a run takes.",
                        null=True,
                    ),
                ),
                (
                    "queue_days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Added to every computed run time to allow for waiting for a machine. A stated allowance, because nothing here schedules against a machine's real backlog.",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisition_requester",
                    models.ForeignKey(
                        blank=True,
                        help_text="Whose name a firmed buy is raised in. A requisition with no requester is a request from nobody, which no approver can act on.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.party",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "planning settings",
            },
        ),
        migrations.AddConstraint(
            model_name="plannedorder",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="planned_order_quantity_positive",
            ),
        ),
    ]
