# Generated by Django 5.2.17 on 2026-09-22 10:31

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0012_bagspecification_inspection_plan_and_more"),
        ("planning", "0001_initial"),
        ("sales", "0030_salesorderline_delivery_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="plannedorder",
            name="rounded_up_by",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0"),
                help_text="How much of this quantity nothing asked for: what rounding the order up added, to a whole bag or pallet or to the precision a quantity is stored at. Shown rather than buried, because it is stock the plan chose to carry.",
                max_digits=18,
            ),
        ),
        migrations.AddConstraint(
            model_name="planneddemand",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="planned_demand_quantity_positive",
            ),
        ),
    ]
