# Generated by Django 5.2.17 on 2026-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_alter_plannedorder_rounded_up_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planningsettings",
            name="holiday_region",
            field=models.CharField(
                blank=True,
                help_text="Which public holiday list shuts this plant. Blank takes the company-wide one only.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="planningsettings",
            name="working_days",
            field=models.CharField(
                default="1234567",
                help_text="Which days this plant works, as ISO weekday numbers — 1 for Monday through 7 for Sunday. Run times are counted against this; a vendor's quoted lead time is not, because their weekends are already inside the number they quoted.",
                max_length=7,
            ),
        ),
    ]
