# Generated by Django 5.2.17 on 2026-09-22 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_stockvaluationsnapshot"),
        ("manufacturing", "0013_remove_workcentre_work_centre_days_in_a_week_and_more"),
        ("planning", "0003_planningsettings_holiday_region_and_more"),
        ("purchasing", "0035_purchaseorderline_bom_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planningsettings",
            name="reschedule_tolerance_days",
            field=models.PositiveIntegerField(
                default=2,
                help_text="How far out a date has to be before the plan says so. Nought produces a message for every order in the plant every morning, which is how action messages get ignored; too high and a week of lateness goes unreported.",
            ),
        ),
        migrations.CreateModel(
            name="PlanningAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("expedite", "Pull in"),
                            ("defer", "Push out"),
                            ("cancel", "Cancel — nothing needs it"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("purchase", "Confirmed purchase order"),
                            ("requisition", "Purchase requisition"),
                            ("work_order", "Work order"),
                            ("byproduct", "By-product of a run"),
                            ("planned", "Planned order"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="How much of that order this is about, in the item's stocking unit. A part-received purchase is only movable for the part still coming.",
                        max_digits=18,
                    ),
                ),
                (
                    "scheduled_on",
                    models.DateField(help_text="When the order says it will arrive."),
                ),
                (
                    "wanted_on",
                    models.DateField(
                        blank=True,
                        help_text="When the demand it covers actually wants it. Empty on a cancel, where nothing wants it at all.",
                        null=True,
                    ),
                ),
                (
                    "days",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How far the date is out. Nought on a cancel.",
                    ),
                ),
                (
                    "because",
                    models.CharField(
                        help_text="The demand that sets the wanted date, in words.",
                        max_length=255,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "purchase_order_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_actions",
                        to="purchasing.purchaseorderline",
                    ),
                ),
                (
                    "requisition_line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_actions",
                        to="purchasing.purchaserequisitionline",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="planning.planningrun",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_actions",
                        to="manufacturing.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["run", "action", "-days", "item__sku", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="planning_action_quantity_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("action", "cancel"), ("wanted_on__isnull", True)),
                            models.Q(
                                models.Q(("action", "cancel"), _negated=True),
                                ("wanted_on__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="planning_action_cancel_wants_nothing",
                    ),
                ],
            },
        ),
    ]
