# Generated by Django 5.2.17 on 2026-09-22 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0017_printdesign_tool_workorder_tools_toolusage_and_more"),
        ("planning", "0004_planningsettings_reschedule_tolerance_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedorder",
            name="bottleneck",
            field=models.ForeignKey(
                blank=True,
                help_text="The machine that held this run longest, and so the one that set its dates. The only one worth adding capacity to, and the one to name when the date slips.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="manufacturing.workcentre",
            ),
        ),
        migrations.AddField(
            model_name="plannedorder",
            name="is_overloaded",
            field=models.BooleanField(
                default=False,
                help_text="The machines could not fit this run before the plan's own date however far back it was pushed. The release date is then the earliest the schedule reached, and it is a date nobody can keep.",
            ),
        ),
    ]
