# Generated by Django 5.2.17 on 2026-09-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0005_plannedorder_bottleneck_plannedorder_is_overloaded"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedorder",
            name="stand_in_note",
            field=models.CharField(
                blank=True,
                help_text="Said when an approved alternative for this item is already on the shelf. A sentence, not a substitution: changing a blend is a judgement somebody makes with the customer's specification in front of them.",
                max_length=255,
            ),
        ),
    ]
