# Generated by Django 5.2.17 on 2026-09-22 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_stockvaluationsnapshot"),
        ("planning", "0006_plannedorder_stand_in_note"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="planneddemand",
            name="source",
            field=models.CharField(
                choices=[
                    ("sales", "Sales order"),
                    ("forecast", "Forecast"),
                    ("work_order", "Open work order"),
                    ("planned", "Another planned order"),
                    ("safety", "Safety stock"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Expected shipments in the period, in the item's stocking unit.",
                        max_digits=18,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["item", "warehouse", "starts_on"],
            },
        ),
        migrations.AddField(
            model_name="planneddemand",
            name="forecast",
            field=models.ForeignKey(
                blank=True,
                help_text="The period this was expected in, when nobody has ordered it yet.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="planned_demands",
                to="planning.forecast",
            ),
        ),
        migrations.AddIndex(
            model_name="forecast",
            index=models.Index(
                fields=["item", "warehouse", "starts_on"],
                name="planning_fo_item_id_e286ba_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecast",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="forecast_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecast",
            constraint=models.CheckConstraint(
                condition=models.Q(("ends_on__gte", models.F("starts_on"))),
                name="forecast_ends_after_it_starts",
            ),
        ),
    ]
