# Generated by Django 5.2.17 on 2026-09-22 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0026_stockvaluationsnapshot"),
        ("planning", "0007_alter_planneddemand_source_forecast_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedorder",
            name="from_warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="On a transfer, the shelf it comes off.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planned_transfers_out",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="plannedorder",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="planned_from",
                to="inventory.stocktransfer",
            ),
        ),
        migrations.AlterField(
            model_name="plannedorder",
            name="kind",
            field=models.CharField(
                choices=[
                    ("make", "Make"),
                    ("buy", "Buy"),
                    ("transfer", "Move from another shelf"),
                ],
                max_length=8,
            ),
        ),
        migrations.CreateModel(
            name="TransferRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead_days",
                    models.PositiveIntegerField(
                        help_text="Calendar days on the road, including loading and booking a lorry."
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Lower is tried first, for a shelf that can be fed from more than one place.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_out",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "to_warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes_in",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["to_warehouse", "priority", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_warehouse", "to_warehouse"),
                        name="one_route_per_pair",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("from_warehouse", models.F("to_warehouse")), _negated=True
                        ),
                        name="a_route_goes_somewhere_else",
                    ),
                ],
            },
        ),
    ]
