# Generated by Django 5.2.17 on 2026-09-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0008_plannedorder_from_warehouse_plannedorder_transfer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planneddemand",
            name="source",
            field=models.CharField(
                choices=[
                    ("sales", "Sales order"),
                    ("forecast", "Forecast"),
                    ("work_order", "Open work order"),
                    ("planned", "Another planned order"),
                    ("phantom", "Through a phantom"),
                    ("safety", "Safety stock"),
                ],
                max_length=16,
            ),
        ),
    ]
