# Generated by Django 5.2.17 on 2026-09-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0009_alter_planneddemand_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedorder",
            name="fenced_from",
            field=models.DateField(
                blank=True,
                help_text="When it was actually wanted, where that fell inside the frozen zone and the order was planned for the first day outside it instead. Kept so the lateness is on the order rather than absorbed into it.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planningaction",
            name="inside_fence",
            field=models.BooleanField(
                default=False,
                help_text="Acting on this would change something inside the frozen zone — pull an order into it, or move or cancel one already there. Still said, because hiding a shortage is worse than reporting one nobody can easily fix; flagged, because it is a decision for a person and not a routine reschedule.",
            ),
        ),
        migrations.AddField(
            model_name="planningrun",
            name="fence_ends",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="The first day outside the frozen zone for this run, or blank where the plant runs without one.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="planningrun",
            name="unforecast",
            field=models.TextField(
                blank=True,
                editable=False,
                help_text="Forecast this run left out because it fell inside the demand fence, one item per line — said rather than dropped, because a forecast nobody ordered against is itself news.",
            ),
        ),
        migrations.AddField(
            model_name="planningsettings",
            name="demand_fence_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Inside this many days only real orders count. Forecast that close in and still not ordered is not going to be, and planning for it builds stock nobody will call off. Nought is off.",
            ),
        ),
        migrations.AddField(
            model_name="planningsettings",
            name="planning_fence_days",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The frozen zone, in the plant's working days from the day the plan runs. Nothing new is planned to be wanted inside it: the runs there are sequenced, the material is on the floor, and a plan that drops a fresh order into tomorrow is a plan the shift will ignore. A shortage that falls inside is planned for the first day outside and says it is late. Nought is off.",
            ),
        ),
    ]
