# Generated by Django 5.2.17 on 2026-09-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planning",
            "0010_plannedorder_fenced_from_planningaction_inside_fence_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="planneddemand",
            name="source",
            field=models.CharField(
                choices=[
                    ("sales", "Sales order"),
                    ("forecast", "Forecast"),
                    ("work_order", "Open work order"),
                    ("planned", "Another planned order"),
                    ("phantom", "Through a phantom"),
                    ("safety", "Safety stock"),
                    ("expiry", "Stock expiring unused"),
                ],
                max_length=16,
            ),
        ),
    ]
