# Generated by Django 5.2.17 on 2026-09-28 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0011_alter_planneddemand_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedorder",
            name="can_start_on",
            field=models.DateField(
                blank=True,
                help_text="For a run that could not be fitted in time: the first day the machines can take it. What its components are wanted by.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plannedorder",
            name="expected_on",
            field=models.DateField(
                blank=True,
                help_text="When it can really be ready: the day it is wanted where the machines or the vendor can manage that, otherwise forward from the plan's date on what the machines have left (or the vendor's lead time), and later again where a component holds it up.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="plannedorder",
            name="held_up_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The planned order for a component that is not ready until after this run should start.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="planning.plannedorder",
            ),
        ),
    ]
