# Generated by Django 5.2.17 on 2026-09-28 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_refold_company_wide_valuation"),
        ("manufacturing", "0047_workcentre_efficiency_percent_and_more"),
        (
            "planning",
            "0012_plannedorder_can_start_on_plannedorder_expected_on_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterScheduleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "week_of",
                    models.DateField(
                        help_text="The Monday of the week it is to be made in."
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="In the item's stocking unit.",
                        max_digits=18,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        help_text="Why it is scheduled: building ahead of a peak, a customer's call-off expected, a stock target.",
                        max_length=255,
                    ),
                ),
                (
                    "committed_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "overload_accepted",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Said when it was committed past what the machines had free.",
                        max_length=255,
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "withdrawn_reason",
                    models.CharField(blank=True, editable=False, max_length=255),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "work_order",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="manufacturing.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["week_of", "item", "id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0)),
                        name="master_schedule_quantity_positive",
                    )
                ],
            },
        ),
    ]
