# Generated by Django 5.2.17 on 2026-09-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0013_masterscheduleentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedorder",
            name="waits_for",
            field=models.CharField(
                blank=True,
                help_text="What the run cannot start without that is not a machine or a material: a printed sack's cylinders.",
                max_length=255,
            ),
        ),
    ]
