# Generated by Django 5.2.17 on 2026-10-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manufacturing", "0067_alternaterouting"),
        ("planning", "0014_plannedorder_waits_for"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedorder",
            name="routing",
            field=models.ForeignKey(
                blank=True,
                help_text="Which way the run was planned: the bill's own routing, or the alternate that could be on time when it could not.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="manufacturing.routing",
            ),
        ),
    ]
