# Generated by Django 5.2.17 on 2026-10-06 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_list_indexes"),
        ("planning", "0015_plannedorder_routing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShipmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("month", models.DateField(help_text="The first day of the month.")),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Shipped less returned that month, in the item's stock unit.",
                        max_digits=18,
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Where the figure came from: the old system's register, a ledger.",
                        max_length=128,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_history",
                        to="inventory.item",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_history",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "shipment history",
                "ordering": ["item", "warehouse", "month"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item", "warehouse", "month"),
                        name="one_history_figure_a_month",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 0)),
                        name="shipment_history_not_negative",
                    ),
                ],
            },
        ),
    ]
